// Generated by scripts/generateBlueprintSchemaTypes.mjs from src/game/sim/blueprints/blueprintSchema.json.
// Do not edit this file directly.
#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use std::collections::BTreeMap;

#[derive(Clone, Debug, PartialEq)]
pub enum BlueprintJsonValue {
    Null,
    Bool(bool),
    Number(f64),
    String(String),
    Array(Vec<BlueprintJsonValue>),
    Object(BTreeMap<String, BlueprintJsonValue>),
}

pub type UnitBlueprintId = String;

pub type StructureBlueprintId = String;

pub type TurretBlueprintId = String;

pub type ShotBlueprintId = String;

pub type ShieldMaterialId = String;

pub type SoundEntry = BlueprintJsonValue;

pub type BarrelShape = BlueprintJsonValue;

pub type TurretRangeOverrides = BlueprintJsonValue;

#[derive(Clone, Debug, PartialEq)]
pub enum TurretRangeVolume {
    TurretRangeCylinderNormal,
    TurretRangeBottomUnbounded,
    TurretRangeTopAndBottomUnbounded,
    TurretRangeSphere,
}

pub type ConstructionEmitterSize = String;

pub type ConstructionEmitterVisualSpec = BlueprintJsonValue;

pub type ResourceCost = BlueprintJsonValue;

pub type UnitSuspensionConfig = BlueprintJsonValue;

pub type EntityId = i32;

pub type PlayerId = i32;

#[derive(Clone, Debug, PartialEq)]
pub struct SensorCapabilityConfig {
    pub fullSightRadius: f64,
    pub radarRadius: f64,
    pub detectorRadius: f64,
    pub trackingRadius: f64,
    pub scanRadius: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ProjectileShotKind {
    Plasma,
    Rocket,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShieldSurfaceResponse {
    Reflect,
    Absorb,
    PassThrough,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShieldReflectionMode {
    OutsideIn,
    InsideOut,
    Both,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShieldReflectionDirection {
    ReflectNone,
    ReflectOutside,
    ReflectInside,
    ReflectBoth,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShieldReflectionEntity {
    Plasma,
    Rocket,
    Beam,
    Laser,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldReflectionEntityDirections {
    pub plasma: Option<ShieldReflectionDirection>,
    pub rocket: Option<ShieldReflectionDirection>,
    pub beam: Option<ShieldReflectionDirection>,
    pub laser: Option<ShieldReflectionDirection>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldReflectionPolicy {
    pub entities: ShieldReflectionEntityDirections,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShieldBarrierShape {
    Sphere,
    InfiniteVerticalCylinder,
    AimedCylinder,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldBarrierRatioConfig {
    pub shape: ShieldBarrierShape,
    pub outerRatio: Option<f64>,
    pub rimWidth: Option<f64>,
    pub originOffsetRadiusRatio: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretSubmunitionEmitterConfig {
    pub shotBlueprintId: String,
    pub launchForce: f64,
    pub cooldown: TurretCooldownConfig,
    pub spread: TurretSpreadConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldMaterialVisualConfig {
    pub color: f64,
    pub alpha: f64,
    pub particleAlpha: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldMaterialReflectionConfig {
    pub mode: ShieldReflectionMode,
    pub reflectivity: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldMaterialProjectileResponseConfig {
    pub plasma: ShieldSurfaceResponse,
    pub rocket: ShieldSurfaceResponse,
    pub beam: ShieldSurfaceResponse,
    pub laser: ShieldSurfaceResponse,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldMaterialHitReactionConfig {
    pub impactEvent: String,
    pub sound: Option<BlueprintJsonValue>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldMaterialBlueprint {
    pub materialId: String,
    pub reflection: ShieldMaterialReflectionConfig,
    pub projectileResponse: ShieldMaterialProjectileResponseConfig,
    pub hitReaction: ShieldMaterialHitReactionConfig,
    pub visual: ShieldMaterialVisualConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotCollision {
    pub radius: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotExplosion {
    pub radius: f64,
    pub damage: f64,
    pub force: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SubmunitionSpec {
    pub shotBlueprintId: String,
    pub count: i32,
    pub randomSpreadSpeedHorizontal: f64,
    pub randomSpreadSpeedVertical: f64,
    pub reflectedVelocityDamper: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SmokeTrailSpec {
    pub useId: Option<String>,
    pub maxPoolSize: Option<f64>,
    pub capPolicy: String,
    pub emitFramesSkip: Option<f64>,
    pub exhaustSpeed: Option<f64>,
    pub startRadius: Option<f64>,
    pub endRadiusMultiplier: Option<f64>,
    pub fadeInMs: Option<f64>,
    pub fadeOutMs: Option<f64>,
    pub maxAlpha: Option<f64>,
    pub color: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ProjectileShotBlueprint {
    pub r#type: ProjectileShotKind,
    pub shotBlueprintId: String,
    pub name: String,
    pub base: EntityBaseLedger,
    pub mass: f64,
    pub health: f64,
    pub radius: EntityRadiusConfig,
    pub detonateOnExpiry: bool,
    pub maxLifespan: Option<f64>,
    pub hitSound: Option<BlueprintJsonValue>,
    pub submunitions: Option<SubmunitionSpec>,
    pub homingTurnRate: Option<f64>,
    pub homingThrust: Option<f64>,
    pub homingDelayMs: Option<f64>,
    pub propulsionForce: Option<f64>,
    pub gravityForceMultiplier: f64,
    pub airFrictionPer60HzFrame: f64,
    pub smokeTrail: Option<SmokeTrailSpec>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShotBlueprint {
    ProjectileShotBlueprint(ProjectileShotBlueprint),
}

#[derive(Clone, Debug, PartialEq)]
pub enum ProjectileTailShape {
    Cone,
    Cylinder,
    None,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldBarrierConfig {
    pub shape: ShieldBarrierShape,
    pub innerRange: f64,
    pub outerRange: f64,
    pub originOffsetZ: f64,
    pub color: f64,
    pub alpha: f64,
    pub particleAlpha: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ProjectileShot {
    pub r#type: ProjectileShotKind,
    pub shotBlueprintId: String,
    pub base: EntityBaseLedger,
    pub mass: f64,
    pub health: f64,
    pub launchForce: f64,
    pub radius: EntityRadiusConfig,
    pub explosion: Option<ShotExplosion>,
    pub detonateOnExpiry: Option<bool>,
    pub maxLifespan: Option<f64>,
    pub homingTurnRate: Option<f64>,
    pub homingThrust: Option<f64>,
    pub homingDelayMs: Option<f64>,
    pub propulsionForce: Option<f64>,
    pub gravityForceMultiplier: f64,
    pub airFrictionPer60HzFrame: f64,
    pub trailLength: Option<f64>,
    pub submunitions: Option<SubmunitionSpec>,
    pub smokeTrail: Option<SmokeTrailSpec>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ActiveProjectileShot {
    ProjectileShot(ProjectileShot),
    BeamRay(BeamRay),
    LaserRay(LaserRay),
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShotConfig {
    ProjectileShot(ProjectileShot),
}

#[derive(Clone, Debug, PartialEq)]
pub enum ProjectileType {
    Projectile,
    Beam,
    Laser,
}

#[derive(Clone, Debug, PartialEq)]
pub enum BeamReflectorKind {
    Shield,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BeamPoint {
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub vx: f64,
    pub vy: f64,
    pub vz: f64,
    pub reflectorEntityId: Option<i32>,
    pub reflectorKind: Option<BeamReflectorKind>,
    pub reflectorPlayerId: Option<i32>,
    pub normalX: Option<f64>,
    pub normalY: Option<f64>,
    pub normalZ: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShotRuntimeType {
    Plasma,
    Rocket,
    Beam,
    Laser,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotRuntimeProfile {
    pub shotBlueprintId: String,
    pub r#type: ShotRuntimeType,
    pub projectileType: ProjectileType,
    pub isProjectile: bool,
    pub isLine: bool,
    pub isRocketLike: bool,
    pub radius: EntityRadiusConfig,
    pub deathExplosionRadius: f64,
    pub maxLifespan: f64,
    pub detonateOnExpiry: bool,
    pub hasExplosion: bool,
    pub hasSubmunitions: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotVisualProfile {
    pub projectileTailShape: ProjectileTailShape,
    pub projectileTailLengthMult: f64,
    pub projectileTailRadiusMult: f64,
    pub projectileFinSizeMult: f64,
    pub smokeTrail: Option<SmokeTrailSpec>,
    pub burnMarkWidth: f64,
    pub lineRadius: f64,
    pub lineDamageSphereRadius: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotProfile {
    pub runtime: ShotRuntimeProfile,
    pub visual: ShotVisualProfile,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldPanel {
    pub offsetX: f64,
    pub offsetY: f64,
    pub angle: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct EntityRadiusConfig {
    pub visual: f64,
    pub hitbox: f64,
    pub collision: f64,
    pub shotArmingRadius: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct EntityDeathExplosion {
    pub radius: f64,
    pub force: f64,
    pub damage: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct EntityBaseLedger {
    pub cost: BlueprintJsonValue,
    pub mass: f64,
    pub health: f64,
    pub deathExplosion: EntityDeathExplosion,
    pub radius: EntityRadiusConfig,
}

pub type TurretRadiusConfig = EntityRadiusConfig;

#[derive(Clone, Debug, PartialEq)]
pub enum TurretAimAngleType {
    RayDirect,
    RayBisectTurretAndBody,
    BallisticArcLow,
    BallisticArcLowOnlyUnder,
    BallisticArcHigh,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretAimStyle {
    pub angleType: TurretAimAngleType,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UnitLauncherAimMode {
    BallisticOrWaypoint,
    DirectTarget,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLauncherConfig {
    pub aimMode: UnitLauncherAimMode,
    pub producedUnitBlueprintId: Option<String>,
    pub autoProduce: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum TurretLockOnRelationshipInclusion {
    FriendlyEntities,
    EnemyEntities,
}

#[derive(Clone, Debug, PartialEq)]
pub enum TurretLockOnEntityFamilyInclusion {
    Buildings,
    Towers,
    Units,
    Turrets,
    Shots,
}

#[derive(Clone, Debug, PartialEq)]
pub enum LockOnRequiresTargetLockedOntoSelf {
    Ignore,
    Require,
    PreferReacquire,
    PreferHold,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LockOnInclusionObject {
    pub includeLockOnLevel0FriendsAndEnemies: Vec<TurretLockOnRelationshipInclusion>,
    pub includeLockOnLevel0Entities: Vec<TurretLockOnEntityFamilyInclusion>,
    pub includeLockOnLevel1Buildings: Vec<String>,
    pub includeLockOnLevel1Towers: Vec<String>,
    pub includeLockOnLevel1Units: Vec<String>,
    pub includeLockOnLevel1Turrets: Vec<String>,
    pub includeLockOnLevel1Shots: Vec<String>,
    pub lockOnRequiresTargetLockedOntoSelf: LockOnRequiresTargetLockedOntoSelf,
}

#[derive(Clone, Debug, PartialEq)]
pub enum WeaponKind {
    Attack,
    Construction,
    Repair,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretSpreadConfig {
    pub angle: f64,
    pub pelletCount: i32,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretBurstConfig {
    pub count: i32,
    pub delay: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretCooldownConfig {
    pub duration: f64,
    pub durationRandomness: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretAudioConfig {
    pub fireSound: BlueprintJsonValue,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretBlueprint {
    pub turretBlueprintId: String,
    pub name: String,
    pub kind: WeaponKind,
    pub range: f64,
    pub rangeVolume: TurretRangeVolume,
    pub cooldown: Option<TurretCooldownConfig>,
    pub color: f64,
    pub turretTurnAccel: f64,
    pub turretDrag: f64,
    pub barrel: BlueprintJsonValue,
    pub rangeMultiplierOverrides: BlueprintJsonValue,
    pub eventsSmooth: bool,
    pub launchForce: f64,
    pub isManualFire: bool,
    pub passive: bool,
    pub requiresNonObstructedLineOfSight: bool,
    pub spread: Option<TurretSpreadConfig>,
    pub submunitions: Option<TurretSubmunitionEmitterConfig>,
    pub burst: Option<TurretBurstConfig>,
    pub shieldPanels: Vec<ShieldPanel>,
    pub audio: Option<TurretAudioConfig>,
    pub radius: TurretRadiusConfig,
    pub headOnly: bool,
    pub aimStyle: TurretAimStyle,
    pub verticalLauncher: bool,
    pub idlePitch: f64,
    pub groundAimFraction: Option<f64>,
    pub constructionEmitter: Option<BlueprintJsonValue>,
    pub unitLauncher: Option<UnitLauncherConfig>,
    pub includeLockOnLevel0FriendsAndEnemies: Vec<TurretLockOnRelationshipInclusion>,
    pub includeLockOnLevel0Entities: Vec<TurretLockOnEntityFamilyInclusion>,
    pub includeLockOnLevel1Buildings: Vec<String>,
    pub includeLockOnLevel1Towers: Vec<String>,
    pub includeLockOnLevel1Units: Vec<String>,
    pub includeLockOnLevel1Turrets: Vec<String>,
    pub includeLockOnLevel1Shots: Vec<String>,
    pub lockOnRequiresTargetLockedOntoSelf: LockOnRequiresTargetLockedOntoSelf,
    pub emissionKind: Option<EmissionKind>,
    pub emissionBlueprintId: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct MountOffset {
    pub x: f64,
    pub y: f64,
    pub z: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitTurretMountZResolver {
    pub kind: String,
    pub bodyTopZFrac: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretMount {
    pub turretBlueprintId: String,
    pub mount: MountOffset,
    pub shieldPanels: Option<Vec<ShieldPanel>>,
    pub hostDirected: bool,
    pub requiredEngagedForFightStop: bool,
    pub zResolver: Option<UnitTurretMountZResolver>,
    pub visualVariant: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BuildingTurretMount {
    pub turretBlueprintId: String,
    pub mount: MountOffset,
    pub shieldPanels: Option<Vec<ShieldPanel>>,
    pub hostDirected: bool,
    pub visualVariant: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct WheelConfig {
    pub wheelDistX: f64,
    pub wheelDistY: f64,
    pub treadLength: f64,
    pub treadWidth: f64,
    pub wheelRadius: f64,
    pub rotationSpeed: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TreadConfig {
    pub treadOffset: f64,
    pub treadLength: f64,
    pub treadWidth: f64,
    pub wheelRadius: f64,
    pub rotationSpeed: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LegLayoutEntry {
    pub attachOffsetXFrac: f64,
    pub attachOffsetYFrac: f64,
    pub upperLegLengthFrac: f64,
    pub lowerLegLengthFrac: f64,
    pub snapTriggerAngle: f64,
    pub snapTargetAngle: f64,
    pub snapDistanceMultiplier: f64,
    pub extensionThreshold: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LegConfig {
    pub upperThickness: f64,
    pub lowerThickness: f64,
    pub hipRadius: f64,
    pub kneeRadius: f64,
    pub lerpDuration: f64,
    pub leftSide: Vec<LegLayoutEntry>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LocomotionPhysics {
    pub driveForce: f64,
    pub traction: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum PathfindingTerrainMode {
    Land,
    Anywhere,
}

#[derive(Clone, Debug, PartialEq)]
pub struct PathfindingBlueprint {
    pub pathfindingBlueprintId: String,
    pub terrainMode: PathfindingTerrainMode,
    pub maxSlopeDeg: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct HoverConfig {
    pub gravityCounterUpwardForceRatio: f64,
    pub hoverHeightUpwardForce: f64,
    pub hoverHeightUpwardForceRandomizationAmount: Option<f64>,
    pub hoverHeightUpwardForceEMA: Option<f64>,
    pub fanDistX: f64,
    pub fanDistY: f64,
    pub fanPositionRadius: Option<f64>,
    pub fanLayout: Option<String>,
    pub fanRadius: f64,
    pub fanRingTubeRadius: f64,
    pub fanOutwardAngleDeg: Option<f64>,
    pub fanSpinRadPerSec: Option<f64>,
    pub tailFanOffsetX: Option<f64>,
    pub tailFanRadius: Option<f64>,
    pub tailFanRingTubeRadius: Option<f64>,
    pub tailFanBackAngleDeg: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct FlyingConfig {
    pub gravityCounterUpwardForceRatio: f64,
    pub hoverHeightUpwardForce: f64,
    pub hoverHeightUpwardForceRandomizationAmount: Option<f64>,
    pub hoverHeightUpwardForceEMA: Option<f64>,
    pub wingEnabled: Option<bool>,
    pub wingSpan: Option<f64>,
    pub wingChord: Option<f64>,
    pub wingOffsetX: Option<f64>,
    pub wingHeight: Option<f64>,
    pub wingThickness: Option<f64>,
    pub wingDihedralDeg: Option<f64>,
    pub wingSweepFrac: Option<f64>,
    pub tailWingSpan: Option<f64>,
    pub tailWingChord: Option<f64>,
    pub tailWingOffsetX: Option<f64>,
    pub tailWingHeight: Option<f64>,
    pub tailWingThickness: Option<f64>,
    pub tailWingDihedralDeg: Option<f64>,
    pub tailWingSweepFrac: Option<f64>,
    pub tailWingMirrorX: Option<bool>,
    pub jetOffsetX: f64,
    pub jetOffsetY: f64,
    pub jetOffsetZ: f64,
    pub jetRadius: f64,
    pub jetLength: f64,
    pub jetCount: Option<i32>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LocomotionBlueprintWheels {
    pub r#type: String,
    pub physics: LocomotionPhysics,
    pub pathfindingBlueprintId: String,
    pub pathfinding: PathfindingBlueprint,
    pub config: WheelConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LocomotionBlueprintTreads {
    pub r#type: String,
    pub physics: LocomotionPhysics,
    pub pathfindingBlueprintId: String,
    pub pathfinding: PathfindingBlueprint,
    pub config: TreadConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LocomotionBlueprintLegs {
    pub r#type: String,
    pub physics: LocomotionPhysics,
    pub pathfindingBlueprintId: String,
    pub pathfinding: PathfindingBlueprint,
    pub config: LegConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LocomotionBlueprintHover {
    pub r#type: String,
    pub physics: LocomotionPhysics,
    pub pathfindingBlueprintId: String,
    pub pathfinding: PathfindingBlueprint,
    pub config: HoverConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LocomotionBlueprintFlying {
    pub r#type: String,
    pub physics: LocomotionPhysics,
    pub pathfindingBlueprintId: String,
    pub pathfinding: PathfindingBlueprint,
    pub config: FlyingConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub enum LocomotionBlueprint {
    LocomotionBlueprintWheels(LocomotionBlueprintWheels),
    LocomotionBlueprintTreads(LocomotionBlueprintTreads),
    LocomotionBlueprintLegs(LocomotionBlueprintLegs),
    LocomotionBlueprintHover(LocomotionBlueprintHover),
    LocomotionBlueprintFlying(LocomotionBlueprintFlying),
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapePartCircle {
    pub kind: String,
    pub offsetForward: f64,
    pub offsetLateral: Option<f64>,
    pub radiusFrac: f64,
    pub yFrac: Option<f64>,
    pub centerYFrac: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapePartOval {
    pub kind: String,
    pub offsetForward: f64,
    pub offsetLateral: Option<f64>,
    pub xFrac: f64,
    pub yFrac: f64,
    pub zFrac: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapePartCylinder {
    pub kind: String,
    pub offsetForward: f64,
    pub offsetLateral: Option<f64>,
    pub lengthFrac: f64,
    pub radiusFrac: f64,
    pub centerYFrac: Option<f64>,
    pub pitchRad: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapePartCone {
    pub kind: String,
    pub offsetForward: f64,
    pub offsetLateral: Option<f64>,
    pub lengthFrac: f64,
    pub radiusFrac: f64,
    pub centerYFrac: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UnitBodyShapePart {
    UnitBodyShapePartCircle(UnitBodyShapePartCircle),
    UnitBodyShapePartOval(UnitBodyShapePartOval),
    UnitBodyShapePartCylinder(UnitBodyShapePartCylinder),
    UnitBodyShapePartCone(UnitBodyShapePartCone),
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapePolygon {
    pub kind: String,
    pub sides: i32,
    pub radiusFrac: f64,
    pub heightFrac: f64,
    pub rotation: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapeRect {
    pub kind: String,
    pub lengthFrac: f64,
    pub widthFrac: f64,
    pub heightFrac: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapeRhombus {
    pub kind: String,
    pub lengthFrac: f64,
    pub widthFrac: f64,
    pub heightFrac: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapeCircle {
    pub kind: String,
    pub radiusFrac: f64,
    pub yFrac: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapeOval {
    pub kind: String,
    pub xFrac: f64,
    pub yFrac: f64,
    pub zFrac: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapeComposite {
    pub kind: String,
    pub parts: Vec<UnitBodyShapePart>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UnitBodyShape {
    UnitBodyShapePolygon(UnitBodyShapePolygon),
    UnitBodyShapeRect(UnitBodyShapeRect),
    UnitBodyShapeRhombus(UnitBodyShapeRhombus),
    UnitBodyShapeCircle(UnitBodyShapeCircle),
    UnitBodyShapeOval(UnitBodyShapeOval),
    UnitBodyShapeComposite(UnitBodyShapeComposite),
}

#[derive(Clone, Debug, PartialEq)]
pub struct EntityHudBlueprint {
    pub barsOffsetAboveTop: f64,
}

pub type UnitRadiusConfig = EntityRadiusConfig;

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBuilderConfig {
    pub buildRange: f64,
    pub constructionRate: f64,
    pub allowedBuildBlueprintIds: Vec<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitDgunConfig {
    pub turretBlueprintId: String,
    pub energyCost: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitSupportSurfaceNone {
    pub kind: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitSupportSurfaceDiscTop {
    pub kind: String,
    pub topZ: f64,
    pub radius: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UnitSupportSurface {
    UnitSupportSurfaceNone(UnitSupportSurfaceNone),
    UnitSupportSurfaceDiscTop(UnitSupportSurfaceDiscTop),
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBlueprint {
    pub unitBlueprintId: String,
    pub name: String,
    pub shortName: String,
    pub base: EntityBaseLedger,
    pub hp: f64,
    pub radius: UnitRadiusConfig,
    pub bodyCenterHeight: f64,
    pub supportSurface: UnitSupportSurface,
    pub fullVisionRadius: f64,
    pub sensors: SensorCapabilityConfig,
    pub mass: f64,
    pub cost: BlueprintJsonValue,
    pub turrets: Vec<TurretMount>,
    pub bodyShape: UnitBodyShape,
    pub hud: EntityHudBlueprint,
    pub legAttachHeightFrac: Option<f64>,
    pub locomotion: LocomotionBlueprint,
    pub suspension: Option<BlueprintJsonValue>,
    pub builder: Option<UnitBuilderConfig>,
    pub dgun: Option<UnitDgunConfig>,
    pub deathSound: Option<BlueprintJsonValue>,
    pub includeLockOnLevel0FriendsAndEnemies: Vec<TurretLockOnRelationshipInclusion>,
    pub includeLockOnLevel0Entities: Vec<TurretLockOnEntityFamilyInclusion>,
    pub includeLockOnLevel1Buildings: Vec<String>,
    pub includeLockOnLevel1Towers: Vec<String>,
    pub includeLockOnLevel1Units: Vec<String>,
    pub includeLockOnLevel1Turrets: Vec<String>,
    pub includeLockOnLevel1Shots: Vec<String>,
    pub lockOnRequiresTargetLockedOntoSelf: LockOnRequiresTargetLockedOntoSelf,
}

pub type RayBlueprintId = String;

pub type ShieldBlueprintId = String;

#[derive(Clone, Debug, PartialEq)]
pub enum RayType {
    Beam,
    Laser,
}

#[derive(Clone, Debug, PartialEq)]
pub enum EmissionKind {
    Shot,
    Ray,
    Shield,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BeamRayBlueprint {
    pub r#type: String,
    pub dps: f64,
    pub force: f64,
    pub recoil: f64,
    pub radius: f64,
    pub width: f64,
    pub damageSphere: ShotCollision,
    pub gravityForceMultiplier: f64,
    pub continuousSound: BeamContinuousSoundConfig,
    pub hitSound: Option<BlueprintJsonValue>,
    pub rayBlueprintId: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BeamContinuousSoundConfig {
    pub harmonicSeriesIndex: i32,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LaserRayBlueprint {
    pub r#type: String,
    pub dps: f64,
    pub force: f64,
    pub recoil: f64,
    pub radius: f64,
    pub width: f64,
    pub damageSphere: ShotCollision,
    pub duration: f64,
    pub gravityForceMultiplier: f64,
    pub hitSound: Option<BlueprintJsonValue>,
    pub rayBlueprintId: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldBlueprint {
    pub r#type: String,
    pub materialId: String,
    pub angle: f64,
    pub transitionTime: f64,
    pub reflection: ShieldReflectionPolicy,
    pub barrier: Option<ShieldBarrierRatioConfig>,
    pub hitSound: Option<BlueprintJsonValue>,
    pub shieldBlueprintId: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RayBlueprint {
    BeamRayBlueprint(BeamRayBlueprint),
    LaserRayBlueprint(LaserRayBlueprint),
}

#[derive(Clone, Debug, PartialEq)]
pub struct BeamRay {
    pub r#type: String,
    pub dps: f64,
    pub force: f64,
    pub recoil: f64,
    pub radius: f64,
    pub width: f64,
    pub damageSphere: ShotCollision,
    pub gravityForceMultiplier: f64,
    pub rayBlueprintId: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LaserRay {
    pub r#type: String,
    pub dps: f64,
    pub force: f64,
    pub recoil: f64,
    pub radius: f64,
    pub width: f64,
    pub damageSphere: ShotCollision,
    pub duration: f64,
    pub gravityForceMultiplier: f64,
    pub rayBlueprintId: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RayConfig {
    BeamRay(BeamRay),
    LaserRay(LaserRay),
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldConfig {
    pub r#type: String,
    pub material: ShieldMaterialBlueprint,
    pub angle: f64,
    pub transitionTime: f64,
    pub reflection: ShieldReflectionPolicy,
    pub barrier: Option<ShieldBarrierConfig>,
    pub shieldBlueprintId: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum EmissionConfig {
    ProjectileShot(ProjectileShot),
    BeamRay(BeamRay),
    LaserRay(LaserRay),
    ShieldConfig(ShieldConfig),
}
