// Generated by scripts/generateBlueprintSchemaTypes.mjs from src/game/sim/blueprints/blueprintSchema.json.
// Do not edit this file directly.
#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use std::collections::BTreeMap;

#[derive(Clone, Debug, PartialEq)]
pub enum BlueprintJsonValue {
    Null,
    Bool(bool),
    Number(f64),
    String(String),
    Array(Vec<BlueprintJsonValue>),
    Object(BTreeMap<String, BlueprintJsonValue>),
}

pub type UnitBlueprintId = String;

pub type StructureBlueprintId = String;

pub type TurretBlueprintId = String;

pub type ShotBlueprintId = String;

pub type ShieldMaterialId = String;

pub type SoundEntry = BlueprintJsonValue;

pub type BarrelShape = BlueprintJsonValue;

pub type TurretRangeOverrides = BlueprintJsonValue;

#[derive(Clone, Debug, PartialEq)]
pub enum TurretRangeVolume {
    TurretRangeCylinderNormal,
    TurretRangeBottomUnbounded,
    TurretRangeTopWaterAndBottomUnbounded,
    TurretRangeTopAndBottomUnbounded,
    TurretRangeSphere,
}

pub type ConstructionEmitterSize = String;

pub type ConstructionEmitterVisualSpec = BlueprintJsonValue;

pub type ResourceCost = BlueprintJsonValue;

pub type UnitSuspensionConfig = BlueprintJsonValue;

pub type EntityId = i32;

pub type PlayerId = i32;

#[derive(Clone, Debug, PartialEq)]
pub struct SensorCapabilityConfig {
    pub fullSightRadius: f64,
    pub radarRadius: f64,
    pub detectorRadius: f64,
    pub trackingRadius: f64,
    pub scanRadius: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ProjectileShotKind {
    Plasma,
    Rocket,
    Missile,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShotLocomotionMotionModel {
    Ballistic,
    ThrustGuided,
    ConstantSpeedGuided,
    TerrainFollowing,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShotLocomotionTerminalOutcome {
    Detonate,
    Despawn,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShotLocomotionTransitionOutcome {
    Continue,
    ContinueBallistic,
    Detonate,
    Despawn,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotLocomotionMediumPhysics {
    pub operational: bool,
    pub propulsionForce: f64,
    pub guidanceThrust: f64,
    pub turnRate: f64,
    pub velocityFrictionPer60HzFrame: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotLocomotionGroundPhysics {
    pub mode: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotLocomotionMedia {
    pub air: ShotLocomotionMediumPhysics,
    pub water: ShotLocomotionMediumPhysics,
    pub ground: ShotLocomotionGroundPhysics,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotLocomotionTransitions {
    pub enterWater: ShotLocomotionTransitionOutcome,
    pub exitWater: ShotLocomotionTransitionOutcome,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotLocomotionTerminalPolicy {
    pub entityImpact: ShotLocomotionTerminalOutcome,
    pub groundContact: ShotLocomotionTerminalOutcome,
    pub expiry: ShotLocomotionTerminalOutcome,
    pub destroyed: ShotLocomotionTerminalOutcome,
    pub reflectorImpact: ShotLocomotionTerminalOutcome,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotLocomotion {
    pub presetId: String,
    pub motionModel: ShotLocomotionMotionModel,
    pub maxLifespanMs: Option<f64>,
    pub gravityForceMultiplier: f64,
    pub guidanceDelayMs: f64,
    pub media: ShotLocomotionMedia,
    pub transitions: ShotLocomotionTransitions,
    pub terminal: ShotLocomotionTerminalPolicy,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShieldSurfaceResponse {
    Reflect,
    Absorb,
    PassThrough,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShieldReflectionMode {
    OutsideIn,
    InsideOut,
    Both,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShieldReflectionDirection {
    ReflectNone,
    ReflectOutside,
    ReflectInside,
    ReflectBoth,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShieldReflectionEntity {
    Plasma,
    Rocket,
    Missile,
    Beam,
    Laser,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldReflectionEntityDirections {
    pub plasma: Option<ShieldReflectionDirection>,
    pub rocket: Option<ShieldReflectionDirection>,
    pub missile: Option<ShieldReflectionDirection>,
    pub beam: Option<ShieldReflectionDirection>,
    pub laser: Option<ShieldReflectionDirection>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldReflectionPolicy {
    pub entities: ShieldReflectionEntityDirections,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShieldBarrierShape {
    Sphere,
    InfiniteVerticalCylinder,
    AimedCylinder,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldBarrierRatioConfig {
    pub shape: ShieldBarrierShape,
    pub outerRatio: Option<f64>,
    pub rimWidth: Option<f64>,
    pub originOffsetRadiusRatio: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretSubmunitionEmitterConfig {
    pub shotBlueprintId: String,
    pub launchForce: f64,
    pub cooldown: TurretCooldownConfig,
    pub spread: TurretSpreadConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldMaterialVisualConfig {
    pub color: f64,
    pub alpha: f64,
    pub particleAlpha: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldMaterialReflectionConfig {
    pub mode: ShieldReflectionMode,
    pub reflectivity: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldMaterialProjectileResponseConfig {
    pub plasma: ShieldSurfaceResponse,
    pub rocket: ShieldSurfaceResponse,
    pub beam: ShieldSurfaceResponse,
    pub laser: ShieldSurfaceResponse,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldMaterialHitReactionConfig {
    pub impactEvent: String,
    pub sound: Option<BlueprintJsonValue>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldMaterialBlueprint {
    pub materialId: String,
    pub reflection: ShieldMaterialReflectionConfig,
    pub projectileResponse: ShieldMaterialProjectileResponseConfig,
    pub hitReaction: ShieldMaterialHitReactionConfig,
    pub visual: ShieldMaterialVisualConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotCollision {
    pub radius: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotExplosion {
    pub radius: f64,
    pub damage: f64,
    pub force: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SubmunitionSpec {
    pub shotBlueprintId: String,
    pub count: i32,
    pub randomSpreadSpeedHorizontal: f64,
    pub randomSpreadSpeedVertical: f64,
    pub reflectedVelocityDamper: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SmokeTrailSpec {
    pub useId: Option<String>,
    pub maxPoolSize: Option<f64>,
    pub capPolicy: String,
    pub emitFramesSkip: Option<f64>,
    pub exhaustSpeed: Option<f64>,
    pub startRadius: Option<f64>,
    pub endRadiusMultiplier: Option<f64>,
    pub fadeInMs: Option<f64>,
    pub fadeOutMs: Option<f64>,
    pub maxAlpha: Option<f64>,
    pub color: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ProjectileShotBlueprint {
    pub r#type: ProjectileShotKind,
    pub shotBlueprintId: String,
    pub name: String,
    pub base: EntityBaseLedger,
    pub mass: f64,
    pub health: f64,
    pub radius: EntityRadiusConfig,
    pub shotLocomotionPresetId: String,
    pub hitSound: Option<BlueprintJsonValue>,
    pub submunitions: Option<SubmunitionSpec>,
    pub smokeTrail: Option<SmokeTrailSpec>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShotBlueprint {
    ProjectileShotBlueprint(ProjectileShotBlueprint),
}

#[derive(Clone, Debug, PartialEq)]
pub enum ProjectileTailShape {
    Cone,
    Cylinder,
    None,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldBarrierConfig {
    pub shape: ShieldBarrierShape,
    pub innerRange: f64,
    pub outerRange: f64,
    pub originOffsetZ: f64,
    pub color: f64,
    pub alpha: f64,
    pub particleAlpha: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ProjectileShot {
    pub r#type: ProjectileShotKind,
    pub shotBlueprintId: String,
    pub base: EntityBaseLedger,
    pub mass: f64,
    pub health: f64,
    pub launchForce: f64,
    pub radius: EntityRadiusConfig,
    pub explosion: Option<ShotExplosion>,
    pub shotLocomotion: ShotLocomotion,
    pub trailLength: Option<f64>,
    pub submunitions: Option<SubmunitionSpec>,
    pub smokeTrail: Option<SmokeTrailSpec>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ActiveProjectileShot {
    ProjectileShot(ProjectileShot),
    BeamRay(BeamRay),
    LaserRay(LaserRay),
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShotConfig {
    ProjectileShot(ProjectileShot),
}

#[derive(Clone, Debug, PartialEq)]
pub enum ProjectileType {
    Projectile,
    Beam,
    Laser,
}

#[derive(Clone, Debug, PartialEq)]
pub enum BeamReflectorKind {
    Shield,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BeamPoint {
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub vx: f64,
    pub vy: f64,
    pub vz: f64,
    pub reflectorEntityId: Option<i32>,
    pub reflectorKind: Option<BeamReflectorKind>,
    pub reflectorPlayerId: Option<i32>,
    pub normalX: Option<f64>,
    pub normalY: Option<f64>,
    pub normalZ: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShotRuntimeType {
    Plasma,
    Rocket,
    Missile,
    Beam,
    Laser,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotRuntimeProfile {
    pub shotBlueprintId: String,
    pub r#type: ShotRuntimeType,
    pub projectileType: ProjectileType,
    pub isProjectile: bool,
    pub isLine: bool,
    pub isRocketLike: bool,
    pub radius: EntityRadiusConfig,
    pub deathExplosionRadius: f64,
    pub maxLifespan: f64,
    pub detonateOnExpiry: bool,
    pub hasExplosion: bool,
    pub hasSubmunitions: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotVisualProfile {
    pub projectileTailShape: ProjectileTailShape,
    pub projectileTailLengthMult: f64,
    pub projectileTailRadiusMult: f64,
    pub projectileFinSizeMult: f64,
    pub smokeTrail: Option<SmokeTrailSpec>,
    pub burnMarkWidth: f64,
    pub lineRadius: f64,
    pub lineDamageSphereRadius: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotProfile {
    pub runtime: ShotRuntimeProfile,
    pub visual: ShotVisualProfile,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldPanel {
    pub offsetX: f64,
    pub offsetY: f64,
    pub angle: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct EntityRadiusConfig {
    pub other: f64,
    pub hitbox: f64,
    pub collision: f64,
    pub shotArmingRadius: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct EntityDeathExplosion {
    pub radius: f64,
    pub force: f64,
    pub damage: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct EntityBaseLedger {
    pub cost: BlueprintJsonValue,
    pub mass: f64,
    pub health: f64,
    pub deathExplosion: EntityDeathExplosion,
    pub radius: EntityRadiusConfig,
}

pub type TurretRadiusConfig = EntityRadiusConfig;

#[derive(Clone, Debug, PartialEq)]
pub enum TurretAimAngleType {
    RayDirect,
    RayBisectTurretAndBody,
    BallisticArcLow,
    BallisticArcLowOnlyUnder,
    BallisticArcHigh,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretAimStyle {
    pub angleType: TurretAimAngleType,
}

#[derive(Clone, Debug, PartialEq)]
pub enum TurretLockOnRelationshipInclusion {
    FriendlyEntities,
    EnemyEntities,
}

#[derive(Clone, Debug, PartialEq)]
pub enum TurretLockOnEntityFamilyInclusion {
    Buildings,
    Towers,
    Units,
    Turrets,
    Shots,
}

#[derive(Clone, Debug, PartialEq)]
pub enum LockOnRequiresTargetLockedOntoSelf {
    Ignore,
    Require,
    PreferReacquire,
    PreferHold,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LockOnInclusionObject {
    pub includeLockOnLevel0FriendsAndEnemies: Vec<TurretLockOnRelationshipInclusion>,
    pub includeLockOnLevel0Entities: Vec<TurretLockOnEntityFamilyInclusion>,
    pub includeLockOnLevel1Buildings: Vec<String>,
    pub includeLockOnLevel1Towers: Vec<String>,
    pub includeLockOnLevel1Units: Vec<String>,
    pub includeLockOnLevel1Turrets: Vec<String>,
    pub includeLockOnLevel1Shots: Vec<String>,
    pub lockOnRequiresTargetLockedOntoSelf: LockOnRequiresTargetLockedOntoSelf,
}

#[derive(Clone, Debug, PartialEq)]
pub enum TurretEmitterKind {
    Attack,
    Spawn,
    ResourcePylon,
}

#[derive(Clone, Debug, PartialEq)]
pub enum TurretMountControlMode {
    Host,
    Autonomous,
    Manual,
}

#[derive(Clone, Debug, PartialEq)]
pub enum SpawnProducedKind {
    BuildingsAndTowers,
    Units,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ResourcePylonResource {
    Metal,
    Energy,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ResourcePylonRole {
    Construction,
    Extraction,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SpawnTurretConfig {
    pub producedKind: SpawnProducedKind,
    pub producedBlueprintId: Option<String>,
    pub producesNanoframe: bool,
    pub cooldownMs: f64,
    pub launchForce: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ResourcePylonConfig {
    pub resource: ResourcePylonResource,
    pub role: ResourcePylonRole,
    pub radius: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretSpreadConfig {
    pub angle: f64,
    pub pelletCount: i32,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretBurstConfig {
    pub count: i32,
    pub delay: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretCooldownConfig {
    pub duration: f64,
    pub durationRandomness: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretAudioConfig {
    pub fireSound: BlueprintJsonValue,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretBlueprint {
    pub turretBlueprintId: String,
    pub name: String,
    pub kind: TurretEmitterKind,
    pub range: f64,
    pub rangeVolume: TurretRangeVolume,
    pub cooldown: Option<TurretCooldownConfig>,
    pub color: f64,
    pub turretTurnAccel: f64,
    pub turretDrag: f64,
    pub barrel: BlueprintJsonValue,
    pub rangeMultiplierOverrides: BlueprintJsonValue,
    pub eventsSmooth: bool,
    pub launchForce: f64,
    pub addTurretVelocityToEmissionLaunch: bool,
    pub passive: bool,
    pub requiresNonObstructedLineOfSight: bool,
    pub spread: Option<TurretSpreadConfig>,
    pub submunitions: Option<TurretSubmunitionEmitterConfig>,
    pub burst: Option<TurretBurstConfig>,
    pub shieldPanels: Vec<ShieldPanel>,
    pub audio: Option<TurretAudioConfig>,
    pub radius: TurretRadiusConfig,
    pub headOnly: bool,
    pub aimStyle: TurretAimStyle,
    pub verticalLauncher: bool,
    pub requiresFullSight: Option<bool>,
    pub idlePitch: f64,
    pub groundAimFraction: Option<f64>,
    pub constructionEmitter: Option<BlueprintJsonValue>,
    pub spawn: Option<SpawnTurretConfig>,
    pub resourcePylon: Option<ResourcePylonConfig>,
    pub includeLockOnLevel0FriendsAndEnemies: Vec<TurretLockOnRelationshipInclusion>,
    pub includeLockOnLevel0Entities: Vec<TurretLockOnEntityFamilyInclusion>,
    pub includeLockOnLevel1Buildings: Vec<String>,
    pub includeLockOnLevel1Towers: Vec<String>,
    pub includeLockOnLevel1Units: Vec<String>,
    pub includeLockOnLevel1Turrets: Vec<String>,
    pub includeLockOnLevel1Shots: Vec<String>,
    pub lockOnRequiresTargetLockedOntoSelf: LockOnRequiresTargetLockedOntoSelf,
    pub emissionKind: Option<EmissionKind>,
    pub emissionBlueprintId: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct MountOffset {
    pub x: f64,
    pub y: f64,
    pub z: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitTurretMountZResolver {
    pub kind: String,
    pub bodyTopZFrac: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretMount {
    pub mountId: String,
    pub turretBlueprintId: String,
    pub mount: MountOffset,
    pub shieldPanels: Option<Vec<ShieldPanel>>,
    pub controlMode: TurretMountControlMode,
    pub requiredEngagedForFightStop: bool,
    pub zResolver: Option<UnitTurretMountZResolver>,
    pub visualVariant: Option<String>,
    pub producedBlueprintId: Option<String>,
    pub allowedBuildBlueprintIds: Option<Vec<String>>,
    pub productionHoldAnchor: Option<String>,
    pub constructionRate: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BuildingTurretMount {
    pub mountId: String,
    pub turretBlueprintId: String,
    pub mount: MountOffset,
    pub shieldPanels: Option<Vec<ShieldPanel>>,
    pub controlMode: TurretMountControlMode,
    pub visualVariant: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct WheelConfig {
    pub wheelDistX: f64,
    pub wheelDistY: f64,
    pub treadLength: f64,
    pub treadWidth: f64,
    pub wheelRadius: f64,
    pub rotationSpeed: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TreadConfig {
    pub treadOffset: f64,
    pub treadLength: f64,
    pub treadWidth: f64,
    pub wheelRadius: f64,
    pub rotationSpeed: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LegAttachmentPoint {
    pub xUnitRadiusRatio: f64,
    pub yUnitRadiusRatio: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LegSegment {
    pub lengthUnitRadiusRatio: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LegSegments {
    pub upper: LegSegment,
    pub lower: LegSegment,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LegFootSphere {
    pub originExtensionRatio: f64,
    pub radiusLegLengthRatio: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LegLayoutEntry {
    pub attachmentPoint: LegAttachmentPoint,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LegChoppingSphere {
    pub radiusAverageFootSphereOriginDistanceRatio: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LegSnapRay {
    pub originBoundarySpanRatio: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LegConfig {
    pub upperThickness: f64,
    pub lowerThickness: f64,
    pub hipRadius: f64,
    pub kneeRadius: f64,
    pub lerpDuration: f64,
    pub segments: LegSegments,
    pub footSphere: LegFootSphere,
    pub choppingSphere: LegChoppingSphere,
    pub snapRay: LegSnapRay,
    pub leftSide: Vec<LegLayoutEntry>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct FlipperConfig {
    pub frontOffsetXFrac: f64,
    pub rearOffsetXFrac: f64,
    pub lateralOffsetFrac: f64,
    pub rootHeightFrac: f64,
    pub frontLengthFrac: f64,
    pub rearLengthFrac: f64,
    pub rootChordFrac: f64,
    pub tipChordFrac: f64,
    pub thicknessFrac: f64,
    pub groundDownAngleDeg: f64,
    pub groundSweepAngleDeg: f64,
    pub waterStrokeAngleDeg: f64,
    pub cycleDistanceFrac: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SwimConfig {
    pub pectoralOffsetXFrac: f64,
    pub pectoralLateralOffsetFrac: f64,
    pub pectoralHeightFrac: f64,
    pub pectoralSpanFrac: f64,
    pub pectoralRootChordFrac: f64,
    pub pectoralTipChordFrac: f64,
    pub rearFanOffsetXFrac: f64,
    pub rearFanHeightFrac: f64,
    pub rearFanRadius: f64,
    pub rearFanRingTubeRadius: f64,
    pub rearFanSpinRadPerSec: f64,
    pub thicknessFrac: f64,
    pub strokeAngleDeg: f64,
    pub cycleDistanceFrac: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LocomotionAirLiftPhysics {
    pub surfaceFollowingInverseForceFromGround: f64,
    pub surfaceFollowingInverseForceFromWater: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LocomotionWaterLiftPhysics {
    pub surfaceFollowingInverseForceFromGround: f64,
    pub surfaceFollowingProportionalForceFromWater: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LocomotionAirFluidBodyPhysics {
    pub lift: LocomotionAirLiftPhysics,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LocomotionWaterFluidBodyPhysics {
    pub lift: LocomotionWaterLiftPhysics,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitUnitLocomotionBlueprintPhysics {
    pub air: LocomotionAirFluidBodyPhysics,
    pub water: LocomotionWaterFluidBodyPhysics,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionEnvironmentalHazardPolicy {
    pub waterFatal: bool,
    pub fatalSubmergedFraction: f64,
    pub fatalExposureSeconds: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct HoverConfig {
    pub fanDistX: f64,
    pub fanDistY: f64,
    pub fanPositionRadius: Option<f64>,
    pub fanLayout: Option<String>,
    pub fanRadius: f64,
    pub fanRingTubeRadius: f64,
    pub fanOutwardAngleDeg: Option<f64>,
    pub fanSpinRadPerSec: Option<f64>,
    pub tailFanOffsetX: Option<f64>,
    pub tailFanRadius: Option<f64>,
    pub tailFanRingTubeRadius: Option<f64>,
    pub tailFanBackAngleDeg: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct FlyingConfig {
    pub wingEnabled: Option<bool>,
    pub wingSpan: Option<f64>,
    pub wingChord: Option<f64>,
    pub wingOffsetX: Option<f64>,
    pub wingHeight: Option<f64>,
    pub wingThickness: Option<f64>,
    pub wingDihedralDeg: Option<f64>,
    pub wingSweepFrac: Option<f64>,
    pub tailWingSpan: Option<f64>,
    pub tailWingChord: Option<f64>,
    pub tailWingOffsetX: Option<f64>,
    pub tailWingHeight: Option<f64>,
    pub tailWingThickness: Option<f64>,
    pub tailWingDihedralDeg: Option<f64>,
    pub tailWingSweepFrac: Option<f64>,
    pub tailWingMirrorX: Option<bool>,
    pub jetOffsetX: f64,
    pub jetOffsetY: f64,
    pub jetOffsetZ: f64,
    pub jetRadius: f64,
    pub jetLength: f64,
    pub jetCount: Option<i32>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionBlueprintWheels {
    pub r#type: String,
    pub physicsPresetId: String,
    pub physics: UnitUnitLocomotionBlueprintPhysics,
    pub environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy,
    pub config: WheelConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionBlueprintTreads {
    pub r#type: String,
    pub physicsPresetId: String,
    pub physics: UnitUnitLocomotionBlueprintPhysics,
    pub environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy,
    pub config: TreadConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionBlueprintAmphibiousTreads {
    pub r#type: String,
    pub physicsPresetId: String,
    pub physics: UnitUnitLocomotionBlueprintPhysics,
    pub environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy,
    pub config: TreadConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionBlueprintLegs {
    pub r#type: String,
    pub physicsPresetId: String,
    pub physics: UnitUnitLocomotionBlueprintPhysics,
    pub environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy,
    pub config: LegConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionBlueprintFlippers {
    pub r#type: String,
    pub physicsPresetId: String,
    pub physics: UnitUnitLocomotionBlueprintPhysics,
    pub environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy,
    pub config: FlipperConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionBlueprintHover {
    pub r#type: String,
    pub physicsPresetId: String,
    pub physics: UnitUnitLocomotionBlueprintPhysics,
    pub environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy,
    pub config: HoverConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionBlueprintFlying {
    pub r#type: String,
    pub physicsPresetId: String,
    pub physics: UnitUnitLocomotionBlueprintPhysics,
    pub environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy,
    pub config: FlyingConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionBlueprintSubmarine {
    pub r#type: String,
    pub physicsPresetId: String,
    pub physics: UnitUnitLocomotionBlueprintPhysics,
    pub environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy,
    pub config: SwimConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionBlueprintDive {
    pub r#type: String,
    pub physicsPresetId: String,
    pub physics: UnitUnitLocomotionBlueprintPhysics,
    pub environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy,
    pub config: FlyingConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UnitLocomotionBlueprint {
    UnitLocomotionBlueprintWheels(UnitLocomotionBlueprintWheels),
    UnitLocomotionBlueprintTreads(UnitLocomotionBlueprintTreads),
    UnitLocomotionBlueprintAmphibiousTreads(UnitLocomotionBlueprintAmphibiousTreads),
    UnitLocomotionBlueprintLegs(UnitLocomotionBlueprintLegs),
    UnitLocomotionBlueprintFlippers(UnitLocomotionBlueprintFlippers),
    UnitLocomotionBlueprintHover(UnitLocomotionBlueprintHover),
    UnitLocomotionBlueprintFlying(UnitLocomotionBlueprintFlying),
    UnitLocomotionBlueprintSubmarine(UnitLocomotionBlueprintSubmarine),
    UnitLocomotionBlueprintDive(UnitLocomotionBlueprintDive),
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapePartCircle {
    pub kind: String,
    pub offsetForward: f64,
    pub offsetLateral: Option<f64>,
    pub radiusFrac: f64,
    pub yFrac: Option<f64>,
    pub centerYFrac: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapePartOval {
    pub kind: String,
    pub offsetForward: f64,
    pub offsetLateral: Option<f64>,
    pub xFrac: f64,
    pub yFrac: f64,
    pub zFrac: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapePartCylinder {
    pub kind: String,
    pub offsetForward: f64,
    pub offsetLateral: Option<f64>,
    pub lengthFrac: f64,
    pub radiusFrac: f64,
    pub centerYFrac: Option<f64>,
    pub pitchRad: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapePartCone {
    pub kind: String,
    pub offsetForward: f64,
    pub offsetLateral: Option<f64>,
    pub lengthFrac: f64,
    pub radiusFrac: f64,
    pub centerYFrac: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UnitBodyShapePart {
    UnitBodyShapePartCircle(UnitBodyShapePartCircle),
    UnitBodyShapePartOval(UnitBodyShapePartOval),
    UnitBodyShapePartCylinder(UnitBodyShapePartCylinder),
    UnitBodyShapePartCone(UnitBodyShapePartCone),
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapePolygon {
    pub kind: String,
    pub sides: i32,
    pub radiusFrac: f64,
    pub heightFrac: f64,
    pub rotation: f64,
    pub bevelEnabled: Option<bool>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapeRect {
    pub kind: String,
    pub lengthFrac: f64,
    pub widthFrac: f64,
    pub heightFrac: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapeRhombus {
    pub kind: String,
    pub lengthFrac: f64,
    pub widthFrac: f64,
    pub heightFrac: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapeCircle {
    pub kind: String,
    pub radiusFrac: f64,
    pub yFrac: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapeOval {
    pub kind: String,
    pub xFrac: f64,
    pub yFrac: f64,
    pub zFrac: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapeComposite {
    pub kind: String,
    pub parts: Vec<UnitBodyShapePart>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UnitBodyShape {
    UnitBodyShapePolygon(UnitBodyShapePolygon),
    UnitBodyShapeRect(UnitBodyShapeRect),
    UnitBodyShapeRhombus(UnitBodyShapeRhombus),
    UnitBodyShapeCircle(UnitBodyShapeCircle),
    UnitBodyShapeOval(UnitBodyShapeOval),
    UnitBodyShapeComposite(UnitBodyShapeComposite),
}

#[derive(Clone, Debug, PartialEq)]
pub struct EntityHudBlueprint {
    pub barsOffsetAboveTop: f64,
}

pub type UnitRadiusConfig = EntityRadiusConfig;

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBuilderConfig {
    pub buildRange: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitDgunConfig {
    pub turretBlueprintId: String,
    pub energyCost: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitSupportSurfaceNone {
    pub kind: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitSupportSurfaceDiscTop {
    pub kind: String,
    pub topZ: f64,
    pub radius: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UnitSupportSurface {
    UnitSupportSurfaceNone(UnitSupportSurfaceNone),
    UnitSupportSurfaceDiscTop(UnitSupportSurfaceDiscTop),
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBlueprint {
    pub unitBlueprintId: String,
    pub name: String,
    pub shortName: String,
    pub base: EntityBaseLedger,
    pub hp: f64,
    pub radius: UnitRadiusConfig,
    pub supportSurface: UnitSupportSurface,
    pub fullVisionRadius: f64,
    pub sensors: SensorCapabilityConfig,
    pub mass: f64,
    pub cost: BlueprintJsonValue,
    pub turrets: Vec<TurretMount>,
    pub bodyShape: Option<UnitBodyShape>,
    pub hud: EntityHudBlueprint,
    pub legAttachHeightFrac: Option<f64>,
    pub unitLocomotion: UnitLocomotionBlueprint,
    pub suspension: Option<BlueprintJsonValue>,
    pub builder: Option<UnitBuilderConfig>,
    pub dgun: Option<UnitDgunConfig>,
    pub deathSound: Option<BlueprintJsonValue>,
    pub includeLockOnLevel0FriendsAndEnemies: Vec<TurretLockOnRelationshipInclusion>,
    pub includeLockOnLevel0Entities: Vec<TurretLockOnEntityFamilyInclusion>,
    pub includeLockOnLevel1Buildings: Vec<String>,
    pub includeLockOnLevel1Towers: Vec<String>,
    pub includeLockOnLevel1Units: Vec<String>,
    pub includeLockOnLevel1Turrets: Vec<String>,
    pub includeLockOnLevel1Shots: Vec<String>,
    pub lockOnRequiresTargetLockedOntoSelf: LockOnRequiresTargetLockedOntoSelf,
    pub preventLockOnIfMyTeamIsAboveMe: Option<bool>,
    pub supportPointOffsetZ: f64,
}

pub type RayBlueprintId = String;

pub type ShieldBlueprintId = String;

#[derive(Clone, Debug, PartialEq)]
pub enum RayType {
    Beam,
    Laser,
}

#[derive(Clone, Debug, PartialEq)]
pub enum EmissionKind {
    Shot,
    Ray,
    Shield,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BeamRayBlueprint {
    pub r#type: String,
    pub dps: f64,
    pub force: f64,
    pub recoil: f64,
    pub radius: f64,
    pub width: f64,
    pub damageSphere: ShotCollision,
    pub gravityForceMultiplier: f64,
    pub continuousSound: BeamContinuousSoundConfig,
    pub hitSound: Option<BlueprintJsonValue>,
    pub rayBlueprintId: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BeamContinuousSoundConfig {
    pub harmonicSeriesIndex: i32,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LaserRayBlueprint {
    pub r#type: String,
    pub dps: f64,
    pub force: f64,
    pub recoil: f64,
    pub radius: f64,
    pub width: f64,
    pub damageSphere: ShotCollision,
    pub duration: f64,
    pub gravityForceMultiplier: f64,
    pub hitSound: Option<BlueprintJsonValue>,
    pub rayBlueprintId: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldBlueprint {
    pub r#type: String,
    pub materialId: String,
    pub angle: f64,
    pub transitionTime: f64,
    pub reflection: ShieldReflectionPolicy,
    pub barrier: Option<ShieldBarrierRatioConfig>,
    pub hitSound: Option<BlueprintJsonValue>,
    pub shieldBlueprintId: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RayBlueprint {
    BeamRayBlueprint(BeamRayBlueprint),
    LaserRayBlueprint(LaserRayBlueprint),
}

#[derive(Clone, Debug, PartialEq)]
pub struct BeamRay {
    pub r#type: String,
    pub dps: f64,
    pub force: f64,
    pub recoil: f64,
    pub radius: f64,
    pub width: f64,
    pub damageSphere: ShotCollision,
    pub gravityForceMultiplier: f64,
    pub rayBlueprintId: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LaserRay {
    pub r#type: String,
    pub dps: f64,
    pub force: f64,
    pub recoil: f64,
    pub radius: f64,
    pub width: f64,
    pub damageSphere: ShotCollision,
    pub duration: f64,
    pub gravityForceMultiplier: f64,
    pub rayBlueprintId: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RayConfig {
    BeamRay(BeamRay),
    LaserRay(LaserRay),
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldConfig {
    pub r#type: String,
    pub material: ShieldMaterialBlueprint,
    pub angle: f64,
    pub transitionTime: f64,
    pub reflection: ShieldReflectionPolicy,
    pub barrier: Option<ShieldBarrierConfig>,
    pub shieldBlueprintId: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum EmissionConfig {
    ProjectileShot(ProjectileShot),
    BeamRay(BeamRay),
    LaserRay(LaserRay),
    ShieldConfig(ShieldConfig),
}
