// Generated by scripts/generateBlueprintSchemaTypes.mjs from src/game/sim/blueprints/blueprintSchema.json.
// Do not edit this file directly.
#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use std::collections::BTreeMap;

#[derive(Clone, Debug, PartialEq)]
pub enum BlueprintJsonValue {
    Null,
    Bool(bool),
    Number(f64),
    String(String),
    Array(Vec<BlueprintJsonValue>),
    Object(BTreeMap<String, BlueprintJsonValue>),
}

pub type UnitBlueprintId = String;

pub type StructureBlueprintId = String;

pub type TurretBlueprintId = String;

pub type ShotBlueprintId = String;

pub type ShieldMaterialId = String;

pub type SoundEntry = BlueprintJsonValue;

pub type BarrelShape = BlueprintJsonValue;

pub type TurretRangeOverrides = BlueprintJsonValue;

#[derive(Clone, Debug, PartialEq)]
pub enum TurretRangeVolume {
    TurretRangeCylinderNormal,
    TurretRangeBottomUnbounded,
    TurretRangeTopWaterAndBottomUnbounded,
    TurretRangeTopAndBottomUnbounded,
    TurretRangeSphere,
}

pub type WorkEmitterSpec = BlueprintJsonValue;

pub type ResourceCost = BlueprintJsonValue;

pub type UnitSuspensionConfig = BlueprintJsonValue;

pub type EntityId = i32;

pub type PlayerId = i32;

#[derive(Clone, Debug, PartialEq)]
pub struct SensorMediumTargetRadii {
    pub aboveWater: f64,
    pub underwater: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SensorMediumRadiusMatrix {
    pub aboveWater: SensorMediumTargetRadii,
    pub underwater: SensorMediumTargetRadii,
}

#[derive(Clone, Debug, PartialEq)]
pub struct EmissionMediumTargetRoutes {
    pub aboveWater: bool,
    pub underwater: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub struct EmissionMediumTrajectoryMatrix {
    pub aboveWater: EmissionMediumTargetRoutes,
    pub underwater: EmissionMediumTargetRoutes,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SensorCapabilityConfig {
    pub fullSight: SensorMediumRadiusMatrix,
    pub contactSight: SensorMediumRadiusMatrix,
    pub detectorRadius: f64,
    pub radarJamRadius: f64,
    pub sonarJamRadius: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretEngagementEnvelope {
    pub range: f64,
    pub rangeVolume: TurretRangeVolume,
    pub rangeMultiplierOverrides: BlueprintJsonValue,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretObservationEnvelope {
    pub rangeVolume: TurretRangeVolume,
    pub sensors: SensorCapabilityConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub enum TurretEffectRangeSource {
    Engagement,
    Explicit,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretEffectEnvelope {
    pub rangeSource: TurretEffectRangeSource,
    pub range: Option<f64>,
    pub rangeVolume: Option<TurretRangeVolume>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum TurretIntelRequirement {
    ContactSight,
    FullSight,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretTargetingConfig {
    pub engagement: TurretEngagementEnvelope,
    pub observation: TurretObservationEnvelope,
    pub effect: TurretEffectEnvelope,
    pub requiredIntel: TurretIntelRequirement,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ProjectileShotKind {
    Plasma,
    Rocket,
    Missile,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShotLocomotionMotionModel {
    Ballistic,
    ThrustGuided,
    ConstantSpeedGuided,
    TerrainFollowing,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShotLocomotionTerminalOutcome {
    Detonate,
    Despawn,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShotLocomotionTransitionOutcome {
    Continue,
    ContinueBallistic,
    Detonate,
    Despawn,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotLocomotionMediumPhysics {
    pub operational: bool,
    pub propulsionForce: f64,
    pub guidanceThrust: f64,
    pub turnRate: f64,
    pub velocityFrictionPer60HzFrame: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotLocomotionGroundPhysics {
    pub mode: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotLocomotionMedia {
    pub air: ShotLocomotionMediumPhysics,
    pub water: ShotLocomotionMediumPhysics,
    pub ground: ShotLocomotionGroundPhysics,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotLocomotionTransitions {
    pub enterWater: ShotLocomotionTransitionOutcome,
    pub exitWater: ShotLocomotionTransitionOutcome,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotLocomotionTerminalPolicy {
    pub entityImpact: ShotLocomotionTerminalOutcome,
    pub groundContact: ShotLocomotionTerminalOutcome,
    pub expiry: ShotLocomotionTerminalOutcome,
    pub destroyed: ShotLocomotionTerminalOutcome,
    pub reflectorImpact: ShotLocomotionTerminalOutcome,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotLocomotion {
    pub presetId: String,
    pub motionModel: ShotLocomotionMotionModel,
    pub maxLifespanMs: Option<f64>,
    pub gravityForceMultiplier: f64,
    pub guidanceDelayMs: f64,
    pub guidanceRampMs: f64,
    pub media: ShotLocomotionMedia,
    pub transitions: ShotLocomotionTransitions,
    pub terminal: ShotLocomotionTerminalPolicy,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShieldSurfaceResponse {
    Reflect,
    Absorb,
    PassThrough,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShieldReflectionMode {
    OutsideIn,
    InsideOut,
    Both,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShieldReflectionDirection {
    ReflectNone,
    ReflectOutside,
    ReflectInside,
    ReflectBoth,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShieldReflectionEntity {
    Plasma,
    Rocket,
    Missile,
    Beam,
    Laser,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldReflectionEntityDirections {
    pub plasma: Option<ShieldReflectionDirection>,
    pub rocket: Option<ShieldReflectionDirection>,
    pub missile: Option<ShieldReflectionDirection>,
    pub beam: Option<ShieldReflectionDirection>,
    pub laser: Option<ShieldReflectionDirection>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldReflectionPolicy {
    pub entities: ShieldReflectionEntityDirections,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShieldBarrierShape {
    Sphere,
    InfiniteVerticalCylinder,
    AimedCylinder,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldBarrierRatioConfig {
    pub shape: ShieldBarrierShape,
    pub outerRatio: Option<f64>,
    pub rimWidth: Option<f64>,
    pub originOffsetRadiusRatio: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretSubmunitionEmitterConfig {
    pub shotBlueprintId: String,
    pub launchForce: f64,
    pub cooldown: TurretCooldownConfig,
    pub spread: TurretSpreadConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldMaterialVisualConfig {
    pub color: f64,
    pub alpha: f64,
    pub particleAlpha: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldMaterialReflectionConfig {
    pub mode: ShieldReflectionMode,
    pub reflectivity: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldMaterialProjectileResponseConfig {
    pub plasma: ShieldSurfaceResponse,
    pub rocket: ShieldSurfaceResponse,
    pub beam: ShieldSurfaceResponse,
    pub laser: ShieldSurfaceResponse,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldMaterialHitReactionConfig {
    pub impactEvent: String,
    pub sound: Option<BlueprintJsonValue>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldMaterialBlueprint {
    pub materialId: String,
    pub reflection: ShieldMaterialReflectionConfig,
    pub projectileResponse: ShieldMaterialProjectileResponseConfig,
    pub hitReaction: ShieldMaterialHitReactionConfig,
    pub visual: ShieldMaterialVisualConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotCollision {
    pub radius: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotExplosion {
    pub radius: f64,
    pub damage: f64,
    pub force: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SubmunitionSpec {
    pub shotBlueprintId: String,
    pub count: i32,
    pub randomSpreadSpeedHorizontal: f64,
    pub randomSpreadSpeedVertical: f64,
    pub reflectedVelocityDamper: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SmokeTrailSpec {
    pub useId: Option<String>,
    pub maxPoolSize: Option<f64>,
    pub capPolicy: String,
    pub emitFramesSkip: Option<f64>,
    pub exhaustSpeed: Option<f64>,
    pub startRadius: Option<f64>,
    pub endRadiusMultiplier: Option<f64>,
    pub fadeInMs: Option<f64>,
    pub fadeOutMs: Option<f64>,
    pub maxAlpha: Option<f64>,
    pub color: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotTurningBlueprint {
    pub turnRate: f64,
    pub guidanceDelayMs: f64,
    pub guidanceRampMs: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ProjectileShotBlueprint {
    pub r#type: ProjectileShotKind,
    pub shotBlueprintId: String,
    pub name: String,
    pub base: EntityBaseLedger,
    pub mass: f64,
    pub health: f64,
    pub radius: EntityRadiusConfig,
    pub shotLocomotionPresetId: String,
    pub maxLifespanMs: Option<f64>,
    pub turning: Option<ShotTurningBlueprint>,
    pub mediumTrajectory: EmissionMediumTrajectoryMatrix,
    pub hitSound: Option<BlueprintJsonValue>,
    pub submunitions: Option<SubmunitionSpec>,
    pub smokeTrail: Option<SmokeTrailSpec>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShotBlueprint {
    ProjectileShotBlueprint(ProjectileShotBlueprint),
}

#[derive(Clone, Debug, PartialEq)]
pub enum ProjectileTailShape {
    Cone,
    Cylinder,
    None,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldBarrierConfig {
    pub shape: ShieldBarrierShape,
    pub innerRange: f64,
    pub outerRange: f64,
    pub originOffsetZ: f64,
    pub color: f64,
    pub alpha: f64,
    pub particleAlpha: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ProjectileShot {
    pub r#type: ProjectileShotKind,
    pub shotBlueprintId: String,
    pub base: EntityBaseLedger,
    pub mass: f64,
    pub health: f64,
    pub launchForce: f64,
    pub radius: EntityRadiusConfig,
    pub explosion: Option<ShotExplosion>,
    pub shotLocomotion: ShotLocomotion,
    pub mediumTrajectory: EmissionMediumTrajectoryMatrix,
    pub trailLength: Option<f64>,
    pub submunitions: Option<SubmunitionSpec>,
    pub smokeTrail: Option<SmokeTrailSpec>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ActiveProjectileShot {
    ProjectileShot(ProjectileShot),
    BeamRay(BeamRay),
    LaserRay(LaserRay),
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShotConfig {
    ProjectileShot(ProjectileShot),
}

#[derive(Clone, Debug, PartialEq)]
pub enum ProjectileType {
    Projectile,
    Beam,
    Laser,
}

#[derive(Clone, Debug, PartialEq)]
pub enum BeamReflectorKind {
    Shield,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BeamPoint {
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub vx: f64,
    pub vy: f64,
    pub vz: f64,
    pub reflectorEntityId: Option<i32>,
    pub reflectorKind: Option<BeamReflectorKind>,
    pub reflectorPlayerId: Option<i32>,
    pub normalX: Option<f64>,
    pub normalY: Option<f64>,
    pub normalZ: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ShotRuntimeType {
    Plasma,
    Rocket,
    Missile,
    Beam,
    Laser,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotRuntimeProfile {
    pub shotBlueprintId: String,
    pub r#type: ShotRuntimeType,
    pub projectileType: ProjectileType,
    pub isProjectile: bool,
    pub isLine: bool,
    pub isRocketLike: bool,
    pub radius: EntityRadiusConfig,
    pub deathExplosionRadius: f64,
    pub maxLifespan: f64,
    pub detonateOnExpiry: bool,
    pub hasExplosion: bool,
    pub hasSubmunitions: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotVisualProfile {
    pub projectileTailShape: ProjectileTailShape,
    pub projectileTailLengthMult: f64,
    pub projectileTailRadiusMult: f64,
    pub projectileFinSizeMult: f64,
    pub smokeTrail: Option<SmokeTrailSpec>,
    pub burnMarkWidth: f64,
    pub lineRadius: f64,
    pub lineDamageSphereRadius: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShotProfile {
    pub runtime: ShotRuntimeProfile,
    pub visual: ShotVisualProfile,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldPanel {
    pub offsetX: f64,
    pub offsetY: f64,
    pub angle: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct EntityRadiusConfig {
    pub other: f64,
    pub hitbox: f64,
    pub collision: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct EntityDeathExplosion {
    pub radius: f64,
    pub force: f64,
    pub damage: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct EntitySignature {
    pub radarStealth: bool,
    pub sonarStealth: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub struct EntityBaseLedger {
    pub cost: BlueprintJsonValue,
    pub mass: f64,
    pub health: f64,
    pub deathExplosion: EntityDeathExplosion,
    pub radius: EntityRadiusConfig,
    pub signature: EntitySignature,
}

#[derive(Clone, Debug, PartialEq)]
pub enum TurretAimAngleType {
    RayDirect,
    RayBisectTurretAndBody,
    BallisticArcLow,
    BallisticArcLowOnlyUnder,
    BallisticArcHigh,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretAimStyle {
    pub angleType: TurretAimAngleType,
}

#[derive(Clone, Debug, PartialEq)]
pub enum TurretLockOnRelationshipInclusion {
    FriendlyEntities,
    EnemyEntities,
}

#[derive(Clone, Debug, PartialEq)]
pub enum TurretLockOnEntityFamilyInclusion {
    Buildings,
    Units,
    Turrets,
    Shots,
}

#[derive(Clone, Debug, PartialEq)]
pub enum LockOnRequiresTargetLockedOntoSelf {
    Ignore,
    Require,
    PreferReacquire,
    PreferHold,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LockOnInclusionObject {
    pub includeLockOnLevel0FriendsAndEnemies: Vec<TurretLockOnRelationshipInclusion>,
    pub includeLockOnLevel0Entities: Vec<TurretLockOnEntityFamilyInclusion>,
    pub includeLockOnLevel1Buildings: Vec<String>,
    pub includeLockOnLevel1Units: Vec<String>,
    pub includeLockOnLevel1Turrets: Vec<String>,
    pub includeLockOnLevel1Shots: Vec<String>,
    pub lockOnRequiresTargetLockedOntoSelf: LockOnRequiresTargetLockedOntoSelf,
}

#[derive(Clone, Debug, PartialEq)]
pub enum TurretEmitterKind {
    Attack,
    Spawn,
    ResourcePylon,
    Sensor,
}

#[derive(Clone, Debug, PartialEq)]
pub enum TurretMountControlMode {
    HostPreferred,
    HostOnly,
    Autonomous,
    Manual,
    Slaved,
}

#[derive(Clone, Debug, PartialEq)]
pub enum SpawnProducedKind {
    Buildings,
    Units,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ResourcePylonResource {
    Metal,
    Energy,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ResourcePylonRole {
    Construction,
    Extraction,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SpawnTurretConfig {
    pub producedKind: SpawnProducedKind,
    pub producedBlueprintId: Option<String>,
    pub producesNanoframe: bool,
    pub cooldownMs: f64,
    pub launchForce: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ResourcePylonConfig {
    pub resource: ResourcePylonResource,
    pub role: ResourcePylonRole,
    pub radius: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretSpreadConfig {
    pub angle: f64,
    pub pelletCount: i32,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretBurstConfig {
    pub count: i32,
    pub delay: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretCooldownConfig {
    pub duration: f64,
    pub durationRandomness: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretAudioConfig {
    pub fireSound: BlueprintJsonValue,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretAngularActuatorAxis {
    pub maxSpeed: f64,
    pub maxAcceleration: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretAngularActuator {
    pub yaw: TurretAngularActuatorAxis,
    pub pitch: TurretAngularActuatorAxis,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretBlueprint {
    pub turretBlueprintId: String,
    pub name: String,
    pub kind: TurretEmitterKind,
    pub targeting: TurretTargetingConfig,
    pub cooldown: Option<TurretCooldownConfig>,
    pub color: f64,
    pub angularActuator: Option<TurretAngularActuator>,
    pub emissionLaneCount: i32,
    pub eventsSmooth: bool,
    pub launchForce: f64,
    pub addTurretVelocityToEmissionLaunch: bool,
    pub passive: bool,
    pub requiresNonObstructedLineOfSight: bool,
    pub spread: Option<TurretSpreadConfig>,
    pub submunitions: Option<TurretSubmunitionEmitterConfig>,
    pub burst: Option<TurretBurstConfig>,
    pub audio: Option<TurretAudioConfig>,
    pub aimMotionSnapshotVisible: bool,
    pub aimStyle: TurretAimStyle,
    pub verticalLauncher: bool,
    pub idlePitch: f64,
    pub groundAimFraction: Option<f64>,
    pub spawn: Option<SpawnTurretConfig>,
    pub resourcePylon: Option<ResourcePylonConfig>,
    pub includeLockOnLevel0FriendsAndEnemies: Vec<TurretLockOnRelationshipInclusion>,
    pub includeLockOnLevel0Entities: Vec<TurretLockOnEntityFamilyInclusion>,
    pub includeLockOnLevel1Buildings: Vec<String>,
    pub includeLockOnLevel1Units: Vec<String>,
    pub includeLockOnLevel1Turrets: Vec<String>,
    pub includeLockOnLevel1Shots: Vec<String>,
    pub lockOnRequiresTargetLockedOntoSelf: LockOnRequiresTargetLockedOntoSelf,
    pub emissionKind: Option<EmissionKind>,
    pub emissionBlueprintId: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretPresentation {
    pub headRadius: Option<f64>,
    pub headOnly: bool,
    pub barrel: Option<BlueprintJsonValue>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct MountOffset {
    pub x: f64,
    pub y: f64,
    pub z: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitTurretMountZResolver {
    pub kind: String,
    pub bodyTopZFrac: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BotArmTurretHostAttachment {
    pub kind: String,
    pub arm: String,
    pub socketOffset: MountOffset,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BotPieceTurretHostAttachment {
    pub kind: String,
    pub piece: String,
    pub socketOffset: MountOffset,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UnitTurretHostAttachment {
    BotArmTurretHostAttachment(BotArmTurretHostAttachment),
    BotPieceTurretHostAttachment(BotPieceTurretHostAttachment),
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretEmissionSocket {
    pub offset: MountOffset,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretYawTraverse {
    pub continuous: bool,
    pub minAngle: f64,
    pub maxAngle: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretPitchTraverse {
    pub minAngle: f64,
    pub maxAngle: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum TurretHostAssistPolicy {
    None,
    RequestYaw,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretStationArticulation {
    pub yaw: TurretYawTraverse,
    pub pitch: TurretPitchTraverse,
    pub restYaw: f64,
    pub restPitch: f64,
    pub restoreDelayMs: f64,
    pub hostAssist: TurretHostAssistPolicy,
    pub claimGroup: Option<String>,
    pub claimPriority: i32,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TurretMount {
    pub mountId: String,
    pub turretBlueprintId: String,
    pub sensorTurretBlueprintId: Option<String>,
    pub mount: MountOffset,
    pub presentation: Option<TurretPresentation>,
    pub shieldPanels: Option<Vec<ShieldPanel>>,
    pub controlMode: TurretMountControlMode,
    pub slavedToMountId: Option<String>,
    pub requiredEngagedForFightStop: bool,
    pub zResolver: Option<UnitTurretMountZResolver>,
    pub hostAttachment: Option<UnitTurretHostAttachment>,
    pub emissionSockets: Option<Vec<TurretEmissionSocket>>,
    pub articulation: Option<TurretStationArticulation>,
    pub producedBlueprintId: Option<String>,
    pub allowedBuildBlueprintIds: Option<Vec<String>>,
    pub productionHoldAnchor: Option<String>,
    pub constructionRate: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BuildingTurretMount {
    pub mountId: String,
    pub turretBlueprintId: String,
    pub sensorTurretBlueprintId: Option<String>,
    pub mount: MountOffset,
    pub presentation: Option<TurretPresentation>,
    pub shieldPanels: Option<Vec<ShieldPanel>>,
    pub controlMode: TurretMountControlMode,
    pub slavedToMountId: Option<String>,
    pub articulation: Option<TurretStationArticulation>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct RoverConfig {
    pub mounts: Vec<LocomotionMount>,
    pub treadWidth: f64,
    pub wheelRadius: f64,
    pub rotationSpeed: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TankConfig {
    pub mounts: Vec<LocomotionMount>,
    pub treadLength: f64,
    pub treadWidth: f64,
    pub wheelRadius: f64,
    pub rotationSpeed: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LegSegment {
    pub lengthUnitRadiusRatio: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LegSegments {
    pub upper: LegSegment,
    pub lower: LegSegment,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LegFootSphere {
    pub originExtensionRatio: f64,
    pub radiusLegLengthRatio: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LegLayoutEntry {
    pub attachmentPoint: LocomotionMount,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LegChoppingSphere {
    pub radiusLegLengthRatio: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LegSnapRay {
    pub originBoundarySpanRatio: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct CrawlerConfig {
    pub radius: f64,
    pub kneeRadius: f64,
    pub hasFeet: bool,
    pub lerpDuration: f64,
    pub segments: LegSegments,
    pub footSphere: LegFootSphere,
    pub choppingSphere: LegChoppingSphere,
    pub snapRay: LegSnapRay,
    pub leftSide: Vec<LegLayoutEntry>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BotArmSegments {
    pub upper: LegSegment,
    pub lower: LegSegment,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BotArms {
    pub shoulder: LocomotionMount,
    pub radius: f64,
    pub segments: BotArmSegments,
    pub handRadiusRatio: f64,
    pub restSwingDeg: f64,
    pub walkSwingDeg: f64,
    pub outwardDeg: f64,
    pub elbowBendDirection: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BotLegs {
    pub hip: LocomotionMount,
    pub radius: f64,
    pub segments: BotArmSegments,
    pub footLengthRatio: f64,
    pub footWidthRatio: f64,
    pub strideLengthRatio: f64,
    pub strideLiftRatio: f64,
    pub standHeightRatio: f64,
    pub stanceForwardUnitRadiusRatio: f64,
    pub stanceOutwardUnitRadiusRatio: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BotConfig {
    pub legs: BotLegs,
    pub arms: BotArms,
    pub upperArms: Option<BotArms>,
    pub upperBodyActuator: TurretAngularActuatorAxis,
    pub upperBodyRestoreDelayMs: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct AmphibianConfig {
    pub mounts: Vec<FlipperMount>,
    pub rootChordFrac: f64,
    pub tipChordFrac: f64,
    pub thicknessFrac: f64,
    pub groundDownAngleDeg: f64,
    pub groundSweepAngleDeg: f64,
    pub waterStrokeAngleDeg: f64,
    pub cycleDistanceFrac: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SubmarineConfig {
    pub pectorals: Vec<SubmarinePectoralMount>,
    pub rearFan: SubmarineRearFan,
    pub pectoralSpanFrac: f64,
    pub pectoralRootChordFrac: f64,
    pub pectoralTipChordFrac: f64,
    pub thicknessFrac: f64,
    pub strokeAngleDeg: f64,
    pub cycleDistanceFrac: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LocomotionAirLiftPhysics {
    pub surfaceFollowingInverseForceFromGround: f64,
    pub surfaceFollowingInverseForceFromWater: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LocomotionWaterLiftPhysics {
    pub surfaceFollowingInverseForceFromGround: f64,
    pub surfaceFollowingProportionalForceFromWater: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LocomotionAirFluidBodyPhysics {
    pub maxPropulsiveForce: f64,
    pub lift: LocomotionAirLiftPhysics,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LocomotionWaterFluidBodyPhysics {
    pub maxPropulsiveForce: f64,
    pub lift: LocomotionWaterLiftPhysics,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LocomotionGroundBodyPhysics {
    pub maxPropulsiveForce: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitUnitLocomotionBlueprintPhysics {
    pub ground: LocomotionGroundBodyPhysics,
    pub air: LocomotionAirFluidBodyPhysics,
    pub water: LocomotionWaterFluidBodyPhysics,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionEnvironmentalHazardPolicy {
    pub waterDamagePerSecond: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct DroneConfig {
    pub mounts: Vec<DroneFanMount>,
    pub fanSpinRadPerSec: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct AirframeConfig {
    pub wing: Option<AirframeSurface>,
    pub tailWing: Option<AirframeSurface>,
    pub jets: Vec<AirframeJetMount>,
    pub jetRadius: f64,
    pub jetLength: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionBlueprintRover {
    pub r#type: String,
    pub physicsPresetId: String,
    pub physics: UnitUnitLocomotionBlueprintPhysics,
    pub environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy,
    pub config: RoverConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionBlueprintTank {
    pub r#type: String,
    pub physicsPresetId: String,
    pub physics: UnitUnitLocomotionBlueprintPhysics,
    pub environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy,
    pub config: TankConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionBlueprintAmphibiousTank {
    pub r#type: String,
    pub physicsPresetId: String,
    pub physics: UnitUnitLocomotionBlueprintPhysics,
    pub environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy,
    pub config: TankConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionBlueprintCrawler {
    pub r#type: String,
    pub physicsPresetId: String,
    pub physics: UnitUnitLocomotionBlueprintPhysics,
    pub environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy,
    pub config: CrawlerConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionBlueprintBot {
    pub r#type: String,
    pub physicsPresetId: String,
    pub physics: UnitUnitLocomotionBlueprintPhysics,
    pub environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy,
    pub config: BotConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionBlueprintAmphibian {
    pub r#type: String,
    pub physicsPresetId: String,
    pub physics: UnitUnitLocomotionBlueprintPhysics,
    pub environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy,
    pub config: AmphibianConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionBlueprintDrone {
    pub r#type: String,
    pub physicsPresetId: String,
    pub physics: UnitUnitLocomotionBlueprintPhysics,
    pub environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy,
    pub config: DroneConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionBlueprintPlane {
    pub r#type: String,
    pub physicsPresetId: String,
    pub physics: UnitUnitLocomotionBlueprintPhysics,
    pub environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy,
    pub config: AirframeConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionBlueprintSubmarine {
    pub r#type: String,
    pub physicsPresetId: String,
    pub physics: UnitUnitLocomotionBlueprintPhysics,
    pub environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy,
    pub config: SubmarineConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitLocomotionBlueprintAerosub {
    pub r#type: String,
    pub physicsPresetId: String,
    pub physics: UnitUnitLocomotionBlueprintPhysics,
    pub environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy,
    pub config: AirframeConfig,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UnitLocomotionBlueprint {
    UnitLocomotionBlueprintRover(UnitLocomotionBlueprintRover),
    UnitLocomotionBlueprintTank(UnitLocomotionBlueprintTank),
    UnitLocomotionBlueprintAmphibiousTank(UnitLocomotionBlueprintAmphibiousTank),
    UnitLocomotionBlueprintCrawler(UnitLocomotionBlueprintCrawler),
    UnitLocomotionBlueprintBot(UnitLocomotionBlueprintBot),
    UnitLocomotionBlueprintAmphibian(UnitLocomotionBlueprintAmphibian),
    UnitLocomotionBlueprintDrone(UnitLocomotionBlueprintDrone),
    UnitLocomotionBlueprintPlane(UnitLocomotionBlueprintPlane),
    UnitLocomotionBlueprintSubmarine(UnitLocomotionBlueprintSubmarine),
    UnitLocomotionBlueprintAerosub(UnitLocomotionBlueprintAerosub),
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapePartCircle {
    pub kind: String,
    pub offsetForward: f64,
    pub offsetLateral: Option<f64>,
    pub radiusFrac: f64,
    pub yFrac: Option<f64>,
    pub centerYFrac: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapePartOval {
    pub kind: String,
    pub offsetForward: f64,
    pub offsetLateral: Option<f64>,
    pub xFrac: f64,
    pub yFrac: f64,
    pub zFrac: f64,
    pub centerYFrac: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapePartBox {
    pub kind: String,
    pub offsetForward: f64,
    pub offsetLateral: Option<f64>,
    pub lengthFrac: f64,
    pub widthFrac: f64,
    pub heightFrac: f64,
    pub centerYFrac: Option<f64>,
    pub pitchRad: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapePartCylinder {
    pub kind: String,
    pub offsetForward: f64,
    pub offsetLateral: Option<f64>,
    pub lengthFrac: f64,
    pub radiusFrac: f64,
    pub centerYFrac: Option<f64>,
    pub pitchRad: Option<f64>,
    pub startYFrac: Option<f64>,
    pub endYFrac: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapePartCone {
    pub kind: String,
    pub offsetForward: f64,
    pub offsetLateral: Option<f64>,
    pub lengthFrac: f64,
    pub radiusFrac: f64,
    pub centerYFrac: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UnitBodyShapePart {
    UnitBodyShapePartCircle(UnitBodyShapePartCircle),
    UnitBodyShapePartOval(UnitBodyShapePartOval),
    UnitBodyShapePartCylinder(UnitBodyShapePartCylinder),
    UnitBodyShapePartCone(UnitBodyShapePartCone),
    UnitBodyShapePartBox(UnitBodyShapePartBox),
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapePolygon {
    pub kind: String,
    pub sides: i32,
    pub radiusFrac: f64,
    pub heightFrac: f64,
    pub rotation: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapeRect {
    pub kind: String,
    pub lengthFrac: f64,
    pub widthFrac: f64,
    pub heightFrac: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapeRhombus {
    pub kind: String,
    pub lengthFrac: f64,
    pub widthFrac: f64,
    pub heightFrac: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapeCircle {
    pub kind: String,
    pub radiusFrac: f64,
    pub yFrac: Option<f64>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapeOval {
    pub kind: String,
    pub xFrac: f64,
    pub yFrac: f64,
    pub zFrac: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBodyShapeComposite {
    pub kind: String,
    pub parts: Vec<UnitBodyShapePart>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TeamOrnamentFit {
    pub backX: f64,
    pub frontX: f64,
    pub backY: f64,
    pub frontY: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UnitBodyShape {
    UnitBodyShapePolygon(UnitBodyShapePolygon),
    UnitBodyShapeRect(UnitBodyShapeRect),
    UnitBodyShapeRhombus(UnitBodyShapeRhombus),
    UnitBodyShapeCircle(UnitBodyShapeCircle),
    UnitBodyShapeOval(UnitBodyShapeOval),
    UnitBodyShapeComposite(UnitBodyShapeComposite),
}

#[derive(Clone, Debug, PartialEq)]
pub struct EntityHudBlueprint {
    pub barsOffsetAboveTop: f64,
}

pub type UnitRadiusConfig = EntityRadiusConfig;

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBuilderConfig {
    pub buildRange: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitDgunConfig {
    pub turretBlueprintId: String,
    pub energyCost: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitSupportSurfaceNone {
    pub kind: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitSupportSurfaceDiscTop {
    pub kind: String,
    pub topZ: f64,
    pub radius: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UnitSupportSurface {
    UnitSupportSurfaceNone(UnitSupportSurfaceNone),
    UnitSupportSurfaceDiscTop(UnitSupportSurfaceDiscTop),
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnitBlueprint {
    pub unitBlueprintId: String,
    pub name: String,
    pub shortName: String,
    pub tinyName: String,
    pub base: EntityBaseLedger,
    pub hp: f64,
    pub radius: UnitRadiusConfig,
    pub supportSurface: UnitSupportSurface,
    pub mass: f64,
    pub cost: BlueprintJsonValue,
    pub turrets: Vec<TurretMount>,
    pub bodyShape: Option<UnitBodyShape>,
    pub teamOrnament: TeamOrnamentFit,
    pub hud: EntityHudBlueprint,
    pub unitLocomotion: UnitLocomotionBlueprint,
    pub suspension: Option<BlueprintJsonValue>,
    pub builder: Option<UnitBuilderConfig>,
    pub constructionRate: Option<f64>,
    pub allowedBuildBlueprintIds: Option<Vec<String>>,
    pub factoryProducedUnitBlueprintId: Option<String>,
    pub workEmitter: Option<BlueprintJsonValue>,
    pub dgun: Option<UnitDgunConfig>,
    pub deathSound: Option<BlueprintJsonValue>,
    pub includeLockOnLevel0FriendsAndEnemies: Vec<TurretLockOnRelationshipInclusion>,
    pub includeLockOnLevel0Entities: Vec<TurretLockOnEntityFamilyInclusion>,
    pub includeLockOnLevel1Buildings: Vec<String>,
    pub includeLockOnLevel1Units: Vec<String>,
    pub includeLockOnLevel1Turrets: Vec<String>,
    pub includeLockOnLevel1Shots: Vec<String>,
    pub lockOnRequiresTargetLockedOntoSelf: LockOnRequiresTargetLockedOntoSelf,
    pub preventLockOnIfMyTeamIsAboveMe: Option<bool>,
    pub supportPointOffsetZ: f64,
}

pub type RayBlueprintId = String;

pub type ShieldBlueprintId = String;

#[derive(Clone, Debug, PartialEq)]
pub enum RayType {
    Beam,
    Laser,
}

#[derive(Clone, Debug, PartialEq)]
pub enum EmissionKind {
    Shot,
    Ray,
    Shield,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BeamRayBlueprint {
    pub r#type: String,
    pub dps: f64,
    pub force: f64,
    pub recoil: f64,
    pub radius: f64,
    pub width: f64,
    pub damageSphere: ShotCollision,
    pub gravityForceMultiplier: f64,
    pub mediumTrajectory: EmissionMediumTrajectoryMatrix,
    pub continuousSound: BeamContinuousSoundConfig,
    pub hitSound: Option<BlueprintJsonValue>,
    pub rayBlueprintId: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct BeamContinuousSoundConfig {
    pub harmonicSeriesIndex: i32,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LaserRayBlueprint {
    pub r#type: String,
    pub dps: f64,
    pub force: f64,
    pub recoil: f64,
    pub radius: f64,
    pub width: f64,
    pub damageSphere: ShotCollision,
    pub duration: f64,
    pub gravityForceMultiplier: f64,
    pub mediumTrajectory: EmissionMediumTrajectoryMatrix,
    pub hitSound: Option<BlueprintJsonValue>,
    pub rayBlueprintId: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldBlueprint {
    pub r#type: String,
    pub materialId: String,
    pub angle: f64,
    pub transitionTime: f64,
    pub reflection: ShieldReflectionPolicy,
    pub barrier: Option<ShieldBarrierRatioConfig>,
    pub mediumTrajectory: EmissionMediumTrajectoryMatrix,
    pub hitSound: Option<BlueprintJsonValue>,
    pub shieldBlueprintId: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RayBlueprint {
    BeamRayBlueprint(BeamRayBlueprint),
    LaserRayBlueprint(LaserRayBlueprint),
}

#[derive(Clone, Debug, PartialEq)]
pub struct BeamRay {
    pub r#type: String,
    pub dps: f64,
    pub force: f64,
    pub recoil: f64,
    pub radius: f64,
    pub width: f64,
    pub damageSphere: ShotCollision,
    pub gravityForceMultiplier: f64,
    pub mediumTrajectory: EmissionMediumTrajectoryMatrix,
    pub rayBlueprintId: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LaserRay {
    pub r#type: String,
    pub dps: f64,
    pub force: f64,
    pub recoil: f64,
    pub radius: f64,
    pub width: f64,
    pub damageSphere: ShotCollision,
    pub duration: f64,
    pub gravityForceMultiplier: f64,
    pub mediumTrajectory: EmissionMediumTrajectoryMatrix,
    pub rayBlueprintId: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RayConfig {
    BeamRay(BeamRay),
    LaserRay(LaserRay),
}

#[derive(Clone, Debug, PartialEq)]
pub struct ShieldConfig {
    pub r#type: String,
    pub material: ShieldMaterialBlueprint,
    pub angle: f64,
    pub transitionTime: f64,
    pub reflection: ShieldReflectionPolicy,
    pub mediumTrajectory: EmissionMediumTrajectoryMatrix,
    pub barrier: Option<ShieldBarrierConfig>,
    pub shieldBlueprintId: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum EmissionConfig {
    ProjectileShot(ProjectileShot),
    BeamRay(BeamRay),
    LaserRay(LaserRay),
    ShieldConfig(ShieldConfig),
}

#[derive(Clone, Debug, PartialEq)]
pub struct LocomotionMount {
    pub xUnitRadiusRatio: f64,
    pub yUnitRadiusRatio: f64,
    pub zUnitRadiusRatio: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct FlipperMount {
    pub offset: LocomotionMount,
    pub lengthFrac: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct DroneFanMount {
    pub offset: LocomotionMount,
    pub radiusFrac: f64,
    pub ringTubeRadiusFrac: f64,
    pub outwardAngleDeg: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct AirframeSurface {
    pub offset: LocomotionMount,
    pub span: f64,
    pub chord: f64,
    pub thickness: f64,
    pub dihedralDeg: f64,
    pub sweepFrac: f64,
    pub mirrorX: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub struct AirframeJetMount {
    pub offset: LocomotionMount,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SubmarinePectoralMount {
    pub offset: LocomotionMount,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SubmarineRearFan {
    pub offset: LocomotionMount,
    pub radius: f64,
    pub ringTubeRadius: f64,
    pub spinRadPerSec: f64,
}
