// snapshot — extracted from lib.rs (pure code motion).

#[allow(unused_imports)]
use crate::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;

// ─────────────────────────────────────────────────────────────────
// Snapshot encoder scratch pools
//
// Every snapshot_encode_*_scratch buffer is a grow-on-demand Vec<elem>
// exported to JS as a raw pointer + an `ensure(count)` that grows it to
// count*stride. The ~24 uniform pools were byte-for-byte identical apart
// from name / element type / stride / initial capacity, so they are
// generated by this one macro (Single Source Of Truth / file-size
// discipline). wasm_bindgen exports the generated ptr/ensure functions by
// their concrete idents, so the JS bindings are unchanged.
// ─────────────────────────────────────────────────────────────────
macro_rules! snapshot_scratch_pool {
    (
        $struct:ident,
        $static:ident,
        $getter:ident,
        $ptr_fn:ident,
        $ensure_fn:ident,
        $elem:ty,
        $zero:expr,
        $stride_const:ident = $stride:expr,
        init $init_count:expr,
        ensure($ensure_param:ident)
    ) => {
        pub(crate) const $stride_const: usize = $stride;

        pub(crate) struct $struct {
            buf: Vec<$elem>,
        }

        pub(crate) static $static: WasmLazy<$struct> = WasmLazy::new();

        #[inline]
        pub(crate) fn $getter() -> &'static mut $struct {
            $static.get_or_init(|| $struct {
                buf: vec![$zero; $stride_const * $init_count],
            })
        }

        #[wasm_bindgen]
        pub fn $ptr_fn() -> *const $elem {
            $getter().buf.as_ptr()
        }

        #[wasm_bindgen]
        pub fn $ensure_fn($ensure_param: u32) {
            let needed = ($ensure_param as usize) * $stride_const;
            let s = $getter();
            if s.buf.len() < needed {
                s.buf.resize(needed, $zero);
            }
        }
    };
}
// ─────────────────────────────────────────────────────────────────
// Snapshot entity encoder (Phase 10 D.3j)
//
// Byte-equal port of stateSerializerEntities.ts:serializeEntitySnapshot's
// output AS msgpack-encoded via @msgpack/msgpack with ignoreUndefined:
// true. Each `snapshot_encode_entity_*` function emits one entity's
// MessagePack bytes into the D.2 writer's scratch buffer; JS reads
// via messagepack_writer_ptr() / _len().
//
// The port lands incrementally — each successive commit handles one
// more field group (envelope → unit sub-object → turret array →
// building sub-object → factory/solar/build/...). Until the full
// kernel exists, callers that need the OUTGOING wire bytes still go
// through the JS path; the Rust path is verified against the JS
// path on every dev build via the (D.3j) byte-equality test runner.
// ─────────────────────────────────────────────────────────────────

/// Entity-type tag for the encoder kernels. Mirrors EntityType
/// strings used in the JS NetworkServerSnapshotEntity DTO.
pub const SNAPSHOT_ENTITY_TYPE_UNIT: u8 = 1;
pub const SNAPSHOT_ENTITY_TYPE_BUILDING: u8 = 2;
pub const SNAPSHOT_ENTITY_TYPE_TOWER: u8 = 3;

// Encoder turret scratch — JS pre-fills with already-quantized
// turret values, then the encoder reads from it when emitting the
// turrets array. Layout per turret (13 f64 = 104 bytes):
//   [0..3]  qRot(rotation, vel, pitch, pitchVel)
//   [4]     turretBlueprintCode (TurretBlueprintCode as f64)
//   [5]     state code (TurretStateCode as f64)
//   [6]     has_target_id (0 or 1)
//   [7]     target_id (raw entity id as f64; ignored when has_target_id==0)
//   [8]     has_shield_range (0 or 1)
//   [9]     shield_range (raw value; ignored when has_ff_range==0)
//   [10]    inactive flag
//   [11]    authoritative host-piece yaw (quantized rotation)
//   [12]    host-piece yaw velocity (quantized rotation rate)
//
// Capacity grown on demand by snapshot_encode_turret_scratch_ensure.
snapshot_scratch_pool!(
    SnapshotEncodeTurretScratch,
    SNAPSHOT_ENCODE_TURRET_SCRATCH,
    snapshot_encode_turret_scratch,
    snapshot_encode_turret_scratch_ptr,
    snapshot_encode_turret_scratch_ensure,
    f64,
    0.0,
    SNAPSHOT_ENCODE_TURRET_STRIDE = 13,
    init 8,
    ensure(turret_count)
);

// Encoder action scratch — JS pre-fills with action data, then the
// encoder reads when emitting the actions array. Layout per action
// (16 f64 = 128 bytes):
//   [0]   action type code (u8 ActionTypeCode as f64)
//   [1]   has_pos (0 or 1)
//   [2..4] pos.x, pos.y (when has_pos)
//   [4]   has_pos_z (0 or 1)
//   [5]   pos_z (when has_pos_z)
//   [6]   path_exp (1 emits `true`, 0 omits the key)
//   [7]   has_target_id (0 or 1)
//   [8]   target_id (when has_target_id)
//   [9]   has_building_type (0 or 1)
//   [10]  building_type_string_slot (when has_building_type)
//   [11]  has_grid (0 or 1)
//   [12..14] grid.x, grid.y (when has_grid)
//   [14]  has_building_id (0 or 1)
//   [15]  building_id (when has_building_id)
snapshot_scratch_pool!(
    SnapshotEncodeActionScratch,
    SNAPSHOT_ENCODE_ACTION_SCRATCH,
    snapshot_encode_action_scratch,
    snapshot_encode_action_scratch_ptr,
    snapshot_encode_action_scratch_ensure,
    f64,
    0.0,
    SNAPSHOT_ENCODE_ACTION_STRIDE = 19,
    init 16,
    ensure(action_count)
);

/// String scratch — UTF-8 byte buffer plus an offset/length table
/// indexed by string slot. JS pre-fills both before any encoder
/// call that emits a string field; the kernel reads via the table.
///
/// `bytes` holds the concatenated UTF-8 of every string; `table[2i]`
/// is the byte offset, `table[2i+1]` is the byte length. A slot
/// with length 0 emits the empty string `""`.
pub(crate) struct SnapshotEncodeStringScratch {
    bytes: Vec<u8>,
    table: Vec<u32>,
}

pub(crate) static SNAPSHOT_ENCODE_STRING_SCRATCH: WasmLazy<SnapshotEncodeStringScratch> =
    WasmLazy::new();

#[inline]
pub(crate) fn snapshot_encode_string_scratch() -> &'static mut SnapshotEncodeStringScratch {
    SNAPSHOT_ENCODE_STRING_SCRATCH.get_or_init(|| SnapshotEncodeStringScratch {
        bytes: vec![0u8; 256],
        table: vec![0u32; 16],
    })
}

#[wasm_bindgen]
pub fn snapshot_encode_string_scratch_bytes_ptr() -> *const u8 {
    snapshot_encode_string_scratch().bytes.as_ptr()
}

#[wasm_bindgen]
pub fn snapshot_encode_string_scratch_table_ptr() -> *const u32 {
    snapshot_encode_string_scratch().table.as_ptr()
}

#[wasm_bindgen]
pub fn snapshot_encode_string_scratch_ensure_bytes(byte_count: u32) {
    let s = snapshot_encode_string_scratch();
    let needed = byte_count as usize;
    if s.bytes.len() < needed {
        s.bytes.resize(needed, 0);
    }
}

#[wasm_bindgen]
pub fn snapshot_encode_string_scratch_ensure_table(slot_count: u32) {
    let s = snapshot_encode_string_scratch();
    let needed = (slot_count as usize) * 2; // pairs of (offset, length)
    if s.table.len() < needed {
        s.table.resize(needed, 0);
    }
}

/// Factory selected-unit scratch — one unit-type code when the factory
/// has a repeat-build selection. JS pre-fills before calling
/// encode_entity_building with has_factory=1.
pub(crate) struct SnapshotEncodeFactoryQueueScratch {
    buf: Vec<u32>,
}

pub(crate) static SNAPSHOT_ENCODE_FACTORY_QUEUE_SCRATCH: WasmLazy<
    SnapshotEncodeFactoryQueueScratch,
> = WasmLazy::new();

#[inline]
pub(crate) fn snapshot_encode_factory_queue_scratch(
) -> &'static mut SnapshotEncodeFactoryQueueScratch {
    SNAPSHOT_ENCODE_FACTORY_QUEUE_SCRATCH.get_or_init(|| SnapshotEncodeFactoryQueueScratch {
        buf: vec![0u32; 16],
    })
}

#[wasm_bindgen]
pub fn snapshot_encode_factory_queue_scratch_ptr() -> *const u32 {
    snapshot_encode_factory_queue_scratch().buf.as_ptr()
}

#[wasm_bindgen]
pub fn snapshot_encode_factory_queue_scratch_ensure(count: u32) {
    let s = snapshot_encode_factory_queue_scratch();
    if s.buf.len() < count as usize {
        s.buf.resize(count as usize, 0);
    }
}

// Factory waypoint scratch — 5 f64 per waypoint:
//   [0..2]  pos.x, pos.y
//   [2]     has_pos_z (0 or 1)
//   [3]     pos_z (when has_pos_z)
//   [4]     type_string_slot (index into string scratch)
snapshot_scratch_pool!(
    SnapshotEncodeWaypointScratch,
    SNAPSHOT_ENCODE_WAYPOINT_SCRATCH,
    snapshot_encode_waypoint_scratch,
    snapshot_encode_waypoint_scratch_ptr,
    snapshot_encode_waypoint_scratch_ensure,
    f64,
    0.0,
    SNAPSHOT_ENCODE_WAYPOINT_STRIDE = 5,
    init 16,
    ensure(count)
);

/// Write a string slot's bytes to the MessagePack writer. Returns
/// silently for out-of-bounds slots (caller is responsible for
/// having populated the slot via the byte+table buffers).
pub(crate) fn write_string_from_scratch(w: &mut MessagePackWriter, slot: u32) {
    let scratch = snapshot_encode_string_scratch();
    let s = slot as usize;
    let i = s * 2;
    if i + 1 >= scratch.table.len() {
        w.write_str("");
        return;
    }
    let offset = scratch.table[i] as usize;
    let length = scratch.table[i + 1] as usize;
    if offset + length > scratch.bytes.len() {
        w.write_str("");
        return;
    }
    // SAFETY: caller wrote valid UTF-8 into this region. Skip the
    // UTF-8 check (from_utf8 + unwrap) — wasm-bindgen guarantees
    // valid UTF-8 from the JS TextEncoder source.
    let bytes = &scratch.bytes[offset..offset + length];
    let s = unsafe { core::str::from_utf8_unchecked(bytes) };
    w.write_str(s);
}

/// Write the sparse envelope key-value pairs (id, type, optional pos,
/// optional rotation, playerId, changedFields) shared by every encoder kernel. Caller
/// is responsible for writing the parent map header with the right
/// key count (envelope keys + sub-object keys). `changed_fields` is
/// emitted only when `has_changed_fields != 0` so the full-snapshot
/// path can omit the key entirely.
pub(crate) fn write_entity_envelope_keys(
    w: &mut MessagePackWriter,
    id: u32,
    type_tag: u8,
    qpos_x: f64,
    qpos_y: f64,
    qpos_z: f64,
    qrot: f64,
    player_id: u8,
    has_changed_fields: u8,
    changed_fields: u32,
) {
    let is_full = has_changed_fields == 0;
    let has_pos = is_full || (changed_fields & ENTITY_CHANGED_POS) != 0;
    let has_rotation = is_full || (changed_fields & ENTITY_CHANGED_ROT) != 0;

    w.write_str("id");
    w.write_uint(id as u64);

    w.write_str("type");
    match type_tag {
        SNAPSHOT_ENTITY_TYPE_UNIT => w.write_str("unit"),
        SNAPSHOT_ENTITY_TYPE_BUILDING => w.write_str("building"),
        SNAPSHOT_ENTITY_TYPE_TOWER => w.write_str("tower"),
        _ => w.write_str(""),
    }

    if has_pos {
        w.write_str("pos");
        w.write_map_header(3);
        w.write_str("x");
        w.write_number(qpos_x);
        w.write_str("y");
        w.write_number(qpos_y);
        w.write_str("z");
        w.write_number(qpos_z);
    }

    if has_rotation {
        w.write_str("rotation");
        w.write_number(qrot);
    }

    w.write_str("playerId");
    w.write_uint(player_id as u64);

    if has_changed_fields != 0 {
        w.write_str("changedFields");
        w.write_uint(changed_fields as u64);
    }
}

pub(crate) fn entity_envelope_key_count(has_changed_fields: u8, changed_fields: u32) -> usize {
    let is_full = has_changed_fields == 0;
    let mut key_count: usize = 3; // id, type, playerId
    if is_full || (changed_fields & ENTITY_CHANGED_POS) != 0 {
        key_count += 1;
    }
    if is_full || (changed_fields & ENTITY_CHANGED_ROT) != 0 {
        key_count += 1;
    }
    if has_changed_fields != 0 {
        key_count += 1;
    }
    key_count
}

/// Encode the entity envelope: `{id, type, [pos,] [rotation,] playerId
/// [, changedFields]}` — the base fields every
/// NetworkServerSnapshotEntity carries plus the optional delta mask.
/// Output written to the D.2 writer; returns the number of bytes.
///
/// Field order matches the JS DTO's property insertion order so the
/// MessagePack key sequence is identical: id → type → pos → rotation
/// → playerId → changedFields. Quantized numbers are passed in as
/// f64 (caller does qPos / qRot conversion).
#[wasm_bindgen]
pub fn snapshot_encode_entity_basic(
    id: u32,
    type_tag: u8,
    qpos_x: f64,
    qpos_y: f64,
    qpos_z: f64,
    qrot: f64,
    player_id: u8,
    has_changed_fields: u8,
    changed_fields: u32,
) -> u32 {
    let w = messagepack_writer();
    let start = w.buf.len();

    let key_count = entity_envelope_key_count(has_changed_fields, changed_fields);
    w.write_map_header(key_count);
    write_entity_envelope_keys(
        w,
        id,
        type_tag,
        qpos_x,
        qpos_y,
        qpos_z,
        qrot,
        player_id,
        has_changed_fields,
        changed_fields,
    );
    (w.buf.len() - start) as u32
}

/// Encode an entity with a unit sub-object. Delta records only emit
/// `hp` and `velocity` when the corresponding changedFields bit is set.
/// Optional keys gated by `has_*` flags include surfaceNormal,
/// orientation, angularVelocity3, actions, turrets, and build state.
///
/// Field order inside `unit` mirrors the pooled DTO's runtime
/// insertion order in stateSerializerEntities.ts.
#[wasm_bindgen]
pub fn snapshot_encode_entity_unit(
    id: u32,
    type_tag: u8,
    qpos_x: f64,
    qpos_y: f64,
    qpos_z: f64,
    qrot: f64,
    player_id: u8,
    has_changed_fields: u8,
    changed_fields: u32,
    hp_curr: f64,
    hp_max: f64,
    qvel_x: f64,
    qvel_y: f64,
    qvel_z: f64,
    has_unit_type: u8,
    unit_type_code: u32,
    has_radius: u8,
    radius_visual: f64,
    radius_hitbox: f64,
    radius_collision: f64,
    has_support_point_offset_z: u8,
    support_point_offset_z: f64,
    has_mass: u8,
    mass: f64,
    has_surface_normal: u8,
    qnormal_x: f64,
    qnormal_y: f64,
    qnormal_z: f64,
    has_orientation: u8,
    qorient_x: f64,
    qorient_y: f64,
    qorient_z: f64,
    qorient_w: f64,
    has_angular_velocity3: u8,
    qangvel_x: f64,
    qangvel_y: f64,
    qangvel_z: f64,
    has_fire_enabled: u8,
    has_is_commander: u8,
    has_build_target_id: u8,
    build_target_id_is_null: u8,
    build_target_id: u32,
    has_actions: u8,
    action_count: u8,
    has_turrets: u8,
    turret_count: u8,
    has_build: u8,
    build_complete: u8,
    build_paid_energy: f64,
    build_paid_metal: f64,
) -> u32 {
    let w = messagepack_writer();
    let start = w.buf.len();

    let mut key_count = entity_envelope_key_count(has_changed_fields, changed_fields);
    key_count += 1; // unit
    w.write_map_header(key_count);
    write_entity_envelope_keys(
        w,
        id,
        type_tag,
        qpos_x,
        qpos_y,
        qpos_z,
        qrot,
        player_id,
        has_changed_fields,
        changed_fields,
    );

    let is_full = has_changed_fields == 0;
    let has_hp = is_full || (changed_fields & ENTITY_CHANGED_HP) != 0;
    let has_velocity = is_full || (changed_fields & ENTITY_CHANGED_VEL) != 0;
    let mut unit_field_count: usize = 0;
    if has_hp {
        unit_field_count += 1;
    }
    if has_velocity {
        unit_field_count += 1;
    }
    if has_unit_type != 0 {
        unit_field_count += 1;
    }
    if has_radius != 0 {
        unit_field_count += 1;
    }
    if has_support_point_offset_z != 0 {
        unit_field_count += 1;
    }
    if has_mass != 0 {
        unit_field_count += 1;
    }
    if has_is_commander != 0 {
        unit_field_count += 1;
    }
    if has_surface_normal != 0 {
        unit_field_count += 1;
    }
    if has_orientation != 0 {
        unit_field_count += 1;
    }
    if has_angular_velocity3 != 0 {
        unit_field_count += 1;
    }
    if has_fire_enabled != 0 {
        unit_field_count += 2; // fireEnabled + fireState
    }
    if has_build != 0 {
        unit_field_count += 1;
    }
    if has_actions != 0 {
        unit_field_count += 1;
    }
    if has_turrets != 0 {
        unit_field_count += 1;
    }
    if has_build_target_id != 0 {
        unit_field_count += 1;
    }

    w.write_str("unit");
    w.write_map_header(unit_field_count);

    if has_hp {
        w.write_str("hp");
        w.write_map_header(2);
        w.write_str("curr");
        w.write_number(hp_curr);
        w.write_str("max");
        w.write_number(hp_max);
    }

    if has_velocity {
        w.write_str("velocity");
        w.write_map_header(3);
        w.write_str("x");
        w.write_number(qvel_x);
        w.write_str("y");
        w.write_number(qvel_y);
        w.write_str("z");
        w.write_number(qvel_z);
    }

    if has_unit_type != 0 {
        w.write_str("unitBlueprintCode");
        w.write_uint(unit_type_code as u64);
    }

    if has_radius != 0 {
        w.write_str("radius");
        w.write_map_header(3);
        w.write_str("other");
        w.write_number(radius_visual);
        w.write_str("hitbox");
        w.write_number(radius_hitbox);
        w.write_str("collision");
        w.write_number(radius_collision);
    }

    if has_support_point_offset_z != 0 {
        w.write_str("supportPointOffsetZ");
        w.write_number(support_point_offset_z);
    }

    if has_mass != 0 {
        w.write_str("mass");
        w.write_number(mass);
    }

    if has_is_commander != 0 {
        w.write_str("isCommander");
        w.write_bool(true);
    }

    if has_surface_normal != 0 {
        w.write_str("surfaceNormal");
        w.write_map_header(3);
        w.write_str("nx");
        w.write_number(qnormal_x);
        w.write_str("ny");
        w.write_number(qnormal_y);
        w.write_str("nz");
        w.write_number(qnormal_z);
    }

    if has_orientation != 0 {
        w.write_str("orientation");
        w.write_map_header(4);
        w.write_str("x");
        w.write_number(qorient_x);
        w.write_str("y");
        w.write_number(qorient_y);
        w.write_str("z");
        w.write_number(qorient_z);
        w.write_str("w");
        w.write_number(qorient_w);
    }

    if has_angular_velocity3 != 0 {
        w.write_str("angularVelocity3");
        w.write_map_header(3);
        w.write_str("x");
        w.write_number(qangvel_x);
        w.write_str("y");
        w.write_number(qangvel_y);
        w.write_str("z");
        w.write_number(qangvel_z);
    }

    // Tri-state scalar/boolean optionals — JS emits them as
    // `false`/`true`/`number|null` or undefined (omitted). Each
    // `has_*` flag gates the key-value pair entirely.
    if has_fire_enabled != 0 {
        w.write_str("fireEnabled");
        w.write_bool(false);
        w.write_str("fireState");
        w.write_str("holdFire");
    }

    if has_build != 0 {
        w.write_str("build");
        w.write_map_header(2); // complete + paid
        w.write_str("complete");
        w.write_bool(build_complete != 0);
        w.write_str("paid");
        w.write_map_header(2);
        w.write_str("energy");
        w.write_number(build_paid_energy);
        w.write_str("metal");
        w.write_number(build_paid_metal);
    }

    if has_actions != 0 {
        let count = action_count as usize;
        let scratch = snapshot_encode_action_scratch();
        w.write_str("actions");
        w.write_array_header(count);
        for a in 0..count {
            let base = a * SNAPSHOT_ENCODE_ACTION_STRIDE;
            let type_code = scratch.buf[base];
            let has_pos = scratch.buf[base + 1] != 0.0;
            let pos_x = scratch.buf[base + 2];
            let pos_y = scratch.buf[base + 3];
            let has_pos_z = scratch.buf[base + 4] != 0.0;
            let pos_z = scratch.buf[base + 5];
            let path_exp = scratch.buf[base + 6] != 0.0;
            let has_target_id = scratch.buf[base + 7] != 0.0;
            let target_id = scratch.buf[base + 8];
            let has_building_type = scratch.buf[base + 9] != 0.0;
            let building_type_string_slot = scratch.buf[base + 10] as u32;
            let has_grid = scratch.buf[base + 11] != 0.0;
            let grid_x = scratch.buf[base + 12];
            let grid_y = scratch.buf[base + 13];
            let has_building_id = scratch.buf[base + 14] != 0.0;
            let building_id = scratch.buf[base + 15];

            // Insertion order in createActionDto: type, pos, posZ,
            // pathExp, targetId, buildingBlueprintId, grid, buildingId.
            // ignoreUndefined drops absent keys.
            let mut action_field_count: usize = 1; // type (always present)
            if has_pos {
                action_field_count += 1;
            }
            if has_pos_z {
                action_field_count += 1;
            }
            if path_exp {
                action_field_count += 1;
            }
            if has_target_id {
                action_field_count += 1;
            }
            if has_building_type {
                action_field_count += 1;
            }
            if has_grid {
                action_field_count += 1;
            }
            if has_building_id {
                action_field_count += 1;
            }
            w.write_map_header(action_field_count);

            w.write_str("type");
            w.write_number(type_code);

            if has_pos {
                w.write_str("pos");
                w.write_map_header(2);
                w.write_str("x");
                w.write_number(pos_x);
                w.write_str("y");
                w.write_number(pos_y);
            }
            if has_pos_z {
                w.write_str("posZ");
                w.write_number(pos_z);
            }
            if path_exp {
                w.write_str("pathExp");
                w.write_bool(true);
            }
            if has_target_id {
                w.write_str("targetId");
                w.write_number(target_id);
            }
            if has_building_type {
                w.write_str("buildingBlueprintId");
                write_string_from_scratch(w, building_type_string_slot);
            }
            if has_grid {
                w.write_str("grid");
                w.write_map_header(2);
                w.write_str("x");
                w.write_number(grid_x);
                w.write_str("y");
                w.write_number(grid_y);
            }
            if has_building_id {
                w.write_str("buildingId");
                w.write_number(building_id);
            }
        }
    }

    if has_turrets != 0 {
        let count = turret_count as usize;
        let scratch = snapshot_encode_turret_scratch();
        w.write_str("turrets");
        w.write_array_header(count);
        for t in 0..count {
            let base = t * SNAPSHOT_ENCODE_TURRET_STRIDE;
            let qrot = scratch.buf[base];
            let qvel = scratch.buf[base + 1];
            let qpitch = scratch.buf[base + 2];
            let qpitch_vel = scratch.buf[base + 3];
            let qhost_yaw = scratch.buf[base + 11];
            let qhost_yaw_vel = scratch.buf[base + 12];
            let turret_blueprint_code = scratch.buf[base + 4];
            let state_code = scratch.buf[base + 5];
            let has_target = scratch.buf[base + 6] != 0.0;
            let target_id_raw = scratch.buf[base + 7];
            let has_ff_range = scratch.buf[base + 8] != 0.0;
            let ff_range_raw = scratch.buf[base + 9];

            // turret DTO: { turret: { turretBlueprintCode, angular: {4 fields} }, [targetId,]
            // state, [currentShieldRange] }
            let mut turret_field_count: usize = 2; // turret + state
            if has_target {
                turret_field_count += 1;
            }
            if has_ff_range {
                turret_field_count += 1;
            }
            w.write_map_header(turret_field_count);

            w.write_str("turret");
            w.write_map_header(2); // turretBlueprintCode + angular
            w.write_str("turretBlueprintCode");
            w.write_number(turret_blueprint_code);
            w.write_str("angular");
            w.write_map_header(6);
            w.write_str("rot");
            w.write_number(qrot);
            w.write_str("vel");
            w.write_number(qvel);
            w.write_str("pitch");
            w.write_number(qpitch);
            w.write_str("pitchVel");
            w.write_number(qpitch_vel);
            w.write_str("hostYaw");
            w.write_number(qhost_yaw);
            w.write_str("hostYawVel");
            w.write_number(qhost_yaw_vel);

            if has_target {
                w.write_str("targetId");
                w.write_number(target_id_raw);
            }

            w.write_str("state");
            w.write_number(state_code);

            if has_ff_range {
                w.write_str("currentShieldRange");
                w.write_number(ff_range_raw);
            }
        }
    }

    if has_build_target_id != 0 {
        w.write_str("buildTargetId");
        if build_target_id_is_null != 0 {
            w.write_nil();
        } else {
            w.write_uint(build_target_id as u64);
        }
    }

    (w.buf.len() - start) as u32
}

/// Encode a building entity DTO: `{...envelope, building: {
///   [type,] [dim,] [hp,] [build,] [metalExtractionRate,] [solar,] [turrets]
/// }}` — covers everything except the factory sub-object (next commit).
///
/// hp + build are sparse on delta records and are emitted only when
/// their changedFields group is set. Other building-sub fields are gated
/// by their `has_*` flags. Turrets reuse the same scratch as units
/// (D.3j-9).
#[wasm_bindgen]
pub fn snapshot_encode_entity_building(
    id: u32,
    qpos_x: f64,
    qpos_y: f64,
    qpos_z: f64,
    qrot: f64,
    player_id: u8,
    has_changed_fields: u8,
    changed_fields: u32,
    has_type: u8,
    type_code: f64,
    has_dim: u8,
    dim_x: f64,
    dim_y: f64,
    hp_curr: f64,
    hp_max: f64,
    build_complete: u8,
    build_paid_energy: f64,
    build_paid_metal: f64,
    has_metal_extraction_rate: u8,
    metal_extraction_rate: f64,
    has_solar: u8,
    solar_open: u8,
    has_turrets: u8,
    turret_count: u8,
    has_factory: u8,
    factory_queue_count: u32,
    factory_progress: f64,
    factory_producing: u8,
    factory_energy_rate: f64,
    factory_metal_rate: f64,
    factory_waypoint_count: u32,
) -> u32 {
    let w = messagepack_writer();
    let start = w.buf.len();

    let mut key_count = entity_envelope_key_count(has_changed_fields, changed_fields);
    key_count += 1; // building
    w.write_map_header(key_count);
    write_entity_envelope_keys(
        w,
        id,
        SNAPSHOT_ENTITY_TYPE_BUILDING,
        qpos_x,
        qpos_y,
        qpos_z,
        qrot,
        player_id,
        has_changed_fields,
        changed_fields,
    );

    let is_full = has_changed_fields == 0;
    let has_hp = is_full || (changed_fields & ENTITY_CHANGED_HP) != 0;
    let has_build = is_full || (changed_fields & ENTITY_CHANGED_BUILDING) != 0;
    let mut building_field_count: usize = 0;
    if has_hp {
        building_field_count += 1;
    }
    if has_build {
        building_field_count += 1;
    }
    if has_type != 0 {
        building_field_count += 1;
    }
    if has_dim != 0 {
        building_field_count += 1;
    }
    if has_metal_extraction_rate != 0 {
        building_field_count += 1;
    }
    if has_solar != 0 {
        building_field_count += 1;
    }
    if has_turrets != 0 {
        building_field_count += 1;
    }
    if has_factory != 0 {
        building_field_count += 1;
    }

    w.write_str("building");
    w.write_map_header(building_field_count);

    if has_type != 0 {
        w.write_str("buildingBlueprintCode");
        w.write_number(type_code);
    }
    if has_dim != 0 {
        w.write_str("dim");
        w.write_map_header(2);
        w.write_str("x");
        w.write_number(dim_x);
        w.write_str("y");
        w.write_number(dim_y);
    }

    if has_hp {
        w.write_str("hp");
        w.write_map_header(2);
        w.write_str("curr");
        w.write_number(hp_curr);
        w.write_str("max");
        w.write_number(hp_max);
    }

    if has_build {
        w.write_str("build");
        w.write_map_header(2);
        w.write_str("complete");
        w.write_bool(build_complete != 0);
        w.write_str("paid");
        w.write_map_header(2);
        w.write_str("energy");
        w.write_number(build_paid_energy);
        w.write_str("metal");
        w.write_number(build_paid_metal);
    }

    if has_metal_extraction_rate != 0 {
        w.write_str("metalExtractionRate");
        w.write_number(metal_extraction_rate);
    }
    if has_solar != 0 {
        w.write_str("solar");
        w.write_map_header(1);
        w.write_str("open");
        w.write_bool(solar_open != 0);
    }
    if has_turrets != 0 {
        let count = turret_count as usize;
        let scratch = snapshot_encode_turret_scratch();
        w.write_str("turrets");
        w.write_array_header(count);
        for t in 0..count {
            let base = t * SNAPSHOT_ENCODE_TURRET_STRIDE;
            let qrot_t = scratch.buf[base];
            let qvel = scratch.buf[base + 1];
            let qpitch = scratch.buf[base + 2];
            let qpitch_vel = scratch.buf[base + 3];
            let qhost_yaw = scratch.buf[base + 11];
            let qhost_yaw_vel = scratch.buf[base + 12];
            let turret_blueprint_code = scratch.buf[base + 4];
            let state_code = scratch.buf[base + 5];
            let has_target = scratch.buf[base + 6] != 0.0;
            let target_id_raw = scratch.buf[base + 7];
            let has_ff_range = scratch.buf[base + 8] != 0.0;
            let ff_range_raw = scratch.buf[base + 9];

            let mut turret_field_count: usize = 2; // turret + state
            if has_target {
                turret_field_count += 1;
            }
            if has_ff_range {
                turret_field_count += 1;
            }
            w.write_map_header(turret_field_count);

            w.write_str("turret");
            w.write_map_header(2);
            w.write_str("turretBlueprintCode");
            w.write_number(turret_blueprint_code);
            w.write_str("angular");
            w.write_map_header(6);
            w.write_str("rot");
            w.write_number(qrot_t);
            w.write_str("vel");
            w.write_number(qvel);
            w.write_str("pitch");
            w.write_number(qpitch);
            w.write_str("pitchVel");
            w.write_number(qpitch_vel);
            w.write_str("hostYaw");
            w.write_number(qhost_yaw);
            w.write_str("hostYawVel");
            w.write_number(qhost_yaw_vel);

            if has_target {
                w.write_str("targetId");
                w.write_number(target_id_raw);
            }
            w.write_str("state");
            w.write_number(state_code);
            if has_ff_range {
                w.write_str("currentShieldRange");
                w.write_number(ff_range_raw);
            }
        }
    }

    if has_factory != 0 {
        w.write_str("factory");
        w.write_map_header(6); // selectedUnitBlueprintCode, progress, producing, energyRate, metalRate, rally

        let qc = factory_queue_count as usize;
        w.write_str("selectedUnitBlueprintCode");
        if qc > 0 {
            let q = snapshot_encode_factory_queue_scratch();
            w.write_uint(q.buf[0] as u64);
        } else {
            w.write_nil();
        }

        w.write_str("progress");
        w.write_number(factory_progress);

        w.write_str("producing");
        w.write_bool(factory_producing != 0);

        w.write_str("energyRate");
        w.write_number(factory_energy_rate);

        w.write_str("metalRate");
        w.write_number(factory_metal_rate);

        let wpc = factory_waypoint_count as usize;
        w.write_str("rally");
        if wpc > 0 {
            let wp = snapshot_encode_waypoint_scratch();
            let base = 0;
            let pos_x = wp.buf[base];
            let pos_y = wp.buf[base + 1];
            let has_pos_z = wp.buf[base + 2] != 0.0;
            let pos_z = wp.buf[base + 3];
            let type_slot = wp.buf[base + 4] as u32;

            let wp_field_count = if has_pos_z { 3 } else { 2 };
            w.write_map_header(wp_field_count);
            w.write_str("pos");
            w.write_map_header(2);
            w.write_str("x");
            w.write_number(pos_x);
            w.write_str("y");
            w.write_number(pos_y);
            if has_pos_z {
                w.write_str("posZ");
                w.write_number(pos_z);
            }
            w.write_str("type");
            write_string_from_scratch(w, type_slot);
        } else {
            w.write_nil();
        }
    }

    (w.buf.len() - start) as u32
}

// Phase 10 D.3j-15: snapshot envelope encoder.
//
// Mirrors stateSerializer.ts's `_snapshotBuf` pool entry layout:
// the entries are inserted in declaration order at pool creation
// (tick, entities, minimapEntities, economy, sprayTargets,
// audioEvents, projectiles, gameState, removedEntityIds,
// visibilityFiltered). msgpack-with-
// ignoreUndefined emits ONLY the keys whose values are not
// undefined.
//
// This commit covers the always-present minimum subset:
//   - tick (uint)
//   - entities[] (array of unit/building DTOs appended between
//     `_begin` and `_continue` via the per-entity encoders)
//   - economy (empty map for now)
//
// Other envelope fields (audioEvents, projectiles, gameState,
// economy contents, etc.) come in follow-up commits.
//
// API:
//   1. `snapshot_encode_envelope_begin(tick, entity_count)`
//      → clears the writer, writes the envelope map header + tick
//      key + entities key + array16 header.
//   2. For each entity: JS packs scratches and calls one of the
//      existing entity encoders. They APPEND now (no auto-clear).
//   3. `snapshot_encode_envelope_continue()`
//      → writes the tail fields. Returns total
//      written bytes.
// Minimap-entities scratch — 6 f64 per entry:
//   [0]   id (entity id)
//   [1]   pos.x
//   [2]   pos.y
//   [3]   type_tag (1 = unit, 2 = building, 3 = tower, matches SNAPSHOT_ENTITY_TYPE_*)
//   [4]   playerId
//   [5]   has_radar_only + (radar_only << 1) packed: 0 = omit, 2 = emit
//         false (rare), 3 = emit true. Practically only 0 or 3 appear.
snapshot_scratch_pool!(
    SnapshotEncodeMinimapScratch,
    SNAPSHOT_ENCODE_MINIMAP_SCRATCH,
    snapshot_encode_minimap_scratch,
    snapshot_encode_minimap_scratch_ptr,
    snapshot_encode_minimap_scratch_ensure,
    f64,
    0.0,
    SNAPSHOT_ENCODE_MINIMAP_STRIDE = 6,
    init 16,
    ensure(count)
);

/// Projectile-despawn scratch — Uint32Array of projectile ids
/// (one u32 per despawn entry).
pub(crate) struct SnapshotEncodeProjDespawnScratch {
    buf: Vec<u32>,
}

pub(crate) static SNAPSHOT_ENCODE_PROJ_DESPAWN_SCRATCH: WasmLazy<SnapshotEncodeProjDespawnScratch> =
    WasmLazy::new();

#[inline]
pub(crate) fn snapshot_encode_proj_despawn_scratch() -> &'static mut SnapshotEncodeProjDespawnScratch
{
    SNAPSHOT_ENCODE_PROJ_DESPAWN_SCRATCH.get_or_init(|| SnapshotEncodeProjDespawnScratch {
        buf: vec![0u32; 32],
    })
}

#[wasm_bindgen]
pub fn snapshot_encode_proj_despawn_scratch_ptr() -> *const u32 {
    snapshot_encode_proj_despawn_scratch().buf.as_ptr()
}

#[wasm_bindgen]
pub fn snapshot_encode_proj_despawn_scratch_ensure(count: u32) {
    let s = snapshot_encode_proj_despawn_scratch();
    if s.buf.len() < count as usize {
        s.buf.resize(count as usize, 0);
    }
}

// Projectile motion-update scratch — 9 f64 per entry:
//   [0]   id
//   [1..4] pos.x, pos.y, pos.z
//   [4..7] velocity.x, velocity.y, velocity.z
//   [7]   authoritative yaw
//   [8]   authoritative yaw rate
snapshot_scratch_pool!(
    SnapshotEncodeProjVelScratch,
    SNAPSHOT_ENCODE_PROJ_VEL_SCRATCH,
    snapshot_encode_proj_vel_scratch,
    snapshot_encode_proj_vel_scratch_ptr,
    snapshot_encode_proj_vel_scratch_ensure,
    f64,
    0.0,
    SNAPSHOT_ENCODE_PROJ_VEL_STRIDE = 9,
    init 32,
    ensure(count)
);

// Projectile spawn scratch — 32 f64 per entry. Field order matches
// `createPooledProjectileSpawn` in stateSerializerProjectiles.ts so
// the emit loop walks the slots in DTO insertion order.
//   [0]    id
//   [1..4] pos.x, pos.y, pos.z
//   [4]    rotation
//   [5..8] velocity.x, velocity.y, velocity.z
//   [8]    projectileType (code)
//   [9]    maxLifespan (gated by flag bit 0)
//   [10]   turretBlueprintCode
//   [11]   shotBlueprintCode (gated by flag bit 1)
//   [12]   sourceTurretBlueprintCode (gated by flag bit 2)
//   [13]   playerId
//   [14]   sourceEntityId
//   [15]   turretIndex
//   [16]   barrelIndex
//   [17..20] beam.start.x/y/z (gated by flag bit 5)
//   [20..23] beam.end.x/y/z (gated by flag bit 5)
//   [23]   targetEntityId (gated by flag bit 6)
//   [24]   homingTurnRate (gated by flag bit 7)
//   [25]   sourceTurretEntityId (gated by flag bit 10)
//   [26]   sourceHostEntityId
//   [27]   sourceRootEntityId
//   [28]   sourceTeamId
//   [29]   spawnTick
//   [30]   parentShotEntityId (gated by flag bit 11)
//   [31]   flags: bit 0 maxLifespan, 1 shotBlueprintCode, 2 sourceTurretBlueprintCode,
//          3 isDGun(true), 4 fromParentDetonation(true), 5 beam,
//          6 targetEntityId, 7 homingTurnRate, 8 isDGun(false),
//          9 fromParentDetonation(false), 10 sourceTurretEntityId,
//          11 parentShotEntityId.
snapshot_scratch_pool!(
    SnapshotEncodeProjSpawnScratch,
    SNAPSHOT_ENCODE_PROJ_SPAWN_SCRATCH,
    snapshot_encode_proj_spawn_scratch,
    snapshot_encode_proj_spawn_scratch_ptr,
    snapshot_encode_proj_spawn_scratch_ensure,
    f64,
    0.0,
    SNAPSHOT_ENCODE_PROJ_SPAWN_STRIDE = 32,
    init 16,
    ensure(count)
);

// Beam-update header scratch — 4 f64 per update:
//   [0]   id
//   [1]   flags: bit 0 has_obstructionT, bit 1 has_endpointDamageable_false,
//         bit 2 has_endpointDamageable_true
//   [2]   obstructionT (qRot value, only valid if flag set)
//   [3]   point_count (u32 as f64, points come from beam_point_scratch
//         in order — first update's points then next update's, etc.)
snapshot_scratch_pool!(
    SnapshotEncodeBeamUpdateScratch,
    SNAPSHOT_ENCODE_BEAM_UPDATE_SCRATCH,
    snapshot_encode_beam_update_scratch,
    snapshot_encode_beam_update_scratch_ptr,
    snapshot_encode_beam_update_scratch_ensure,
    f64,
    0.0,
    SNAPSHOT_ENCODE_BEAM_UPDATE_STRIDE = 4,
    init 16,
    ensure(count)
);

// Beam-point scratch — flat 12 f64 per point across ALL beam updates
// (first update's N1 points, then next update's N2 points, etc.).
//   [0..3]  x, y, z
//   [3..6]  vx, vy, vz
//   [6]     flags: bit 0 has_reflectorEntityId, bit 1 has_reflectorKind
//           (shield material; bit 2 unused), bit 3 has_reflectorPlayerId,
//           bit 4 has_normalX, bit 5 has_normalY, bit 6 has_normalZ.
//   [7]     reflectorEntityId
//   [8]     reflectorPlayerId
//   [9..12] normalX, normalY, normalZ
snapshot_scratch_pool!(
    SnapshotEncodeBeamPointScratch,
    SNAPSHOT_ENCODE_BEAM_POINT_SCRATCH,
    snapshot_encode_beam_point_scratch,
    snapshot_encode_beam_point_scratch_ptr,
    snapshot_encode_beam_point_scratch_ensure,
    f64,
    0.0,
    SNAPSHOT_ENCODE_BEAM_POINT_STRIDE = 12,
    init 64,
    ensure(count)
);

pub(crate) const PACKED_BINARY_ROW_COUNT_BYTES: usize = 4;
pub(crate) const PACKED_MINIMAP_ENTITIES_VERSION: u64 = 2;
pub(crate) const PACKED_MINIMAP_ENTITY_FLAG_RADAR_ONLY: u32 = 0x01;
pub(crate) const PACKED_PROJECTILES_VERSION: u64 = 1;
pub(crate) const PROJECTILE_SPAWN_FLAG_MAX_LIFESPAN: u32 = 0x001;
pub(crate) const PROJECTILE_SPAWN_FLAG_SHOT_BLUEPRINT_CODE: u32 = 0x002;
pub(crate) const PROJECTILE_SPAWN_FLAG_SOURCE_TURRET_BLUEPRINT_CODE: u32 = 0x004;
pub(crate) const PROJECTILE_SPAWN_FLAG_BEAM: u32 = 0x020;
pub(crate) const PROJECTILE_SPAWN_FLAG_TARGET_ENTITY_ID: u32 = 0x040;
pub(crate) const PROJECTILE_SPAWN_FLAG_HOMING_TURN_RATE: u32 = 0x080;
pub(crate) const PROJECTILE_SPAWN_FLAG_SOURCE_TURRET_ENTITY_ID: u32 = 0x400;
pub(crate) const PROJECTILE_SPAWN_FLAG_PARENT_SHOT_ENTITY_ID: u32 = 0x800;
pub(crate) const PROJECTILE_BEAM_UPDATE_FLAG_OBSTRUCTION_T: u32 = 0x01;
pub(crate) const PROJECTILE_BEAM_POINT_FLAG_MIRROR_ENTITY_ID: u32 = 0x01;
pub(crate) const PROJECTILE_BEAM_POINT_FLAG_REFLECTOR_PLAYER_ID: u32 = 0x08;
pub(crate) const PROJECTILE_BEAM_POINT_FLAG_NORMAL_X: u32 = 0x10;
pub(crate) const PROJECTILE_BEAM_POINT_FLAG_NORMAL_Y: u32 = 0x20;
pub(crate) const PROJECTILE_BEAM_POINT_FLAG_NORMAL_Z: u32 = 0x40;

#[derive(Default)]
pub(crate) struct PackedBinaryWriter {
    buf: Vec<u8>,
}

impl PackedBinaryWriter {
    pub(crate) fn reset(&mut self, initial_len: usize) {
        self.buf.clear();
        self.buf.resize(initial_len, 0);
    }

    pub(crate) fn as_slice(&self) -> &[u8] {
        self.buf.as_slice()
    }

    pub(crate) fn write_var_uint(&mut self, value: u64) {
        let mut v = value;
        while v >= 0x80 {
            self.buf.push(((v % 0x80) as u8) | 0x80);
            v /= 0x80;
        }
        self.buf.push(v as u8);
    }

    pub(crate) fn write_var_uint_from_f64(&mut self, value: f64) {
        self.write_var_uint(f64_floor_u64(value));
    }

    pub(crate) fn write_var_int(&mut self, value: i64) {
        let zigzag = if value < 0 {
            ((-value) as u64).saturating_mul(2).saturating_sub(1)
        } else {
            (value as u64).saturating_mul(2)
        };
        self.write_var_uint(zigzag);
    }

    pub(crate) fn write_var_int_from_f64(&mut self, value: f64) {
        self.write_var_int(f64_round_i64(value));
    }

    pub(crate) fn write_bytes(&mut self, bytes: &[u8]) {
        self.buf.extend_from_slice(bytes);
    }

    /// Little-endian f64, matching TS PackedBinaryWriter.writeFloat64
    /// (DataView.setFloat64(..., true)).
    pub(crate) fn write_f64_le(&mut self, value: f64) {
        self.buf.extend_from_slice(&value.to_le_bytes());
    }

    pub(crate) fn set_u32_le(&mut self, offset: usize, value: u32) {
        if offset + 4 > self.buf.len() {
            self.buf.resize(offset + 4, 0);
        }
        self.buf[offset..offset + 4].copy_from_slice(&value.to_le_bytes());
    }
}

#[derive(Default)]
pub(crate) struct PackedMinimapGroup {
    type_tag: u32,
    player_id: u32,
    flags: u32,
    count: u32,
    last_id: i64,
    writer: PackedBinaryWriter,
}

impl PackedMinimapGroup {
    pub(crate) fn reset(&mut self, type_tag: u32, player_id: u32, flags: u32) {
        self.type_tag = type_tag;
        self.player_id = player_id;
        self.flags = flags;
        self.count = 0;
        self.last_id = 0;
        self.writer.reset(0);
    }
}

#[derive(Default)]
pub(crate) struct SnapshotEncodePackedMinimapScratch {
    out: PackedBinaryWriter,
    groups: Vec<PackedMinimapGroup>,
    group_count: usize,
}

impl SnapshotEncodePackedMinimapScratch {
    pub(crate) fn reset_groups(&mut self) {
        self.group_count = 0;
    }

    pub(crate) fn group_index(&mut self, type_tag: u32, player_id: u32, flags: u32) -> usize {
        for i in 0..self.group_count {
            let group = &self.groups[i];
            if group.type_tag == type_tag && group.player_id == player_id && group.flags == flags {
                return i;
            }
        }
        let index = self.group_count;
        if index == self.groups.len() {
            self.groups.push(PackedMinimapGroup::default());
        }
        self.groups[index].reset(type_tag, player_id, flags);
        self.group_count += 1;
        index
    }
}

pub(crate) static SNAPSHOT_ENCODE_PACKED_MINIMAP_SCRATCH: WasmLazy<
    SnapshotEncodePackedMinimapScratch,
> = WasmLazy::new();

#[inline]
pub(crate) fn snapshot_encode_packed_minimap_scratch(
) -> &'static mut SnapshotEncodePackedMinimapScratch {
    SNAPSHOT_ENCODE_PACKED_MINIMAP_SCRATCH.get_or_init(SnapshotEncodePackedMinimapScratch::default)
}

pub(crate) fn pack_minimap_entities_v2(count: usize) {
    let rows = snapshot_encode_minimap_scratch();
    let scratch = snapshot_encode_packed_minimap_scratch();
    scratch.out.reset(PACKED_BINARY_ROW_COUNT_BYTES);
    scratch.reset_groups();

    for i in 0..count {
        let base = i * SNAPSHOT_ENCODE_MINIMAP_STRIDE;
        let type_tag = f64_floor_u64(rows.buf[base + 3]) as u32;
        let player_id = f64_floor_u64(rows.buf[base + 4]) as u32;
        let scratch_flags = f64_floor_u64(rows.buf[base + 5]) as u32;
        let flags = if (scratch_flags & 0x02) != 0 {
            PACKED_MINIMAP_ENTITY_FLAG_RADAR_ONLY
        } else {
            0
        };
        let group_index = scratch.group_index(type_tag, player_id, flags);
        let group = &mut scratch.groups[group_index];
        let id = f64_round_i64(rows.buf[base]);
        group.writer.write_var_int(id - group.last_id);
        group.last_id = id;
        group.writer.write_var_int_from_f64(rows.buf[base + 1]);
        group.writer.write_var_int_from_f64(rows.buf[base + 2]);
        group.count += 1;
    }

    let group_count = scratch.group_count;
    let out = &mut scratch.out;
    let groups = &scratch.groups;
    out.write_var_uint(group_count as u64);
    for group in groups.iter().take(group_count) {
        out.write_var_uint(group.type_tag as u64);
        out.write_var_uint(group.player_id as u64);
        out.write_var_uint(group.flags as u64);
        out.write_var_uint(group.count as u64);
        out.write_bytes(group.writer.as_slice());
    }
    out.set_u32_le(0, count as u32);
}

#[derive(Default)]
pub(crate) struct PackedProjectileGroup {
    flags: u32,
    count: u32,
    last_id: i64,
    writer: PackedBinaryWriter,
}

impl PackedProjectileGroup {
    pub(crate) fn reset(&mut self, flags: u32) {
        self.flags = flags;
        self.count = 0;
        self.last_id = 0;
        self.writer.reset(0);
    }
}

#[derive(Default)]
pub(crate) struct SnapshotEncodePackedProjectileScratch {
    out: PackedBinaryWriter,
    spawn_groups: Vec<PackedProjectileGroup>,
    spawn_group_count: usize,
    velocity_groups: Vec<PackedProjectileGroup>,
    velocity_group_count: usize,
}

impl SnapshotEncodePackedProjectileScratch {
    pub(crate) fn reset_spawn_groups(&mut self) {
        self.spawn_group_count = 0;
    }

    pub(crate) fn reset_velocity_groups(&mut self) {
        self.velocity_group_count = 0;
    }

    pub(crate) fn spawn_group_index(&mut self, flags: u32) -> usize {
        find_or_create_packed_group(&mut self.spawn_groups, &mut self.spawn_group_count, flags)
    }

    pub(crate) fn velocity_group_index(&mut self, flags: u32) -> usize {
        find_or_create_packed_group(
            &mut self.velocity_groups,
            &mut self.velocity_group_count,
            flags,
        )
    }
}

pub(crate) static SNAPSHOT_ENCODE_PACKED_PROJECTILE_SCRATCH: WasmLazy<
    SnapshotEncodePackedProjectileScratch,
> = WasmLazy::new();

#[inline]
pub(crate) fn snapshot_encode_packed_projectile_scratch(
) -> &'static mut SnapshotEncodePackedProjectileScratch {
    SNAPSHOT_ENCODE_PACKED_PROJECTILE_SCRATCH
        .get_or_init(SnapshotEncodePackedProjectileScratch::default)
}

pub(crate) fn find_or_create_packed_group(
    groups: &mut Vec<PackedProjectileGroup>,
    active_count: &mut usize,
    flags: u32,
) -> usize {
    for i in 0..*active_count {
        if groups[i].flags == flags {
            return i;
        }
    }
    let index = *active_count;
    if index == groups.len() {
        groups.push(PackedProjectileGroup::default());
    }
    groups[index].reset(flags);
    *active_count += 1;
    index
}

pub(crate) fn f64_round_i64(value: f64) -> i64 {
    if value.is_finite() {
        value.round() as i64
    } else {
        0
    }
}

pub(crate) fn f64_floor_u64(value: f64) -> u64 {
    if value.is_finite() && value > 0.0 {
        value.floor() as u64
    } else {
        0
    }
}

pub(crate) fn pack_projectile_spawns(count: usize) {
    let rows = snapshot_encode_proj_spawn_scratch();
    let scratch = snapshot_encode_packed_projectile_scratch();
    scratch.out.reset(PACKED_BINARY_ROW_COUNT_BYTES);
    if count == 0 {
        scratch.out.write_var_uint(0);
        scratch.out.set_u32_le(0, 0);
        return;
    }

    scratch.reset_spawn_groups();
    for i in 0..count {
        let base = i * SNAPSHOT_ENCODE_PROJ_SPAWN_STRIDE;
        let flags = rows.buf[base + 31] as u32;
        let group_index = scratch.spawn_group_index(flags);
        let group = &mut scratch.spawn_groups[group_index];
        let id = f64_round_i64(rows.buf[base]);
        group.writer.write_var_int(id - group.last_id);
        group.last_id = id;
        group.writer.write_var_int_from_f64(rows.buf[base + 1]);
        group.writer.write_var_int_from_f64(rows.buf[base + 2]);
        group.writer.write_var_int_from_f64(rows.buf[base + 3]);
        group.writer.write_var_int_from_f64(rows.buf[base + 4]);
        group.writer.write_var_int_from_f64(rows.buf[base + 5]);
        group.writer.write_var_int_from_f64(rows.buf[base + 6]);
        group.writer.write_var_int_from_f64(rows.buf[base + 7]);
        group.writer.write_var_uint_from_f64(rows.buf[base + 8]);
        group.writer.write_var_uint_from_f64(rows.buf[base + 10]);
        group.writer.write_var_uint_from_f64(rows.buf[base + 13]);
        group.writer.write_var_uint_from_f64(rows.buf[base + 14]);
        group.writer.write_var_uint_from_f64(rows.buf[base + 26]);
        group.writer.write_var_uint_from_f64(rows.buf[base + 27]);
        group.writer.write_var_uint_from_f64(rows.buf[base + 28]);
        group.writer.write_var_uint_from_f64(rows.buf[base + 29]);
        group.writer.write_var_uint_from_f64(rows.buf[base + 15]);
        group.writer.write_var_uint_from_f64(rows.buf[base + 16]);
        if (flags & PROJECTILE_SPAWN_FLAG_MAX_LIFESPAN) != 0 {
            group.writer.write_var_uint_from_f64(rows.buf[base + 9]);
        }
        if (flags & PROJECTILE_SPAWN_FLAG_SHOT_BLUEPRINT_CODE) != 0 {
            group.writer.write_var_uint_from_f64(rows.buf[base + 11]);
        }
        if (flags & PROJECTILE_SPAWN_FLAG_SOURCE_TURRET_BLUEPRINT_CODE) != 0 {
            group.writer.write_var_uint_from_f64(rows.buf[base + 12]);
        }
        if (flags & PROJECTILE_SPAWN_FLAG_SOURCE_TURRET_ENTITY_ID) != 0 {
            group.writer.write_var_uint_from_f64(rows.buf[base + 25]);
        }
        if (flags & PROJECTILE_SPAWN_FLAG_PARENT_SHOT_ENTITY_ID) != 0 {
            group.writer.write_var_uint_from_f64(rows.buf[base + 30]);
        }
        if (flags & PROJECTILE_SPAWN_FLAG_BEAM) != 0 {
            group.writer.write_var_int_from_f64(rows.buf[base + 17]);
            group.writer.write_var_int_from_f64(rows.buf[base + 18]);
            group.writer.write_var_int_from_f64(rows.buf[base + 19]);
            group.writer.write_var_int_from_f64(rows.buf[base + 20]);
            group.writer.write_var_int_from_f64(rows.buf[base + 21]);
            group.writer.write_var_int_from_f64(rows.buf[base + 22]);
        }
        if (flags & PROJECTILE_SPAWN_FLAG_TARGET_ENTITY_ID) != 0 {
            group.writer.write_var_uint_from_f64(rows.buf[base + 23]);
        }
        if (flags & PROJECTILE_SPAWN_FLAG_HOMING_TURN_RATE) != 0 {
            group.writer.write_f64_le(rows.buf[base + 24]);
        }
        group.count += 1;
    }

    let group_count = scratch.spawn_group_count;
    let out = &mut scratch.out;
    let groups = &scratch.spawn_groups;
    out.reset(PACKED_BINARY_ROW_COUNT_BYTES);
    out.write_var_uint(group_count as u64);
    for group in groups.iter().take(group_count) {
        out.write_var_uint(group.flags as u64);
        out.write_var_uint(group.count as u64);
        out.write_bytes(group.writer.as_slice());
    }
    out.set_u32_le(0, count as u32);
}

pub(crate) fn pack_projectile_despawns(count: usize) {
    let rows = snapshot_encode_proj_despawn_scratch();
    let scratch = snapshot_encode_packed_projectile_scratch();
    let out = &mut scratch.out;
    out.reset(PACKED_BINARY_ROW_COUNT_BYTES);
    let mut last_id: i64 = 0;
    for i in 0..count {
        let id = rows.buf[i] as i64;
        out.write_var_int(id - last_id);
        last_id = id;
    }
    out.set_u32_le(0, count as u32);
}

pub(crate) fn pack_projectile_motion_updates(count: usize) {
    let rows = snapshot_encode_proj_vel_scratch();
    let scratch = snapshot_encode_packed_projectile_scratch();
    scratch.out.reset(PACKED_BINARY_ROW_COUNT_BYTES);
    if count == 0 {
        scratch.out.write_var_uint(0);
        scratch.out.set_u32_le(0, 0);
        return;
    }

    scratch.reset_velocity_groups();
    for i in 0..count {
        let base = i * SNAPSHOT_ENCODE_PROJ_VEL_STRIDE;
        let flags = 0;
        let group_index = scratch.velocity_group_index(flags);
        let group = &mut scratch.velocity_groups[group_index];
        let id = f64_round_i64(rows.buf[base]);
        group.writer.write_var_int(id - group.last_id);
        group.last_id = id;
        group.writer.write_var_int_from_f64(rows.buf[base + 1]);
        group.writer.write_var_int_from_f64(rows.buf[base + 2]);
        group.writer.write_var_int_from_f64(rows.buf[base + 3]);
        group.writer.write_var_int_from_f64(rows.buf[base + 4]);
        group.writer.write_var_int_from_f64(rows.buf[base + 5]);
        group.writer.write_var_int_from_f64(rows.buf[base + 6]);
        group.writer.write_var_int_from_f64(rows.buf[base + 7]);
        group.writer.write_var_int_from_f64(rows.buf[base + 8]);
        group.count += 1;
    }

    let group_count = scratch.velocity_group_count;
    let out = &mut scratch.out;
    let groups = &scratch.velocity_groups;
    out.reset(PACKED_BINARY_ROW_COUNT_BYTES);
    out.write_var_uint(group_count as u64);
    for group in groups.iter().take(group_count) {
        out.write_var_uint(group.flags as u64);
        out.write_var_uint(group.count as u64);
        out.write_bytes(group.writer.as_slice());
    }
    out.set_u32_le(0, count as u32);
}

pub(crate) fn pack_beam_point(writer: &mut PackedBinaryWriter, point_base: usize) {
    let points = snapshot_encode_beam_point_scratch();
    let flags = points.buf[point_base + 6] as u32;
    writer.write_var_uint(flags as u64);
    writer.write_var_int_from_f64(points.buf[point_base]);
    writer.write_var_int_from_f64(points.buf[point_base + 1]);
    writer.write_var_int_from_f64(points.buf[point_base + 2]);
    writer.write_var_int_from_f64(points.buf[point_base + 3]);
    writer.write_var_int_from_f64(points.buf[point_base + 4]);
    writer.write_var_int_from_f64(points.buf[point_base + 5]);
    if (flags & PROJECTILE_BEAM_POINT_FLAG_MIRROR_ENTITY_ID) != 0 {
        writer.write_var_uint_from_f64(points.buf[point_base + 7]);
    }
    if (flags & PROJECTILE_BEAM_POINT_FLAG_REFLECTOR_PLAYER_ID) != 0 {
        writer.write_var_uint_from_f64(points.buf[point_base + 8]);
    }
    if (flags & PROJECTILE_BEAM_POINT_FLAG_NORMAL_X) != 0 {
        writer.write_var_int_from_f64(points.buf[point_base + 9]);
    }
    if (flags & PROJECTILE_BEAM_POINT_FLAG_NORMAL_Y) != 0 {
        writer.write_var_int_from_f64(points.buf[point_base + 10]);
    }
    if (flags & PROJECTILE_BEAM_POINT_FLAG_NORMAL_Z) != 0 {
        writer.write_var_int_from_f64(points.buf[point_base + 11]);
    }
}

pub(crate) fn pack_projectile_beam_updates(count: usize, beam_point_count: usize) {
    let updates = snapshot_encode_beam_update_scratch();
    let scratch = snapshot_encode_packed_projectile_scratch();
    let out = &mut scratch.out;
    out.reset(PACKED_BINARY_ROW_COUNT_BYTES);
    let mut last_beam_id: i64 = 0;
    let mut point_offset: usize = 0;
    for i in 0..count {
        let base = i * SNAPSHOT_ENCODE_BEAM_UPDATE_STRIDE;
        let id = f64_round_i64(updates.buf[base]);
        let flags = updates.buf[base + 1] as u32;
        out.write_var_int(id - last_beam_id);
        last_beam_id = id;
        out.write_var_uint(flags as u64);
        if (flags & PROJECTILE_BEAM_UPDATE_FLAG_OBSTRUCTION_T) != 0 {
            out.write_var_int_from_f64(updates.buf[base + 2]);
        }

        let requested_point_count = f64_floor_u64(updates.buf[base + 3]) as usize;
        let available = beam_point_count.saturating_sub(point_offset);
        let point_count = requested_point_count.min(available);
        out.write_var_uint(point_count as u64);
        for p in 0..point_count {
            pack_beam_point(out, (point_offset + p) * SNAPSHOT_ENCODE_BEAM_POINT_STRIDE);
        }
        point_offset += requested_point_count;
    }
    out.set_u32_le(0, count as u32);
}

// Death-context scratch — 16 f64 per deathContext (one per audio
// event that has the has_deathContext flag set). Caller packs in
// the same order as the audio events appear; Rust walks audio
// events and uses a local offset to pull the next deathContext.
//   [0..2]  unitVel.x, unitVel.y
//   [2..4]  hitDir.x, hitDir.y
//   [4..6]  projectileVel.x, projectileVel.y
//   [6]     attackMagnitude
//   [7]     radius
//   [8]     color
//   [9]     visualRadius (gated by flags bit 0)
//   [10]    collisionRadius (gated by flags bit 1)
//   [11]    baseZ (gated by flags bit 2)
//   [12]    rotation (gated by flags bit 4)
//   [13]    unitBlueprintId string-scratch slot (gated by flags bit 3)
//   [14]    turretPoses_count (gated by flags bit 5)
//   [15]    flags: bit 0 has_visualRadius, bit 1 has_collisionRadius,
//            bit 2 has_baseZ, bit 3 has_unitType, bit 4 has_rotation,
//            bit 5 has_turretPoses
snapshot_scratch_pool!(
    SnapshotEncodeDeathContextScratch,
    SNAPSHOT_ENCODE_DEATH_CONTEXT_SCRATCH,
    snapshot_encode_death_context_scratch,
    snapshot_encode_death_context_scratch_ptr,
    snapshot_encode_death_context_scratch_ensure,
    f64,
    0.0,
    SNAPSHOT_ENCODE_DEATH_CONTEXT_STRIDE = 16,
    init 4,
    ensure(count)
);

// Turret-pose scratch (for deathContext.turretPoses arrays) — flat
// across all deathContexts in pack order; stride 2 (rotation, pitch).
snapshot_scratch_pool!(
    SnapshotEncodeTurretPoseScratch,
    SNAPSHOT_ENCODE_TURRET_POSE_SCRATCH,
    snapshot_encode_turret_pose_scratch,
    snapshot_encode_turret_pose_scratch_ptr,
    snapshot_encode_turret_pose_scratch_ensure,
    f64,
    0.0,
    SNAPSHOT_ENCODE_TURRET_POSE_STRIDE = 2,
    init 16,
    ensure(count)
);

// Impact-context scratch — 11 f64 per impactContext (one per audio
// event with has_impactContext flag set). All fields are required
// in the source DTO (no optionals).
//   [0]    radiusCollision
//   [1]    deathExplosionRadius
//   [2..4] projectile.pos.x, projectile.pos.y
//   [4..6] projectile.vel.x, projectile.vel.y
//   [6..8] entity.vel.x, entity.vel.y
//   [8]    entity.radiusCollision
//   [9..11] penetrationDir.x, penetrationDir.y
snapshot_scratch_pool!(
    SnapshotEncodeImpactContextScratch,
    SNAPSHOT_ENCODE_IMPACT_CONTEXT_SCRATCH,
    snapshot_encode_impact_context_scratch,
    snapshot_encode_impact_context_scratch_ptr,
    snapshot_encode_impact_context_scratch_ensure,
    f64,
    0.0,
    SNAPSHOT_ENCODE_IMPACT_CONTEXT_STRIDE = 11,
    init 4,
    ensure(count)
);

// Audio-event scratch — 16 f64 per event (NetworkServerSnapshotSimEvent
// minus deathContext / impactContext, which arrive in follow-ups).
//   [0]    type_code (0='fire', 1='hit', 2='death', 3='laserStart',
//           4='laserStop', 5='shieldStart', 6='shieldStop',
//           7='shieldImpact', 8='ping', 9='attackAlert',
//           10='projectileExpire', 11='waterSplash')
//   [1..3] pos.x, pos.y, pos.z (always present)
//   [4]    playerId (gated by flags bit 2)
//   [5]    entityId (gated by flags bit 3)
//   [6]    killerPlayerId (gated by flags bit 5)
//   [7]    victimPlayerId (gated by flags bit 6)
//   [8..10] shieldImpact.normal.x/y/z (gated by flags bit 4)
//   [11]   shieldImpact.playerId
//   [12]   sourceType_code (gated by flags bit 0; 0='turret', 1='unit',
//           2='building', 3='system')
//   [13]   turretBlueprintId string-scratch slot (always present — empty
//           string is a valid value, encoded as fixstr 0xA0)
//   [14]   sourceKey string-scratch slot (gated by flags bit 1)
//   [15]   flags: bit 0 has_sourceType, bit 1 has_sourceKey,
//           bit 2 has_playerId, bit 3 has_entityId,
//           bit 4 has_shieldImpact, bit 5 has_killerPlayerId,
//           bit 6 has_victimPlayerId, bit 7 has_audioOnly,
//           bit 8 audioOnly_value, bit 9 has_deathContext (TBD),
//           bit 10 has_impactContext (TBD),
//           bit 11 has_waterSplash.
//   [16..18] waterSplash.velocity.x/y/z (gated by flags bit 11)
//   [19]   waterSplash.mass (gated by flags bit 11)
snapshot_scratch_pool!(
    SnapshotEncodeAudioEventScratch,
    SNAPSHOT_ENCODE_AUDIO_EVENT_SCRATCH,
    snapshot_encode_audio_event_scratch,
    snapshot_encode_audio_event_scratch_ptr,
    snapshot_encode_audio_event_scratch_ensure,
    f64,
    0.0,
    SNAPSHOT_ENCODE_AUDIO_EVENT_STRIDE = 20,
    init 16,
    ensure(count)
);

#[inline]
pub(crate) fn audio_event_type_str(code: u8) -> &'static str {
    match code {
        0 => "fire",
        1 => "hit",
        2 => "death",
        3 => "laserStart",
        4 => "laserStop",
        5 => "shieldStart",
        6 => "shieldStop",
        7 => "shieldImpact",
        8 => "ping",
        9 => "attackAlert",
        10 => "projectileExpire",
        11 => "waterSplash",
        _ => "",
    }
}

#[inline]
pub(crate) fn audio_event_source_type_str(code: u8) -> &'static str {
    match code {
        0 => "turret",
        1 => "unit",
        2 => "building",
        3 => "system",
        _ => "",
    }
}

// Economy scratch — 11 f64 per player (caller must pack in ASCENDING
// playerId order to match @msgpack/msgpack's iteration of a JS
// object with integer-string keys).
//   [0]   playerId (becomes the outer-map string key)
//   [1..3] stockpile.curr, stockpile.max
//   [3..5] income.base, income.production
//   [5]   expenditure
//   [6..8] metal.stockpile.curr, metal.stockpile.max
//   [8..10] metal.income.base, metal.income.extraction
//   [10]  metal.expenditure
snapshot_scratch_pool!(
    SnapshotEncodeEconomyScratch,
    SNAPSHOT_ENCODE_ECONOMY_SCRATCH,
    snapshot_encode_economy_scratch,
    snapshot_encode_economy_scratch_ptr,
    snapshot_encode_economy_scratch_ensure,
    f64,
    0.0,
    SNAPSHOT_ENCODE_ECONOMY_STRIDE = 11,
    init 8,
    ensure(count)
);

/// Resource-movement scratch — 7 f64 per movement.
///   [0] playerId
///   [1] sourceEntityId
///   [2] targetEntityId (gated by has_target flag)
///   [3] resource code
///   [4] amountPerSecond
///   [5] direction code
///   [6] has_target flag
pub(crate) const SNAPSHOT_ENCODE_RESOURCE_MOVEMENT_STRIDE: usize = 7;

pub(crate) struct SnapshotEncodeResourceMovementScratch {
    buf: Vec<f64>,
}

pub(crate) static SNAPSHOT_ENCODE_RESOURCE_MOVEMENT_SCRATCH: WasmLazy<
    SnapshotEncodeResourceMovementScratch,
> = WasmLazy::new();

#[inline]
pub(crate) fn snapshot_encode_resource_movement_scratch(
) -> &'static mut SnapshotEncodeResourceMovementScratch {
    SNAPSHOT_ENCODE_RESOURCE_MOVEMENT_SCRATCH.get_or_init(|| {
        SnapshotEncodeResourceMovementScratch {
            buf: vec![0.0; SNAPSHOT_ENCODE_RESOURCE_MOVEMENT_STRIDE * 16],
        }
    })
}

#[wasm_bindgen]
pub fn snapshot_encode_resource_movement_scratch_ptr() -> *const f64 {
    snapshot_encode_resource_movement_scratch().buf.as_ptr()
}

#[wasm_bindgen]
pub fn snapshot_encode_resource_movement_scratch_ensure(count: u32) {
    let needed = (count as usize) * SNAPSHOT_ENCODE_RESOURCE_MOVEMENT_STRIDE;
    let s = snapshot_encode_resource_movement_scratch();
    if s.buf.len() < needed {
        s.buf.resize(needed, 0.0);
    }
}

// Spray-target scratch — 17 f64 per spray (NetworkServerSnapshotSprayTarget).
//   [0]    source.id
//   [1..3] source.pos.x, source.pos.y
//   [3]    source.z (gated by flags bit 1)
//   [4]    source.playerId
//   [5]    target.id
//   [6..8] target.pos.x, target.pos.y
//   [8]    target.z (gated by flags bit 2)
//   [9..11] target.dim.x, target.dim.y (gated by flags bit 3)
//   [11]   target.radius (gated by flags bit 4)
//   [12]   intensity
//   [13]   speed (gated by flags bit 5)
//   [14]   particleRadius (gated by flags bit 6)
//   [15]   ballSpawnRate (gated by flags bit 7)
//   [16]   flags: bit 0 type_is_heal (else 'build'), bit 1 has_source_z,
//          bit 2 has_target_z, bit 3 has_target_dim, bit 4 has_target_radius,
//          bit 5 has_speed, bit 6 has_particleRadius, bit 7 hasBallSpawnRate,
//          bit 8 inverse (target-volume -> source emitter).
snapshot_scratch_pool!(
    SnapshotEncodeSprayScratch,
    SNAPSHOT_ENCODE_SPRAY_SCRATCH,
    snapshot_encode_spray_scratch,
    snapshot_encode_spray_scratch_ptr,
    snapshot_encode_spray_scratch_ensure,
    f64,
    0.0,
    SNAPSHOT_ENCODE_SPRAY_STRIDE = 17,
    init 16,
    ensure(count)
);

/// Shared numeric scratch for low-frequency top-level snapshot
/// payloads such as terrain and buildability. JS packs one or more
/// number arrays back-to-back, then passes offsets/counts into the
/// dedicated envelope emitters below.
pub(crate) struct SnapshotEncodeNumberScratch {
    buf: Vec<f64>,
}

pub(crate) static SNAPSHOT_ENCODE_NUMBER_SCRATCH: WasmLazy<SnapshotEncodeNumberScratch> =
    WasmLazy::new();

#[inline]
pub(crate) fn snapshot_encode_number_scratch() -> &'static mut SnapshotEncodeNumberScratch {
    SNAPSHOT_ENCODE_NUMBER_SCRATCH.get_or_init(|| SnapshotEncodeNumberScratch {
        buf: vec![0.0; 4096],
    })
}

#[wasm_bindgen]
pub fn snapshot_encode_number_scratch_ptr() -> *const f64 {
    snapshot_encode_number_scratch().buf.as_ptr()
}

#[wasm_bindgen]
pub fn snapshot_encode_number_scratch_ensure(number_count: u32) {
    let s = snapshot_encode_number_scratch();
    if s.buf.len() < number_count as usize {
        s.buf.resize(number_count as usize, 0.0);
    }
}

pub(crate) struct SnapshotEncodePackedStaticScratch {
    bytes: Vec<u8>,
}

pub(crate) static SNAPSHOT_ENCODE_PACKED_STATIC_SCRATCH: WasmLazy<
    SnapshotEncodePackedStaticScratch,
> = WasmLazy::new();

#[inline]
pub(crate) fn snapshot_encode_packed_static_scratch(
) -> &'static mut SnapshotEncodePackedStaticScratch {
    SNAPSHOT_ENCODE_PACKED_STATIC_SCRATCH.get_or_init(|| SnapshotEncodePackedStaticScratch {
        bytes: Vec::with_capacity(4096),
    })
}

#[inline]
pub(crate) fn packed_static_write_var_uint(bytes: &mut Vec<u8>, mut value: u64) {
    while value >= 0x80 {
        bytes.push(((value % 0x80) as u8) | 0x80);
        value /= 0x80;
    }
    bytes.push(value as u8);
}

#[inline]
pub(crate) fn packed_static_write_var_int(bytes: &mut Vec<u8>, value: f64) {
    let v = value.round() as i64;
    let encoded = if v < 0 {
        ((-v) as u64 * 2) - 1
    } else {
        (v as u64) * 2
    };
    packed_static_write_var_uint(bytes, encoded);
}

pub(crate) fn write_number_scratch_float32_bin(w: &mut MessagePackWriter, offset: u32, count: u32) {
    let numbers = snapshot_encode_number_scratch();
    let scratch = snapshot_encode_packed_static_scratch();
    let start = offset as usize;
    let n = count as usize;
    scratch.bytes.clear();
    scratch.bytes.reserve(n * 4);
    for i in 0..n {
        let value = numbers.buf.get(start + i).copied().unwrap_or(0.0) as f32;
        scratch.bytes.extend_from_slice(&value.to_le_bytes());
    }
    w.write_bin(&scratch.bytes);
}

pub(crate) fn write_number_scratch_int8_bin(w: &mut MessagePackWriter, offset: u32, count: u32) {
    let numbers = snapshot_encode_number_scratch();
    let scratch = snapshot_encode_packed_static_scratch();
    let start = offset as usize;
    let n = count as usize;
    scratch.bytes.clear();
    scratch.bytes.reserve(n);
    for i in 0..n {
        scratch
            .bytes
            .push(numbers.buf.get(start + i).copied().unwrap_or(0.0) as i8 as u8);
    }
    w.write_bin(&scratch.bytes);
}

pub(crate) fn write_triangle_index_delta_bin(w: &mut MessagePackWriter, offset: u32, count: u32) {
    let numbers = snapshot_encode_number_scratch();
    let scratch = snapshot_encode_packed_static_scratch();
    let start = offset as usize;
    let triangle_count = (count as usize) / 3;
    scratch.bytes.clear();
    scratch.bytes.reserve(1 + triangle_count * 4);
    packed_static_write_var_uint(&mut scratch.bytes, triangle_count as u64);

    let mut previous_base = 0.0;
    for tri in 0..triangle_count {
        let base = start + tri * 3;
        let a = numbers.buf.get(base).copied().unwrap_or(0.0);
        let b = numbers.buf.get(base + 1).copied().unwrap_or(0.0);
        let c = numbers.buf.get(base + 2).copied().unwrap_or(0.0);
        packed_static_write_var_int(&mut scratch.bytes, a - previous_base);
        packed_static_write_var_int(&mut scratch.bytes, b - a);
        packed_static_write_var_int(&mut scratch.bytes, c - a);
        previous_base = a;
    }

    w.write_bin(&scratch.bytes);
}

#[inline]
pub(crate) fn number_scratch_i32(index: usize) -> i32 {
    snapshot_encode_number_scratch()
        .buf
        .get(index)
        .copied()
        .unwrap_or(0.0) as i32
}

pub(crate) fn buildability_run_count(
    flags_offset: u32,
    flags_count: u32,
    levels_offset: u32,
    levels_count: u32,
) -> usize {
    let count = (flags_count as usize).min(levels_count as usize);
    if count == 0 {
        return 0;
    }
    let flags_start = flags_offset as usize;
    let levels_start = levels_offset as usize;
    let mut runs = 0usize;
    let mut i = 0usize;
    while i < count {
        runs += 1;
        let flag = number_scratch_i32(flags_start + i);
        let level = number_scratch_i32(levels_start + i);
        i += 1;
        while i < count
            && number_scratch_i32(flags_start + i) == flag
            && number_scratch_i32(levels_start + i) == level
        {
            i += 1;
        }
    }
    runs
}

#[inline]
pub(crate) fn write_number_array_from_scratch(w: &mut MessagePackWriter, offset: u32, count: u32) {
    let scratch = snapshot_encode_number_scratch();
    let start = offset as usize;
    let n = count as usize;
    w.write_array_header(n);
    for i in 0..n {
        w.write_number(scratch.buf[start + i]);
    }
}

// Scan-pulse scratch — 6 f64 per pulse:
//   [0] playerId   [1] x   [2] y   [3] z
//   [4] radius     [5] expiresAtTick
// Field count is fixed (no optionals on NetworkServerSnapshotScanPulse).
snapshot_scratch_pool!(
    SnapshotEncodeScanPulseScratch,
    SNAPSHOT_ENCODE_SCAN_PULSE_SCRATCH,
    snapshot_encode_scan_pulse_scratch,
    snapshot_encode_scan_pulse_scratch_ptr,
    snapshot_encode_scan_pulse_scratch_ensure,
    f64,
    0.0,
    SNAPSHOT_ENCODE_SCAN_PULSE_STRIDE = 6,
    init 8,
    ensure(count)
);

/// Removed-entity-IDs scratch — Uint32Array of EntityId values for
/// the envelope's removedEntityIds field. JS pre-fills before
/// calling snapshot_encode_envelope_continue with
/// has_removed_entity_ids=1.
pub(crate) struct SnapshotEncodeRemovedIdsScratch {
    buf: Vec<u32>,
}

pub(crate) static SNAPSHOT_ENCODE_REMOVED_IDS_SCRATCH: WasmLazy<SnapshotEncodeRemovedIdsScratch> =
    WasmLazy::new();

#[inline]
pub(crate) fn snapshot_encode_removed_ids_scratch() -> &'static mut SnapshotEncodeRemovedIdsScratch
{
    SNAPSHOT_ENCODE_REMOVED_IDS_SCRATCH.get_or_init(|| SnapshotEncodeRemovedIdsScratch {
        buf: vec![0u32; 16],
    })
}

#[wasm_bindgen]
pub fn snapshot_encode_removed_ids_scratch_ptr() -> *const u32 {
    snapshot_encode_removed_ids_scratch().buf.as_ptr()
}

#[wasm_bindgen]
pub fn snapshot_encode_removed_ids_scratch_ensure(count: u32) {
    let s = snapshot_encode_removed_ids_scratch();
    if s.buf.len() < count as usize {
        s.buf.resize(count as usize, 0);
    }
}

mod entity_wire;

/// Open the envelope: clear writer, emit map header with the
/// caller-computed total_key_count, emit tick key + entities array
/// header. `total_key_count` includes tick + entities + every
/// optional envelope key the caller will subsequently emit (the
/// continue function counts only the ones it's about to write).
#[wasm_bindgen]
pub fn snapshot_encode_envelope_begin(tick: u32, entity_count: u32, total_key_count: u32) {
    let w = messagepack_writer();
    w.buf.clear();
    w.write_map_header(total_key_count as usize);
    w.write_str("tick");
    w.write_uint(tick as u64);
    w.write_str("entities");
    w.write_array_header(entity_count as usize);
}

/// Open the envelope when the `entities` value is already in a compact
/// packed wire shape. The caller must emit the `entities` key next via
/// snapshot_encode_envelope_emit_raw_key_value so key order stays
/// byte-identical with the JS encoder.
#[wasm_bindgen]
pub fn snapshot_encode_envelope_begin_packed_entities(tick: u32, total_key_count: u32) {
    let w = messagepack_writer();
    w.buf.clear();
    w.write_map_header(total_key_count as usize);
    w.write_str("tick");
    w.write_uint(tick as u64);
}

/// Append a top-level snapshot key whose value has already been
/// MessagePack-encoded by a transitional JS fallback. This keeps the
/// envelope writer authoritative for key ordering while DP-02 ports
/// the remaining low-frequency DTO fields.
#[wasm_bindgen]
pub fn snapshot_encode_envelope_emit_raw_key_value(key: &str, value: &[u8]) -> u32 {
    let w = messagepack_writer();
    w.write_str(key);
    w.append_raw_value(value);
    w.buf.len() as u32
}

/// Append the `serverMeta` top-level snapshot key. This mirrors the
/// ServerSnapshotMetaBuilder object-literal insertion order so the
/// Rust envelope remains byte-identical with @msgpack/msgpack while
/// removing one always-present raw fallback from the DP-02 hot path.
#[wasm_bindgen]
pub fn snapshot_encode_envelope_emit_server_meta(
    ticks_avg: f64,
    ticks_low: f64,
    ticks_rate: f64,
    snaps_rate_is_string: u8,
    snaps_rate: f64,
    snaps_rate_slot: u32,
    server_time_slot: u32,
    server_ip_slot: u32,
    has_units_allowed: u8,
    units_allowed_slot_start: u32,
    units_allowed_count: u32,
    has_units_max: u8,
    units_max: f64,
    has_units_count: u8,
    units_count: f64,
    has_turret_shield_panels_enabled: u8,
    turret_shield_panels_enabled: u8,
    has_turret_shield_spheres_enabled: u8,
    turret_shield_spheres_enabled: u8,
    has_force_fields_visible: u8,
    force_fields_visible: u8,
    has_shield_aware_targeting_player_mask: u8,
    shield_aware_targeting_player_mask: u32,
    has_shield_tech_player_mask: u8,
    shield_tech_player_mask: u32,
    has_shield_reflection_mode: u8,
    shield_reflection_mode_slot: u32,
    has_fog_of_war_enabled: u8,
    fog_of_war_enabled: u8,
    cpu_avg: f64,
    cpu_hi: f64,
    wind_x: f64,
    wind_y: f64,
    wind_z: f64,
    wind_speed: f64,
    wind_angle: f64,
    tilt_ema_slot: u32,
) -> u32 {
    let w = messagepack_writer();

    let mut field_count: usize = 7; // ticks, snaps, server, units, cpu, wind, unitGroundNormalEma
    if has_turret_shield_panels_enabled != 0 {
        field_count += 1;
    }
    if has_turret_shield_spheres_enabled != 0 {
        field_count += 1;
    }
    if has_force_fields_visible != 0 {
        field_count += 1;
    }
    if has_shield_aware_targeting_player_mask != 0 {
        field_count += 1;
    }
    if has_shield_tech_player_mask != 0 {
        field_count += 1;
    }
    if has_shield_reflection_mode != 0 {
        field_count += 1;
    }
    if has_fog_of_war_enabled != 0 {
        field_count += 1;
    }

    w.write_str("serverMeta");
    w.write_map_header(field_count);

    w.write_str("ticks");
    w.write_map_header(3);
    w.write_str("avg");
    w.write_number(ticks_avg);
    w.write_str("low");
    w.write_number(ticks_low);
    w.write_str("rate");
    w.write_number(ticks_rate);

    w.write_str("snaps");
    w.write_map_header(1);
    w.write_str("rate");
    if snaps_rate_is_string != 0 {
        write_string_from_scratch(w, snaps_rate_slot);
    } else {
        w.write_number(snaps_rate);
    }

    w.write_str("server");
    w.write_map_header(2);
    w.write_str("time");
    write_string_from_scratch(w, server_time_slot);
    w.write_str("ip");
    write_string_from_scratch(w, server_ip_slot);

    let mut units_field_count: usize = 0;
    if has_units_allowed != 0 {
        units_field_count += 1;
    }
    if has_units_max != 0 {
        units_field_count += 1;
    }
    if has_units_count != 0 {
        units_field_count += 1;
    }
    w.write_str("units");
    w.write_map_header(units_field_count);
    if has_units_allowed != 0 {
        w.write_str("allowed");
        let count = units_allowed_count as usize;
        w.write_array_header(count);
        for i in 0..count {
            write_string_from_scratch(w, units_allowed_slot_start + i as u32);
        }
    }
    if has_units_max != 0 {
        w.write_str("max");
        w.write_number(units_max);
    }
    if has_units_count != 0 {
        w.write_str("count");
        w.write_number(units_count);
    }

    if has_turret_shield_panels_enabled != 0 {
        w.write_str("mirrorsEnabled");
        w.write_bool(turret_shield_panels_enabled != 0);
    }
    if has_turret_shield_spheres_enabled != 0 {
        w.write_str("shieldsEnabled");
        w.write_bool(turret_shield_spheres_enabled != 0);
    }
    if has_force_fields_visible != 0 {
        w.write_str("forceFieldsVisible");
        w.write_bool(force_fields_visible != 0);
    }
    if has_shield_aware_targeting_player_mask != 0 {
        w.write_str("shieldAwareTargetingPlayerMask");
        w.write_uint(shield_aware_targeting_player_mask as u64);
    }
    if has_shield_tech_player_mask != 0 {
        w.write_str("shieldTechPlayerMask");
        w.write_uint(shield_tech_player_mask as u64);
    }
    if has_shield_reflection_mode != 0 {
        w.write_str("shieldReflectionMode");
        write_string_from_scratch(w, shield_reflection_mode_slot);
    }
    if has_fog_of_war_enabled != 0 {
        w.write_str("fogOfWarEnabled");
        w.write_bool(fog_of_war_enabled != 0);
    }

    w.write_str("cpu");
    w.write_map_header(2);
    w.write_str("avg");
    w.write_number(cpu_avg);
    w.write_str("hi");
    w.write_number(cpu_hi);

    w.write_str("wind");
    w.write_map_header(5);
    w.write_str("x");
    w.write_number(wind_x);
    w.write_str("y");
    w.write_number(wind_y);
    w.write_str("z");
    w.write_number(wind_z);
    w.write_str("speed");
    w.write_number(wind_speed);
    w.write_str("angle");
    w.write_number(wind_angle);

    w.write_str("unitGroundNormalEma");
    write_string_from_scratch(w, tilt_ema_slot);

    w.buf.len() as u32
}

mod envelope_emit;

/// Append `sprayTargets: [...]`. Sits between economy and projectiles
/// in iteration order (sprayTargets is in the _snapshotBuf static
/// init). Reads `count` entries (17 f64 each) from the spray scratch.
#[wasm_bindgen]
pub fn snapshot_encode_envelope_emit_spray_targets(count: u32) -> u32 {
    let w = messagepack_writer();
    let n = count as usize;
    let scratch = snapshot_encode_spray_scratch();
    w.write_str("sprayTargets");
    w.write_array_header(n);
    for i in 0..n {
        let base = i * SNAPSHOT_ENCODE_SPRAY_STRIDE;
        let flags = scratch.buf[base + 16] as u32;
        let type_is_heal = (flags & 0x01) != 0;
        let has_source_z = (flags & 0x02) != 0;
        let has_target_z = (flags & 0x04) != 0;
        let has_target_dim = (flags & 0x08) != 0;
        let has_target_radius = (flags & 0x10) != 0;
        let has_speed = (flags & 0x20) != 0;
        let has_particle_radius = (flags & 0x40) != 0;
        let has_ball_spawn_rate = (flags & 0x80) != 0;
        let inverse = (flags & 0x100) != 0;

        // Outer field count: source, target, type, intensity always +
        // optional speed + particleRadius + ballSpawnRate.
        let mut field_count: usize = 4;
        if has_speed {
            field_count += 1;
        }
        if has_particle_radius {
            field_count += 1;
        }
        if has_ball_spawn_rate {
            field_count += 1;
        }
        if inverse {
            field_count += 1;
        }
        w.write_map_header(field_count);

        // source: { id, pos: {x, y}, [z], playerId } in pool order.
        w.write_str("source");
        let src_field_count = if has_source_z { 4 } else { 3 };
        w.write_map_header(src_field_count);
        w.write_str("id");
        w.write_uint(scratch.buf[base] as u64);
        w.write_str("pos");
        w.write_map_header(2);
        w.write_str("x");
        w.write_number(scratch.buf[base + 1]);
        w.write_str("y");
        w.write_number(scratch.buf[base + 2]);
        if has_source_z {
            w.write_str("z");
            w.write_number(scratch.buf[base + 3]);
        }
        w.write_str("playerId");
        w.write_uint(scratch.buf[base + 4] as u64);

        // target: { id, pos: {x, y}, [z], [dim], [radius] } in pool order.
        w.write_str("target");
        let mut tgt_field_count: usize = 2;
        if has_target_z {
            tgt_field_count += 1;
        }
        if has_target_dim {
            tgt_field_count += 1;
        }
        if has_target_radius {
            tgt_field_count += 1;
        }
        w.write_map_header(tgt_field_count);
        w.write_str("id");
        w.write_uint(scratch.buf[base + 5] as u64);
        w.write_str("pos");
        w.write_map_header(2);
        w.write_str("x");
        w.write_number(scratch.buf[base + 6]);
        w.write_str("y");
        w.write_number(scratch.buf[base + 7]);
        if has_target_z {
            w.write_str("z");
            w.write_number(scratch.buf[base + 8]);
        }
        if has_target_dim {
            w.write_str("dim");
            w.write_map_header(2);
            w.write_str("x");
            w.write_number(scratch.buf[base + 9]);
            w.write_str("y");
            w.write_number(scratch.buf[base + 10]);
        }
        if has_target_radius {
            w.write_str("radius");
            w.write_number(scratch.buf[base + 11]);
        }

        w.write_str("type");
        if type_is_heal {
            w.write_str("heal");
        } else {
            w.write_str("build");
        }
        if inverse {
            w.write_str("inverse");
            w.write_bool(true);
        }
        w.write_str("intensity");
        w.write_number(scratch.buf[base + 12]);
        if has_speed {
            w.write_str("speed");
            w.write_number(scratch.buf[base + 13]);
        }
        if has_particle_radius {
            w.write_str("particleRadius");
            w.write_number(scratch.buf[base + 14]);
        }
        if has_ball_spawn_rate {
            w.write_str("ballSpawnRate");
            w.write_number(scratch.buf[base + 15]);
        }
    }
    w.buf.len() as u32
}

/// Close the envelope. Emits the post-projectiles optional keys in
/// stateSerializer.ts pool-insertion order: gameState,
/// removedEntityIds, visibilityFiltered. Caller flags gate which
/// appear; map-header count in _begin must match.
#[wasm_bindgen]
pub fn snapshot_encode_envelope_continue(
    has_game_state: u8,
    game_state_phase_slot: u32,
    has_winner_id: u8,
    winner_id: u8,
    has_removed_entity_ids: u8,
    removed_entity_id_count: u32,
    has_visibility_filtered: u8,
    visibility_filtered: u8,
) -> u32 {
    let w = messagepack_writer();
    if has_game_state != 0 {
        w.write_str("gameState");
        let gs_field_count = if has_winner_id != 0 { 2 } else { 1 };
        w.write_map_header(gs_field_count);
        w.write_str("phase");
        write_string_from_scratch(w, game_state_phase_slot);
        if has_winner_id != 0 {
            w.write_str("winnerId");
            w.write_uint(winner_id as u64);
        }
    }
    if has_removed_entity_ids != 0 {
        let count = removed_entity_id_count as usize;
        let scratch = snapshot_encode_removed_ids_scratch();
        w.write_str("removedEntityIds");
        w.write_array_header(count);
        for i in 0..count {
            w.write_uint(scratch.buf[i] as u64);
        }
    }
    if has_visibility_filtered != 0 {
        w.write_str("visibilityFiltered");
        w.write_bool(visibility_filtered != 0);
    }
    w.buf.len() as u32
}

/// Append compact `terrain: { v: 5, m, vc, vh, ti, tw }` from raw
/// TerrainTileMap arrays already copied into number scratch. This
/// mirrors snapshotStaticWirePack.ts without running its large JS
/// packing loops on the Rust send path.
#[wasm_bindgen]
pub fn snapshot_encode_envelope_emit_packed_terrain(
    map_width: f64,
    map_height: f64,
    cell_size: f64,
    subdiv: f64,
    cells_x: f64,
    cells_y: f64,
    vertices_x: f64,
    vertices_y: f64,
    version: f64,
    mesh_vertex_coords_offset: u32,
    mesh_vertex_coords_count: u32,
    mesh_vertex_heights_offset: u32,
    mesh_vertex_heights_count: u32,
    mesh_triangle_indices_offset: u32,
    mesh_triangle_indices_count: u32,
    mesh_triangle_wall_flags_offset: u32,
    mesh_triangle_wall_flags_count: u32,
) -> u32 {
    const PACKED_TERRAIN_VERSION: u64 = 5;
    const TERRAIN_TRIANGLE_INDICES_DELTA: f64 = 4.0;

    let w = messagepack_writer();
    w.write_str("terrain");
    w.write_map_header(6);

    w.write_str("v");
    w.write_uint(PACKED_TERRAIN_VERSION);

    w.write_str("m");
    w.write_array_header(10);
    w.write_number(map_width);
    w.write_number(map_height);
    w.write_number(cell_size);
    w.write_number(subdiv);
    w.write_number(cells_x);
    w.write_number(cells_y);
    w.write_number(vertices_x);
    w.write_number(vertices_y);
    w.write_number(version);
    w.write_number(TERRAIN_TRIANGLE_INDICES_DELTA);

    w.write_str("vc");
    write_number_scratch_float32_bin(w, mesh_vertex_coords_offset, mesh_vertex_coords_count);

    w.write_str("vh");
    write_number_scratch_float32_bin(w, mesh_vertex_heights_offset, mesh_vertex_heights_count);

    w.write_str("ti");
    write_triangle_index_delta_bin(w, mesh_triangle_indices_offset, mesh_triangle_indices_count);

    w.write_str("tw");
    write_number_scratch_int8_bin(
        w,
        mesh_triangle_wall_flags_offset,
        mesh_triangle_wall_flags_count,
    );

    w.buf.len() as u32
}

/// Append the static `terrain` top-level snapshot key. Full snapshots
/// use this to ship the authoritative TerrainTileMap without falling
/// back to JS object MessagePack encoding.
#[wasm_bindgen]
pub fn snapshot_encode_envelope_emit_terrain(
    map_width: f64,
    map_height: f64,
    cell_size: f64,
    subdiv: f64,
    cells_x: f64,
    cells_y: f64,
    vertices_x: f64,
    vertices_y: f64,
    version: f64,
    mesh_vertex_coords_offset: u32,
    mesh_vertex_coords_count: u32,
    mesh_vertex_heights_offset: u32,
    mesh_vertex_heights_count: u32,
    mesh_triangle_indices_offset: u32,
    mesh_triangle_indices_count: u32,
    mesh_triangle_levels_offset: u32,
    mesh_triangle_levels_count: u32,
    mesh_triangle_wall_flags_offset: u32,
    mesh_triangle_wall_flags_count: u32,
    mesh_triangle_neighbor_indices_offset: u32,
    mesh_triangle_neighbor_indices_count: u32,
    mesh_triangle_neighbor_levels_offset: u32,
    mesh_triangle_neighbor_levels_count: u32,
    mesh_cell_triangle_offsets_offset: u32,
    mesh_cell_triangle_offsets_count: u32,
    mesh_cell_triangle_indices_offset: u32,
    mesh_cell_triangle_indices_count: u32,
) -> u32 {
    let w = messagepack_writer();
    w.write_str("terrain");
    w.write_map_header(18);

    w.write_str("mapWidth");
    w.write_number(map_width);
    w.write_str("mapHeight");
    w.write_number(map_height);
    w.write_str("cellSize");
    w.write_number(cell_size);
    w.write_str("subdiv");
    w.write_number(subdiv);
    w.write_str("cellsX");
    w.write_number(cells_x);
    w.write_str("cellsY");
    w.write_number(cells_y);
    w.write_str("verticesX");
    w.write_number(vertices_x);
    w.write_str("verticesY");
    w.write_number(vertices_y);
    w.write_str("version");
    w.write_number(version);

    w.write_str("meshVertexCoords");
    write_number_array_from_scratch(w, mesh_vertex_coords_offset, mesh_vertex_coords_count);
    w.write_str("meshVertexHeights");
    write_number_array_from_scratch(w, mesh_vertex_heights_offset, mesh_vertex_heights_count);
    w.write_str("meshTriangleIndices");
    write_number_array_from_scratch(w, mesh_triangle_indices_offset, mesh_triangle_indices_count);
    w.write_str("meshTriangleLevels");
    write_number_array_from_scratch(w, mesh_triangle_levels_offset, mesh_triangle_levels_count);
    w.write_str("meshTriangleWallFlags");
    write_number_array_from_scratch(
        w,
        mesh_triangle_wall_flags_offset,
        mesh_triangle_wall_flags_count,
    );
    w.write_str("meshTriangleNeighborIndices");
    write_number_array_from_scratch(
        w,
        mesh_triangle_neighbor_indices_offset,
        mesh_triangle_neighbor_indices_count,
    );
    w.write_str("meshTriangleNeighborLevels");
    write_number_array_from_scratch(
        w,
        mesh_triangle_neighbor_levels_offset,
        mesh_triangle_neighbor_levels_count,
    );
    w.write_str("meshCellTriangleOffsets");
    write_number_array_from_scratch(
        w,
        mesh_cell_triangle_offsets_offset,
        mesh_cell_triangle_offsets_count,
    );
    w.write_str("meshCellTriangleIndices");
    write_number_array_from_scratch(
        w,
        mesh_cell_triangle_indices_offset,
        mesh_cell_triangle_indices_count,
    );

    w.buf.len() as u32
}

/// Append compact `buildability: { v: 1, m, k, r }` from raw
/// TerrainBuildabilityGrid flags/levels copied into number scratch.
#[wasm_bindgen]
pub fn snapshot_encode_envelope_emit_packed_buildability(
    map_width: f64,
    map_height: f64,
    cell_size: f64,
    cells_x: f64,
    cells_y: f64,
    version: f64,
    config_key_slot: u32,
    flags_offset: u32,
    flags_count: u32,
    levels_offset: u32,
    levels_count: u32,
) -> u32 {
    let w = messagepack_writer();
    w.write_str("buildability");
    w.write_map_header(4);

    w.write_str("v");
    w.write_uint(1);

    w.write_str("m");
    w.write_array_header(6);
    w.write_number(map_width);
    w.write_number(map_height);
    w.write_number(cell_size);
    w.write_number(cells_x);
    w.write_number(cells_y);
    w.write_number(version);

    w.write_str("k");
    write_string_from_scratch(w, config_key_slot);

    w.write_str("r");
    let count = (flags_count as usize).min(levels_count as usize);
    let flags_start = flags_offset as usize;
    let levels_start = levels_offset as usize;
    let run_count = buildability_run_count(flags_offset, flags_count, levels_offset, levels_count);
    w.write_array_header(run_count * 3);

    let mut i = 0usize;
    while i < count {
        let flag = number_scratch_i32(flags_start + i);
        let level = number_scratch_i32(levels_start + i);
        let mut run_length = 1usize;
        i += 1;
        while i < count
            && number_scratch_i32(flags_start + i) == flag
            && number_scratch_i32(levels_start + i) == level
        {
            run_length += 1;
            i += 1;
        }
        w.write_number(run_length as f64);
        w.write_number(flag as f64);
        w.write_number(level as f64);
    }

    w.buf.len() as u32
}

/// Append the static `buildability` top-level snapshot key. The
/// configKey string is read from string scratch; flags/levels are read
/// from the shared numeric scratch as JS-number arrays so MessagePack
/// integer/float selection stays byte-identical with @msgpack/msgpack.
#[wasm_bindgen]
pub fn snapshot_encode_envelope_emit_buildability(
    map_width: f64,
    map_height: f64,
    cell_size: f64,
    cells_x: f64,
    cells_y: f64,
    version: f64,
    config_key_slot: u32,
    flags_offset: u32,
    flags_count: u32,
    levels_offset: u32,
    levels_count: u32,
) -> u32 {
    let w = messagepack_writer();
    w.write_str("buildability");
    w.write_map_header(9);

    w.write_str("mapWidth");
    w.write_number(map_width);
    w.write_str("mapHeight");
    w.write_number(map_height);
    w.write_str("cellSize");
    w.write_number(cell_size);
    w.write_str("cellsX");
    w.write_number(cells_x);
    w.write_str("cellsY");
    w.write_number(cells_y);
    w.write_str("version");
    w.write_number(version);
    w.write_str("configKey");
    write_string_from_scratch(w, config_key_slot);
    w.write_str("flags");
    write_number_array_from_scratch(w, flags_offset, flags_count);
    w.write_str("levels");
    write_number_array_from_scratch(w, levels_offset, levels_count);

    w.buf.len() as u32
}

/// Write `value` in base-10 ASCII into the END of `buf`, return the
/// &str slice covering the digits. Avoids std::fmt allocation in WASM.
#[inline]
pub(crate) fn u32_to_decimal<'a>(buf: &'a mut [u8; 12], mut value: u32) -> &'a str {
    if value == 0 {
        buf[11] = b'0';
        return core::str::from_utf8(&buf[11..12]).unwrap();
    }
    let mut idx = 12;
    while value > 0 {
        idx -= 1;
        buf[idx] = b'0' + (value % 10) as u8;
        value /= 10;
    }
    core::str::from_utf8(&buf[idx..12]).unwrap()
}

/// Append the scanPulses array. Sits AFTER visibilityFiltered in
/// pool-insertion order because scanPulses is added to _snapshotBuf
/// (stateSerializer.ts) lazily on its first non-undefined assignment,
/// not in the static init — so its property slot lands at the end of
/// the iteration order. Reads `count` entries (6 f64 each) from the
/// scan-pulse scratch.
#[wasm_bindgen]
pub fn snapshot_encode_envelope_emit_scan_pulses(count: u32) -> u32 {
    let w = messagepack_writer();
    let n = count as usize;
    let scratch = snapshot_encode_scan_pulse_scratch();
    w.write_str("scanPulses");
    w.write_array_header(n);
    for i in 0..n {
        let base = i * SNAPSHOT_ENCODE_SCAN_PULSE_STRIDE;
        let player_id = scratch.buf[base] as u32;
        let x = scratch.buf[base + 1];
        let y = scratch.buf[base + 2];
        let z = scratch.buf[base + 3];
        let radius = scratch.buf[base + 4];
        let expires_at_tick = scratch.buf[base + 5] as u32;

        // Pool order from createScanPulseDto: playerId, x, y, z,
        // radius, expiresAtTick. All 6 fields always present.
        w.write_map_header(6);
        w.write_str("playerId");
        w.write_uint(player_id as u64);
        w.write_str("x");
        w.write_number(x);
        w.write_str("y");
        w.write_number(y);
        w.write_str("z");
        w.write_number(z);
        w.write_str("radius");
        w.write_number(radius);
        w.write_str("expiresAtTick");
        w.write_uint(expires_at_tick as u64);
    }
    w.buf.len() as u32
}

// Shared across all test modules: the combat-targeting pool is a process-global
// static, so every test that stamps or reads it must serialize on ONE lock
// regardless of which test module it lives in.
#[cfg(test)]
pub(crate) static COMBAT_TARGETING_TEST_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

#[cfg(test)]
mod tests;
