/**
 * Weapon Blueprints
 *
 * Static data for all weapon types.
 * Merges WEAPON_STATS + turret visuals + audio from config.ts and audioConfig.ts.
 */

import { SPATIAL_GRID_CELL_SIZE, FORCE_FIELD_TURRET } from '../../../config';
import type { WeaponBlueprint } from './types';

export const TURRET_BLUEPRINTS: Record<string, WeaponBlueprint> = {
  gatlingTurret: {
    id: 'gatlingTurret',
    projectileId: 'lightShot',
    range: 100,
    cooldown: 400,
    spreadAngle: Math.PI / 12,
    turretTurnAccel: 200,
    turretDrag: 0.5,
    turret: { type: 'single', barrelLength: 1.2, barrelThickness: 2 },
    rangeMultiplierOverrides: {
      see: null,
      fire: null,
      release: null,
      lock: null,
      fightstop: null,
    },
    color: 0xffffff,
    fireSound: { synth: 'burst-rifle', volume: 0.2, playSpeed: 0.5 },
  },
  pulseTurret: {
    id: 'pulseTurret',
    projectileId: 'heavyShot',
    range: 160,
    cooldown: 1800,
    burstCount: 2,
    burstDelay: 80,
    spreadAngle: Math.PI / 32,
    turretTurnAccel: 40,
    turretDrag: 0.15,
    turret: {
      type: 'multibarrel',
      barrelCount: 2,
      barrelLength: 1.7,
      barrelThickness: 4,
      orbitRadius: 0.35,
      depthScale: 0.1,
      spin: { idle: 2.0, max: 30, accel: 80, decel: 30 },
    },
    rangeMultiplierOverrides: {
      see: null,
      fire: null,
      release: null,
      lock: null,
      fightstop: null,
    },
    color: 0xffffff,
    fireSound: { synth: 'burst-rifle', volume: 0.2, playSpeed: 0.3 },
  },
  shotgunTurret: {
    id: 'shotgunTurret',
    projectileId: 'heavyShot',
    range: 160,
    cooldown: 1500,
    pelletCount: 4,
    spreadAngle: Math.PI / 1.4,
    homingTurnRate: 3,
    turretTurnAccel: 5,
    turretDrag: 0.15,
    turret: {
      type: 'coneSpread',
      barrelCount: 5,
      barrelLength: 0.6,
      barrelThickness: 2,
      baseOrbit: 0.094,
      depthScale: 0.12,
      spin: { idle: 0.7, max: 2, accel: 80, decel: 30 },
    },
    rangeMultiplierOverrides: {
      see: 1,
      fire: 0.9,
      release: 1,
      lock: 0.9,
      fightstop: 0.8,
    },
    color: 0xffffff,
    fireSound: { synth: 'burst-rifle', volume: 0.4, playSpeed: 0.2 },
  },
  mortarTurret: {
    id: 'mortarTurret',
    projectileId: 'mortarShot',
    range: 400,
    cooldown: 6000,
    spreadAngle: Math.PI / 24,
    turretTurnAccel: 40,
    turretDrag: 0.4,
    turret: { type: 'single', barrelLength: 0.75, barrelThickness: 6 },
    rangeMultiplierOverrides: {
      see: null,
      fire: null,
      release: null,
      lock: null,
      fightstop: null,
    },
    color: 0xffffff,
    fireSound: { synth: 'cannon', volume: 0.2, playSpeed: 1.0 },
  },
  cannonTurret: {
    id: 'cannonTurret',
    projectileId: 'cannonShot',
    range: 360,
    cooldown: 3000,
    spreadAngle: Math.PI / 24,
    turretTurnAccel: 200,
    turretDrag: 0.5,
    turret: { type: 'single', barrelLength: 1.4, barrelThickness: 7 },
    rangeMultiplierOverrides: {
      see: null,
      fire: null,
      release: null,
      lock: null,
      fightstop: null,
    },
    color: 0xffffff,
    fireSound: { synth: 'cannon', volume: 0.2, playSpeed: 0.8 },
  },
  laserTurret: {
    id: 'laserTurret',
    projectileId: 'laserShot',
    range: 100,
    cooldown: 1500,
    // cooldown: 3000,
    spreadAngle: 0,
    turretTurnAccel: 100,
    turretDrag: 0.6,
    turret: { type: 'single', barrelLength: 1.0, barrelThickness: 2 },
    rangeMultiplierOverrides: {
      see: null,
      fire: 0.9,
      release: null,
      lock: null,
      fightstop: 0.7,
    },
    color: 0xffffff,
    fireSound: { synth: 'laserGun', volume: 0.03, playSpeed: 0.6 },
  },
  beamTurret: {
    id: 'beamTurret',
    projectileId: 'beamShot',
    range: 150,
    turretTurnAccel: 100,
    turretDrag: 0.4,
    turret: { type: 'beamEmitter', barrelLength: 0.6, barrelThickness: 3.5 },
    rangeMultiplierOverrides: {
      see: null,
      fire: null,
      release: null,
      lock: null,
      fightstop: null,
    },
    color: 0xffffff,
    fireSound: { synth: 'laser-zap', volume: 0.2, playSpeed: 1.0 },
    laserSound: { synth: 'beam-hum', volume: 1.0, playSpeed: 1.0 },
  },
  forceTurret: {
    id: 'forceTurret',
    range: SPATIAL_GRID_CELL_SIZE * 1.9,
    turretTurnAccel: 30,
    turretDrag: 0.5,
    isForceField: true,
    forceFieldAngle: Math.PI * 2,
    forceFieldTransitionTime: 500,
    turret: { type: 'forceField', grate: FORCE_FIELD_TURRET.forceField },
    push: {
      innerRatio: 0.0,
      outerRatio: 0.8,
      color: 0x3366ff,
      alpha: 0.05,
      particleAlpha: 0.2,
      power: 300,
      damage: 0,
    },
    pull: {
      innerRatio: 0.8,
      outerRatio: 0.82,
      color: 0x3366ff,
      alpha: 0.2,
      particleAlpha: 0.2,
      power: null,
      damage: 0,
    },
    rangeMultiplierOverrides: {
      see: null,
      fire: null,
      release: null,
      lock: null,
      fightstop: 1.5,
    },
    color: 0xffffff,
    fireSound: { synth: 'force-field', volume: 0.5, playSpeed: 1.0 },
  },
  megaForceTurret: {
    id: 'megaForceTurret',
    range: SPATIAL_GRID_CELL_SIZE * 1.3,
    turretTurnAccel: 30,
    turretDrag: 0.5,
    isForceField: true,
    forceFieldAngle: Math.PI * 2,
    forceFieldTransitionTime: 500,
    turret: { type: 'forceField', grate: FORCE_FIELD_TURRET.megaForceField },
    push: {
      innerRatio: 0.0,
      outerRatio: 0.5,
      color: 0x3366ff,
      alpha: 0.05,
      particleAlpha: 0.2,
      power: 300,
      damage: 0,
    },
    pull: {
      innerRatio: 0.5,
      outerRatio: 0.52,
      color: 0x3366ff,
      alpha: 0.2,
      particleAlpha: 0.2,
      power: null,
      damage: 0,
    },
    rangeMultiplierOverrides: {
      see: null,
      fire: null,
      release: null,
      lock: null,
      fightstop: 1.5,
    },
    color: 0xffffff,
    fireSound: { synth: 'force-field', volume: 0.5, playSpeed: 2.0 },
  },
  disruptorTurret: {
    id: 'disruptorTurret',
    projectileId: 'disruptorShot',
    range: 150,
    cooldown: 0,
    turretTurnAccel: 40,
    turretDrag: 0.15,
    turret: { type: 'beamEmitter', barrelLength: 0.7, barrelThickness: 4 },
    rangeMultiplierOverrides: {
      see: null,
      fire: null,
      release: null,
      lock: null,
      fightstop: null,
    },
    color: 0xff8800,
    fireSound: { synth: 'cannon', volume: 0.2, playSpeed: 1.0 },
  },
  dgunTurret: {
    id: 'dgunTurret',
    projectileId: 'disruptorShot',
    range: 150,
    cooldown: 0,
    turretTurnAccel: 40,
    turretDrag: 0.15,
    turret: { type: 'beamEmitter', barrelLength: 0.7, barrelThickness: 4 },
    rangeMultiplierOverrides: {
      see: null,
      fire: null,
      release: null,
      lock: null,
      fightstop: null,
    },
    isManualFire: true,
    color: 0xff8800,
    fireSound: { synth: 'cannon', volume: 0.2, playSpeed: 1.0 },
  },
};

export function getTurretBlueprint(id: string): WeaponBlueprint {
  const bp = TURRET_BLUEPRINTS[id];
  if (!bp) throw new Error(`Unknown weapon blueprint: ${id}`);
  return bp;
}
