/**
 * Per-preset sky backdrop panoramas.
 *
 * Mirrors how Beyond All Reason applies map skyboxes (a far-visual sky
 * texture swapped per biome via Spring.SetSkyBoxTexture), extended into
 * four map-centered parallax shells. Each stock battle preset maps to a
 * coordinated near/middle/far/terminal UASTC KTX2 set generated by
 * scripts/generate_backdrops.py from the colorsConfig palette. The first
 * three layers have transparent skies; terminal is fully opaque.
 */

/** Preset display names (battlePresets.ts) -> generated panorama slug. */
const PRESET_BACKDROP_SLUGS: Readonly<Record<string, string>> = {
  'Large Circle': 'large-circle',
  'Angels Flat': 'angels-flat',
  'Boulder Mountain': 'boulder-mountain',
  'Spikey Lake': 'spikey-lake',
  'Niemo Islands': 'niemo-islands',
  'Angels Playhouse': 'angels-playhouse',
  'METAL HELL': 'metal-hell',
  'METAL PLATE': 'metal-plate',
};

export const PRESET_BACKDROP_LAYER_IDS = [
  'near',
  'middle',
  'far',
  'terminal',
] as const;

export type PresetBackdropLayerId = typeof PRESET_BACKDROP_LAYER_IDS[number];
export type PresetBackdropLayerUrls = readonly [string, string, string, string];

export function backdropUrlsForPresetName(
  name: string | null,
): PresetBackdropLayerUrls | null {
  if (!name) return null;
  const slug = PRESET_BACKDROP_SLUGS[name];
  if (!slug) return null;
  const root = `${import.meta.env.BASE_URL}assets/backdrops/${slug}`;
  return [
    `${root}-near.ktx2`,
    `${root}-middle.ktx2`,
    `${root}-far.ktx2`,
    `${root}-terminal.ktx2`,
  ];
}

export type BackdropTarget = {
  setBackdropLayerUrls(urls: PresetBackdropLayerUrls | null): void;
};

const targets = new Set<BackdropTarget>();
let activeUrls: PresetBackdropLayerUrls | null = null;

/** Called by ThreeApp on construction; the returned function must be
 *  called from destroy(). The current backdrop is applied immediately so
 *  instances created mid-session (battle restarts, lobby preview) pick
 *  it up without waiting for the next preset change. */
export function registerBackdropTarget(target: BackdropTarget): () => void {
  targets.add(target);
  target.setBackdropLayerUrls(activeUrls);
  return () => {
    targets.delete(target);
  };
}

/** Reactive entry point: GameCanvas feeds the battle bar's matched
 *  preset name (null when the current settings match no stock preset). */
export function setActiveBackdropPresetName(name: string | null): void {
  const urls = backdropUrlsForPresetName(name);
  if (urls?.[0] === activeUrls?.[0]) return;
  activeUrls = urls;
  for (const target of targets) target.setBackdropLayerUrls(urls);
}
