/**
 * Per-preset sky backdrop panoramas.
 *
 * Mirrors how Beyond All Reason applies map skyboxes (a far-visual sky
 * texture swapped per biome via Spring.SetSkyBoxTexture): each stock
 * battle preset maps to an equirectangular panorama generated by
 * scripts/generate_backdrops.py from the colorsConfig palette. ThreeApp
 * registers itself here and receives the URL for whatever preset the
 * battle bar currently matches; when the settings drift off every stock
 * preset the URL goes null and ThreeApp falls back to the plain
 * sky-gradient backdrop colors.
 */

/** Preset display names (battlePresets.ts) -> generated panorama slug. */
const PRESET_BACKDROP_SLUGS: Readonly<Record<string, string>> = {
  'Large Circle': 'large-circle',
  'Angels Flat': 'angels-flat',
  'Boulder Mountain': 'boulder-mountain',
  'Spikey Lake': 'spikey-lake',
  'Niemo Islands': 'niemo-islands',
  'Angels Playhouse': 'angels-playhouse',
  'METAL HELL': 'metal-hell',
  'METAL PLATE': 'metal-plate',
};

export function backdropUrlForPresetName(name: string | null): string | null {
  if (!name) return null;
  const slug = PRESET_BACKDROP_SLUGS[name];
  if (!slug) return null;
  return `${import.meta.env.BASE_URL}assets/backdrops/${slug}.png`;
}

export type BackdropTarget = {
  setBackdropUrl(url: string | null): void;
};

const targets = new Set<BackdropTarget>();
let activeUrl: string | null = null;

/** Called by ThreeApp on construction; the returned function must be
 *  called from destroy(). The current backdrop is applied immediately so
 *  instances created mid-session (battle restarts, lobby preview) pick
 *  it up without waiting for the next preset change. */
export function registerBackdropTarget(target: BackdropTarget): () => void {
  targets.add(target);
  target.setBackdropUrl(activeUrl);
  return () => {
    targets.delete(target);
  };
}

/** Reactive entry point: GameCanvas feeds the battle bar's matched
 *  preset name (null when the current settings match no stock preset). */
export function setActiveBackdropPresetName(name: string | null): void {
  const url = backdropUrlForPresetName(name);
  if (url === activeUrl) return;
  activeUrl = url;
  for (const target of targets) target.setBackdropUrl(url);
}
