/**
 * Per-preset sky backdrop panoramas.
 *
 * Mirrors how Beyond All Reason applies map skyboxes (a far-visual sky
 * texture swapped per biome via Spring.SetSkyBoxTexture), extended into
 * four map-centered parallax shells. Each stock battle preset maps to a
 * coordinated near/middle/far/terminal UASTC KTX2 set generated by
 * scripts/generate_backdrops.py from the colorsConfig palette, plus a
 * `default` set for settings that match no preset. The first three layers
 * have transparent skies; terminal is fully opaque.
 */

import { createRenderBroadcastChannel } from './renderBroadcastChannel';
import { BATTLE_PRESETS } from '@/components/battlePresets';

/** Panorama used whenever the battle bar matches no stock preset. Settings
 *  drifted off a preset still deserve a layered horizon, so the fallback is
 *  a real four-layer set (neutral daylight, no preset signature) rather than
 *  the bare gradient sky the renderer shows with no textures bound. */
const DEFAULT_BACKDROP_SLUG = 'default';

export const PRESET_BACKDROP_LAYER_IDS = [
  'near',
  'middle',
  'far',
  'terminal',
] as const;

export type PresetBackdropLayerId = typeof PRESET_BACKDROP_LAYER_IDS[number];
export type PresetBackdropLayerUrls = readonly [string, string, string, string];

/** Always resolves a layer set: unknown / null names fall back to the
 *  generated `default` panorama. */
export function backdropUrlsForPresetName(
  name: string | null,
): PresetBackdropLayerUrls {
  const slug = (name
    ? BATTLE_PRESETS.find((preset) => preset.name === name)?.backdropSlug
    : undefined)
    ?? DEFAULT_BACKDROP_SLUG;
  const root = `${import.meta.env.BASE_URL}assets/backdrops/${slug}`;
  return [
    `${root}-near.ktx2`,
    `${root}-middle.ktx2`,
    `${root}-far.ktx2`,
    `${root}-terminal.ktx2`,
  ];
}

export type BackdropTarget = {
  setBackdropLayerUrls(urls: PresetBackdropLayerUrls): void;
};

// One slug per set, so the near URL identifies the whole layer set.
const channel = createRenderBroadcastChannel<PresetBackdropLayerUrls>(
  backdropUrlsForPresetName(null),
  (a, b) => a[0] === b[0],
);

/** Called by ThreeApp on construction; the returned function must be
 *  called from destroy(). The current backdrop is applied immediately so
 *  instances created mid-session (battle restarts, lobby preview) pick
 *  it up without waiting for the next preset change. */
export function registerBackdropTarget(target: BackdropTarget): () => void {
  return channel.register((urls) => target.setBackdropLayerUrls(urls));
}

/** Reactive entry point: GameCanvas feeds the battle bar's matched
 *  preset name (null when the current settings match no stock preset,
 *  which resolves to the default panorama). */
export function setActiveBackdropPresetName(name: string | null): void {
  channel.set(backdropUrlsForPresetName(name));
}
