// Generated by scripts/generateBlueprintSchemaTypes.mjs from src/game/sim/blueprints/blueprintSchema.json.
// Do not edit this file directly.
import type { SoundEntry } from './audio';
import type { RayBlueprintId, ShieldBlueprintId, ShieldMaterialId, ShotBlueprintId, TurretBlueprintId, UnitBlueprintId } from './blueprintIds';
import type { TurretRangeOverrides } from './combatTypes';
import type { BarrelShape } from './config';
import type { ConstructionEmitterSize, ConstructionEmitterVisualSpec } from './constructionTypes';
import type { ResourceCost } from './economyTypes';
import type { EntityId, PlayerId } from './entityTypes';
import type { UnitSuspensionConfig } from './locomotionTypes';

export type TurretRangeVolume = 'turret-range-cylinder-normal' | 'turret-range-bottom-unbounded' | 'turret-range-top-and-bottom-unbounded' | 'turret-range-sphere';

export type ProjectileShotKind = 'plasma' | 'rocket';

export type ShieldSurfaceResponse = 'reflect' | 'absorb' | 'passThrough';

export type ShieldReflectionMode = 'outside-in' | 'inside-out' | 'both';

export type ShieldBarrierShape = 'sphere' | 'infiniteVerticalCylinder';

export type ShieldBarrierRatioConfig = {
  shape: ShieldBarrierShape;
  outerRatio?: number | null;
  rimWidth?: number | null;
  originOffsetRadiusRatio?: number | null;
};

export type ShieldMaterialVisualConfig = {
  color: number;
  alpha: number;
  particleAlpha: number;
};

export type ShieldMaterialReflectionConfig = {
  mode: ShieldReflectionMode;
  reflectivity: number;
};

export type ShieldMaterialOcclusionConfig = {
  blocksLineOfSight: boolean;
};

export type ShieldMaterialProjectileResponseConfig = {
  plasma: ShieldSurfaceResponse;
  rocket: ShieldSurfaceResponse;
  beam: ShieldSurfaceResponse;
  laser: ShieldSurfaceResponse;
};

export type ShieldMaterialHitReactionConfig = {
  impactEvent: 'shieldImpact';
  sound: SoundEntry | null;
};

export type ShieldMaterialBlueprint = {
  materialId: ShieldMaterialId;
  reflection: ShieldMaterialReflectionConfig;
  occlusion: ShieldMaterialOcclusionConfig;
  projectileResponse: ShieldMaterialProjectileResponseConfig;
  hitReaction: ShieldMaterialHitReactionConfig;
  visual: ShieldMaterialVisualConfig;
};

export type ShotCollision = {
  radius: number;
};

export type ShotExplosion = {
  radius: number;
  damage: number;
  force: number;
};

export type SubmunitionSpec = {
  shotBlueprintId: ShotBlueprintId;
  count: number;
  randomSpreadSpeedHorizontal: number;
  randomSpreadSpeedVertical: number;
  reflectedVelocityDamper?: number;
};

export type SmokeTrailSpec = {
  useId?: string;
  maxPoolSize?: number;
  capPolicy: 'evictOldest' | 'skipWhenFull';
  emitFramesSkip?: number;
  exhaustSpeed?: number;
  startRadius?: number;
  endRadiusMultiplier?: number;
  fadeInMs?: number;
  fadeOutMs?: number;
  maxAlpha?: number;
  color?: number;
};

export type ProjectileShotBlueprint = {
  type: ProjectileShotKind;
  shotBlueprintId: ShotBlueprintId;
  name: string;
  base: EntityBaseLedger;
  mass: number;
  health: number;
  radius: EntityRadiusConfig;
  armingDelayMs: number;
  detonateOnExpiry: boolean;
  maxLifespan?: number | null;
  hitSound: SoundEntry | null;
  submunitions: SubmunitionSpec | null;
  homingTurnRate: number | null;
  homingThrust: number | null;
  gravityForceMultiplier: number;
  smokeTrail: SmokeTrailSpec | null;
};

export type ShotBlueprint = ProjectileShotBlueprint;

export type ProjectileTailShape = 'cone' | 'cylinder' | 'none';

export type ShieldBarrierConfig = {
  shape: ShieldBarrierShape;
  innerRange: number;
  outerRange: number;
  originOffsetZ: number;
  color: number;
  alpha: number;
  particleAlpha: number;
};

export type ProjectileShot = {
  type: ProjectileShotKind;
  shotBlueprintId: ShotBlueprintId;
  base: EntityBaseLedger;
  mass: number;
  health: number;
  launchForce: number;
  radius: EntityRadiusConfig;
  armingDelayMs: number;
  explosion?: ShotExplosion;
  detonateOnExpiry?: boolean;
  maxLifespan?: number;
  homingTurnRate?: number;
  homingThrust?: number;
  gravityForceMultiplier: number;
  trailLength?: number;
  submunitions?: SubmunitionSpec;
  smokeTrail?: SmokeTrailSpec;
};

export type ActiveProjectileShot = ProjectileShot | BeamRay | LaserRay;

export type ShotConfig = ProjectileShot;

export type ProjectileType = 'projectile' | 'beam' | 'laser';

export type BeamReflectorKind = 'shield';

export type BeamPoint = {
  x: number;
  y: number;
  z: number;
  vx: number;
  vy: number;
  vz: number;
  reflectorEntityId?: EntityId;
  reflectorKind?: BeamReflectorKind;
  reflectorPlayerId?: PlayerId;
  normalX?: number;
  normalY?: number;
  normalZ?: number;
};

export type ShotRuntimeType = 'plasma' | 'rocket' | 'beam' | 'laser';

export type ShotRuntimeProfile = {
  shotBlueprintId: string;
  type: ShotRuntimeType;
  projectileType: ProjectileType;
  isProjectile: boolean;
  isLine: boolean;
  isRocketLike: boolean;
  radius: EntityRadiusConfig;
  deathExplosionRadius: number;
  armingDelayMs: number;
  maxLifespan: number;
  detonateOnExpiry: boolean;
  hasExplosion: boolean;
  hasSubmunitions: boolean;
};

export type ShotVisualProfile = {
  projectileTailShape: ProjectileTailShape;
  projectileTailLengthMult: number;
  projectileTailRadiusMult: number;
  projectileFinSizeMult: number;
  smokeTrail?: SmokeTrailSpec;
  burnMarkWidth: number;
  lineRadius: number;
  lineDamageSphereRadius: number;
  lineEmissionOffset: number;
};

export type ShotProfile = {
  runtime: ShotRuntimeProfile;
  visual: ShotVisualProfile;
};

export type ShieldPanel = {
  offsetX: number;
  offsetY: number;
  angle: number;
};

export type EntityRadiusConfig = {
  visual: number;
  hitbox: number;
  collision: number;
};

export type EntityDeathExplosion = {
  radius: number;
  force: number;
  damage: number;
};

export type EntityBaseLedger = {
  cost: ResourceCost;
  mass: number;
  health: number;
  deathExplosion: EntityDeathExplosion;
  radius: EntityRadiusConfig;
};

export type TurretRadiusConfig = EntityRadiusConfig;

export type TurretAimAngleType = 'rayDirect' | 'rayBisectTurretAndBody' | 'ballisticArcLow' | 'ballisticArcLowOnlyUnder' | 'ballisticArcHigh';

export type TurretAimStyle = {
  angleType: TurretAimAngleType;
};

export type TurretLockOnRelationshipInclusion = 'friendly_entities' | 'enemy_entities';

export type TurretLockOnEntityFamilyInclusion = 'buildings' | 'towers' | 'units' | 'turrets' | 'shots';

export type LockOnRequiresTargetLockedOntoSelf = 'ignore' | 'require' | 'preferReacquire' | 'preferHold';

export type LockOnInclusionObject = {
  includeLockOnLevel0FriendsAndEnemies: TurretLockOnRelationshipInclusion[];
  includeLockOnLevel0Entities: TurretLockOnEntityFamilyInclusion[];
  includeLockOnLevel1Buildings: string[];
  includeLockOnLevel1Towers: string[];
  includeLockOnLevel1Units: string[];
  includeLockOnLevel1Turrets: string[];
  includeLockOnLevel1Shots: string[];
  lockOnRequiresTargetLockedOntoSelf: LockOnRequiresTargetLockedOntoSelf;
};

export type WeaponKind = 'attack' | 'construction' | 'repair';

export type TurretSpreadConfig = {
  angle: number;
  pelletCount: number;
};

export type TurretBurstConfig = {
  count: number;
  delay: number;
};

export type TurretAudioConfig = {
  fireSound: SoundEntry;
};

export type TurretBlueprint = {
  turretBlueprintId: TurretBlueprintId;
  name: string;
  kind: WeaponKind;
  range: number;
  rangeVolume: TurretRangeVolume;
  cooldown: number;
  color: number;
  turretTurnAccel: number;
  turretDrag: number;
  barrel: BarrelShape;
  rangeMultiplierOverrides: TurretRangeOverrides;
  eventsSmooth: boolean;
  launchForce: number;
  isManualFire: boolean;
  passive: boolean;
  requiresNonObstructedLineOfSight: boolean;
  spread: TurretSpreadConfig | null;
  burst: TurretBurstConfig | null;
  shieldPanels: ShieldPanel[];
  audio: TurretAudioConfig | null;
  radius: TurretRadiusConfig;
  headOnly: boolean;
  aimStyle: TurretAimStyle;
  verticalLauncher: boolean;
  idlePitch: number;
  groundAimFraction: number | null;
  constructionEmitter: ConstructionEmitterVisualSpec | null;
  includeLockOnLevel0FriendsAndEnemies: TurretLockOnRelationshipInclusion[];
  includeLockOnLevel0Entities: TurretLockOnEntityFamilyInclusion[];
  includeLockOnLevel1Buildings: string[];
  includeLockOnLevel1Towers: string[];
  includeLockOnLevel1Units: string[];
  includeLockOnLevel1Turrets: string[];
  includeLockOnLevel1Shots: string[];
  lockOnRequiresTargetLockedOntoSelf: LockOnRequiresTargetLockedOntoSelf;
  emissionKind: EmissionKind | null;
  emissionBlueprintId: string | null;
};

export type MountOffset = {
  x: number;
  y: number;
  z: number;
};

export type UnitTurretMountZResolver = {
  kind: 'topMounted';
  bodyTopZFrac: number;
};

export type TurretMount = {
  turretBlueprintId: TurretBlueprintId;
  mount: MountOffset;
  shieldPanels?: ShieldPanel[];
  hostDirected: boolean;
  zResolver?: UnitTurretMountZResolver;
  visualVariant?: ConstructionEmitterSize;
};

export type BuildingTurretMount = {
  turretBlueprintId: TurretBlueprintId;
  mount: MountOffset;
  shieldPanels?: ShieldPanel[];
  hostDirected: boolean;
  visualVariant?: ConstructionEmitterSize;
};

export type WheelConfig = {
  wheelDistX: number;
  wheelDistY: number;
  treadLength: number;
  treadWidth: number;
  wheelRadius: number;
  rotationSpeed: number;
};

export type TreadConfig = {
  treadOffset: number;
  treadLength: number;
  treadWidth: number;
  wheelRadius: number;
  rotationSpeed: number;
};

export type LegLayoutEntry = {
  attachOffsetXFrac: number;
  attachOffsetYFrac: number;
  upperLegLengthFrac: number;
  lowerLegLengthFrac: number;
  snapTriggerAngle: number;
  snapTargetAngle: number;
  snapDistanceMultiplier: number;
  extensionThreshold: number;
};

export type LegConfig = {
  upperThickness: number;
  lowerThickness: number;
  hipRadius: number;
  kneeRadius: number;
  lerpDuration: number;
  leftSide: LegLayoutEntry[];
};

export type LocomotionPhysics = {
  driveForce: number;
  traction: number;
};

export type PathfindingTerrainMode = 'land' | 'anywhere';

export type PathfindingBlueprint = {
  pathfindingBlueprintId: string;
  terrainMode: PathfindingTerrainMode;
  maxSlopeDeg: number | null;
};

export type HoverConfig = {
  gravityCounterUpwardForceRatio: number;
  hoverHeightUpwardForce: number;
  hoverHeightUpwardForceRandomizationAmount?: number;
  hoverHeightUpwardForceEMA?: number;
  fanDistX: number;
  fanDistY: number;
  fanPositionRadius?: number;
  fanLayout?: 'quad' | 'triFront' | 'twin';
  fanRadius: number;
  fanRingTubeRadius: number;
  fanOutwardAngleDeg?: number;
  fanSpinRadPerSec?: number;
  tailFanOffsetX?: number;
  tailFanRadius?: number;
  tailFanRingTubeRadius?: number;
  tailFanBackAngleDeg?: number;
};

export type FlyingConfig = {
  gravityCounterUpwardForceRatio: number;
  hoverHeightUpwardForce: number;
  hoverHeightUpwardForceRandomizationAmount?: number;
  hoverHeightUpwardForceEMA?: number;
  wingEnabled?: boolean;
  wingSpan?: number;
  wingChord?: number;
  wingOffsetX?: number;
  wingHeight?: number;
  wingThickness?: number;
  wingDihedralDeg?: number;
  wingSweepFrac?: number;
  tailWingSpan?: number;
  tailWingChord?: number;
  tailWingOffsetX?: number;
  tailWingHeight?: number;
  tailWingThickness?: number;
  tailWingDihedralDeg?: number;
  tailWingSweepFrac?: number;
  tailWingMirrorX?: boolean;
  jetOffsetX: number;
  jetOffsetY: number;
  jetOffsetZ: number;
  jetRadius: number;
  jetLength: number;
  jetCount?: 1 | 2;
};

export type LocomotionBlueprintWheels = {
  type: 'wheels';
  physics: LocomotionPhysics;
  pathfindingBlueprintId: string;
  pathfinding: PathfindingBlueprint;
  config: WheelConfig;
};

export type LocomotionBlueprintTreads = {
  type: 'treads';
  physics: LocomotionPhysics;
  pathfindingBlueprintId: string;
  pathfinding: PathfindingBlueprint;
  config: TreadConfig;
};

export type LocomotionBlueprintLegs = {
  type: 'legs';
  physics: LocomotionPhysics;
  pathfindingBlueprintId: string;
  pathfinding: PathfindingBlueprint;
  config: LegConfig;
};

export type LocomotionBlueprintHover = {
  type: 'hover';
  physics: LocomotionPhysics;
  pathfindingBlueprintId: string;
  pathfinding: PathfindingBlueprint;
  config: HoverConfig;
};

export type LocomotionBlueprintFlying = {
  type: 'flying';
  physics: LocomotionPhysics;
  pathfindingBlueprintId: string;
  pathfinding: PathfindingBlueprint;
  config: FlyingConfig;
};

export type LocomotionBlueprint = LocomotionBlueprintWheels | LocomotionBlueprintTreads | LocomotionBlueprintLegs | LocomotionBlueprintHover | LocomotionBlueprintFlying;

export type UnitBodyShapePartCircle = {
  kind: 'circle';
  offsetForward: number;
  offsetLateral?: number;
  radiusFrac: number;
  yFrac?: number;
  centerYFrac?: number;
};

export type UnitBodyShapePartOval = {
  kind: 'oval';
  offsetForward: number;
  offsetLateral?: number;
  xFrac: number;
  yFrac: number;
  zFrac: number;
};

export type UnitBodyShapePartCylinder = {
  kind: 'cylinder';
  offsetForward: number;
  offsetLateral?: number;
  lengthFrac: number;
  radiusFrac: number;
  centerYFrac?: number;
  pitchRad?: number;
};

export type UnitBodyShapePartCone = {
  kind: 'cone';
  offsetForward: number;
  offsetLateral?: number;
  lengthFrac: number;
  radiusFrac: number;
  centerYFrac?: number;
};

export type UnitBodyShapePart = UnitBodyShapePartCircle | UnitBodyShapePartOval | UnitBodyShapePartCylinder | UnitBodyShapePartCone;

export type UnitBodyShapePolygon = {
  kind: 'polygon';
  sides: number;
  radiusFrac: number;
  heightFrac: number;
  rotation: number;
};

export type UnitBodyShapeRect = {
  kind: 'rect';
  lengthFrac: number;
  widthFrac: number;
  heightFrac: number;
};

export type UnitBodyShapeRhombus = {
  kind: 'rhombus';
  lengthFrac: number;
  widthFrac: number;
  heightFrac: number;
};

export type UnitBodyShapeCircle = {
  kind: 'circle';
  radiusFrac: number;
  yFrac?: number;
};

export type UnitBodyShapeOval = {
  kind: 'oval';
  xFrac: number;
  yFrac: number;
  zFrac: number;
};

export type UnitBodyShapeComposite = {
  kind: 'composite';
  parts: UnitBodyShapePart[];
};

export type UnitBodyShape = UnitBodyShapePolygon | UnitBodyShapeRect | UnitBodyShapeRhombus | UnitBodyShapeCircle | UnitBodyShapeOval | UnitBodyShapeComposite;

export type EntityHudBlueprint = {
  barsOffsetAboveTop: number;
};

export type UnitRadiusConfig = EntityRadiusConfig;

export type UnitBuilderConfig = {
  buildRange: number;
  constructionRate: number;
};

export type UnitDgunConfig = {
  turretBlueprintId: TurretBlueprintId;
  energyCost: number;
};

export type UnitBlueprint = {
  unitBlueprintId: UnitBlueprintId;
  name: string;
  shortName: string;
  base: EntityBaseLedger;
  hp: number;
  radius: UnitRadiusConfig;
  bodyCenterHeight: number;
  fullVisionRadius: number;
  mass: number;
  cost: ResourceCost;
  turrets: TurretMount[];
  bodyShape: UnitBodyShape;
  hud: EntityHudBlueprint;
  legAttachHeightFrac: number | null;
  locomotion: LocomotionBlueprint;
  suspension: UnitSuspensionConfig | null;
  builder: UnitBuilderConfig | null;
  dgun: UnitDgunConfig | null;
  deathSound: SoundEntry | null;
  fightStopEngagedRatio: number | null;
  includeLockOnLevel0FriendsAndEnemies: TurretLockOnRelationshipInclusion[];
  includeLockOnLevel0Entities: TurretLockOnEntityFamilyInclusion[];
  includeLockOnLevel1Buildings: string[];
  includeLockOnLevel1Towers: string[];
  includeLockOnLevel1Units: string[];
  includeLockOnLevel1Turrets: string[];
  includeLockOnLevel1Shots: string[];
  lockOnRequiresTargetLockedOntoSelf: LockOnRequiresTargetLockedOntoSelf;
};

export type RayType = 'beam' | 'laser';

export type EmissionKind = 'shot' | 'ray' | 'shield';

export type BeamRayBlueprint = {
  type: 'beam';
  dps: number;
  force: number;
  recoil: number;
  radius: number;
  width: number;
  damageSphere: ShotCollision;
  gravityForceMultiplier: number;
  hitSound: SoundEntry | null;
  rayBlueprintId: RayBlueprintId;
};

export type LaserRayBlueprint = {
  type: 'laser';
  dps: number;
  force: number;
  recoil: number;
  radius: number;
  width: number;
  damageSphere: ShotCollision;
  duration: number;
  gravityForceMultiplier: number;
  hitSound: SoundEntry | null;
  rayBlueprintId: RayBlueprintId;
};

export type ShieldBlueprint = {
  type: 'shield';
  materialId: ShieldMaterialId;
  angle: number;
  transitionTime: number;
  barrier: ShieldBarrierRatioConfig | null;
  hitSound: SoundEntry | null;
  shieldBlueprintId: ShieldBlueprintId;
};

export type RayBlueprint = BeamRayBlueprint | LaserRayBlueprint;

export type BeamRay = {
  type: 'beam';
  dps: number;
  force: number;
  recoil: number;
  radius: number;
  width: number;
  damageSphere: ShotCollision;
  gravityForceMultiplier: number;
  rayBlueprintId: RayBlueprintId;
};

export type LaserRay = {
  type: 'laser';
  dps: number;
  force: number;
  recoil: number;
  radius: number;
  width: number;
  damageSphere: ShotCollision;
  duration: number;
  gravityForceMultiplier: number;
  rayBlueprintId: RayBlueprintId;
};

export type RayConfig = BeamRay | LaserRay;

export type ShieldConfig = {
  type: 'shield';
  material: ShieldMaterialBlueprint;
  angle: number;
  transitionTime: number;
  barrier?: ShieldBarrierConfig;
  shieldBlueprintId: ShieldBlueprintId;
};

export type EmissionConfig = ProjectileShot | BeamRay | LaserRay | ShieldConfig;
