// Generated by scripts/generateBlueprintSchemaTypes.mjs from src/game/sim/blueprints/blueprintSchema.json.
// Do not edit this file directly.
import type { SoundEntry } from './audio';
import type { RayBlueprintId, ShieldBlueprintId, ShieldMaterialId, ShotBlueprintId, StructureBlueprintId, TurretBlueprintId, UnitBlueprintId } from './blueprintIds';
import type { TurretRangeOverrides } from './combatTypes';
import type { BarrelShape } from './config';
import type { WorkEmitterSpec } from './constructionTypes';
import type { ResourceCost } from './economyTypes';
import type { EntityId, PlayerId } from './entityTypes';
import type { UnitSuspensionConfig } from './unitLocomotionTypes';

export type TurretRangeVolume = 'turret-range-cylinder-normal' | 'turret-range-bottom-unbounded' | 'turret-range-top-water-and-bottom-unbounded' | 'turret-range-top-and-bottom-unbounded' | 'turret-range-sphere';

export type SensorMediumTargetRadii = {
  aboveWater: number;
  underwater: number;
};

export type SensorMediumRadiusMatrix = {
  aboveWater: SensorMediumTargetRadii;
  underwater: SensorMediumTargetRadii;
};

export type EmissionMediumTargetRoutes = {
  aboveWater: boolean;
  underwater: boolean;
};

export type EmissionMediumTrajectoryMatrix = {
  aboveWater: EmissionMediumTargetRoutes;
  underwater: EmissionMediumTargetRoutes;
};

export type SensorCapabilityConfig = {
  fullSight: SensorMediumRadiusMatrix;
  contactSight: SensorMediumRadiusMatrix;
  detectorRadius: number;
  radarJamRadius: number;
  sonarJamRadius: number;
};

export type TurretEngagementEnvelope = {
  range: number;
  rangeVolume: TurretRangeVolume;
  rangeMultiplierOverrides: TurretRangeOverrides;
};

export type TurretObservationEnvelope = {
  rangeVolume: TurretRangeVolume;
  sensors: SensorCapabilityConfig;
};

export type TurretEffectRangeSource = 'engagement' | 'explicit';

export type TurretEffectEnvelope = {
  rangeSource: TurretEffectRangeSource;
  range?: number;
  rangeVolume?: TurretRangeVolume;
};

export type TurretIntelRequirement = 'contactSight' | 'fullSight';

export type TurretTargetingConfig = {
  engagement: TurretEngagementEnvelope;
  observation: TurretObservationEnvelope;
  effect: TurretEffectEnvelope;
  requiredIntel: TurretIntelRequirement;
};

export type ProjectileShotKind = 'plasma' | 'rocket' | 'missile';

export type ShotLocomotionMotionModel = 'ballistic' | 'thrustGuided' | 'constantSpeedGuided' | 'terrainFollowing';

export type ShotLocomotionTerminalOutcome = 'detonate' | 'despawn';

export type ShotLocomotionTransitionOutcome = 'continue' | 'continueBallistic' | 'detonate' | 'despawn';

export type ShotLocomotionMediumPhysics = {
  operational: boolean;
  propulsionForce: number;
  guidanceThrust: number;
  turnRate: number;
  velocityFrictionPer60HzFrame: number;
};

export type ShotLocomotionGroundPhysics = {
  mode: 'impact' | 'terrainFollowing';
};

export type ShotLocomotionMedia = {
  air: ShotLocomotionMediumPhysics;
  water: ShotLocomotionMediumPhysics;
  ground: ShotLocomotionGroundPhysics;
};

export type ShotLocomotionTransitions = {
  enterWater: ShotLocomotionTransitionOutcome;
  exitWater: ShotLocomotionTransitionOutcome;
};

export type ShotLocomotionTerminalPolicy = {
  entityImpact: ShotLocomotionTerminalOutcome;
  groundContact: ShotLocomotionTerminalOutcome;
  expiry: ShotLocomotionTerminalOutcome;
  destroyed: ShotLocomotionTerminalOutcome;
  reflectorImpact: ShotLocomotionTerminalOutcome;
};

export type ShotLocomotion = {
  presetId: string;
  motionModel: ShotLocomotionMotionModel;
  maxLifespanMs: number | null;
  gravityForceMultiplier: number;
  guidanceDelayMs: number;
  guidanceRampMs: number;
  guidanceSolveRateHz: number;
  lostTargetBehavior: 'continueCurrentVector' | 'flyToLastInterceptPoint';
  lostTargetArrivalRadius: number;
  media: ShotLocomotionMedia;
  transitions: ShotLocomotionTransitions;
  terminal: ShotLocomotionTerminalPolicy;
};

export type ShieldSurfaceResponse = 'reflect' | 'absorb' | 'passThrough';

export type ShieldReflectionMode = 'outside-in' | 'inside-out' | 'both';

export type ShieldReflectionDirection = 'reflect-none' | 'reflect-outside' | 'reflect-inside' | 'reflect-both';

export type ShieldReflectionEntity = 'plasma' | 'rocket' | 'missile' | 'beam';

export type ShieldReflectionEntityDirections = {
  plasma?: ShieldReflectionDirection;
  rocket?: ShieldReflectionDirection;
  missile?: ShieldReflectionDirection;
  beam?: ShieldReflectionDirection;
};

export type ShieldReflectionPolicy = {
  entities: ShieldReflectionEntityDirections;
};

export type ShieldBarrierShape = 'sphere';

export type ShieldBarrierRatioConfig = {
  shape: ShieldBarrierShape;
  outerRatio?: number | null;
  rimWidth?: number | null;
  originOffsetRadiusRatio?: number | null;
};

export type TurretSubmunitionEmitterConfig = {
  shotBlueprintId: ShotBlueprintId;
  launchForce: number;
  cooldown: TurretCooldownConfig;
  spread: TurretSpreadConfig;
};

export type ShieldMaterialVisualConfig = {
  color: number;
  alpha: number;
  particleAlpha: number;
};

export type ShieldMaterialReflectionConfig = {
  mode: ShieldReflectionMode;
  reflectivity: number;
};

export type ShieldMaterialProjectileResponseConfig = {
  plasma: ShieldSurfaceResponse;
  rocket: ShieldSurfaceResponse;
  beam: ShieldSurfaceResponse;
};

export type ShieldMaterialHitReactionConfig = {
  impactEvent: 'shieldImpact';
  sound: SoundEntry | null;
};

export type ShieldMaterialBlueprint = {
  materialId: ShieldMaterialId;
  reflection: ShieldMaterialReflectionConfig;
  projectileResponse: ShieldMaterialProjectileResponseConfig;
  hitReaction: ShieldMaterialHitReactionConfig;
  visual: ShieldMaterialVisualConfig;
};

export type ShotCollision = {
  radius: number;
};

export type ShotExplosion = {
  radius: number;
  damage: number;
  force: number;
};

export type SubmunitionSpec = {
  shotBlueprintId: ShotBlueprintId;
  count: number;
  randomSpreadSpeedHorizontal: number;
  randomSpreadSpeedVertical: number;
  reflectedVelocityDamper?: number;
};

export type SmokeTrailSpec = {
  useId?: string;
  maxPoolSize?: number;
  capPolicy: 'evictOldest' | 'skipWhenFull';
  emitFramesSkip?: number;
  exhaustSpeed?: number;
  startRadius?: number;
  endRadiusMultiplier?: number;
  fadeInMs?: number;
  fadeOutMs?: number;
  maxAlpha?: number;
  color?: number;
};

export type ShotTurningBlueprint = {
  turnRate: number;
  guidanceDelayMs: number;
  guidanceRampMs: number;
  guidanceSolveRateHz: number;
  lostTargetBehavior: 'continueCurrentVector' | 'flyToLastInterceptPoint';
  lostTargetArrivalRadius: number;
};

export type ProjectileShotBlueprint = {
  type: ProjectileShotKind;
  shotBlueprintId: ShotBlueprintId;
  name: string;
  base: EntityBaseLedger;
  mass: number;
  health: number;
  radius: EntityRadiusConfig;
  shotLocomotionPresetId: string;
  maxLifespanMs: number | null;
  turning: ShotTurningBlueprint | null;
  mediumTrajectory: EmissionMediumTrajectoryMatrix;
  hitSound: SoundEntry | null;
  submunitions: SubmunitionSpec | null;
  smokeTrail: SmokeTrailSpec | null;
};

export type ShotBlueprint = ProjectileShotBlueprint;

export type ProjectileTailShape = 'cone' | 'cylinder' | 'none';

export type ShieldBarrierConfig = {
  shape: ShieldBarrierShape;
  innerRange: number;
  outerRange: number;
  originOffsetZ: number;
  color: number;
  alpha: number;
  particleAlpha: number;
};

export type ProjectileShot = {
  type: ProjectileShotKind;
  shotBlueprintId: ShotBlueprintId;
  base: EntityBaseLedger;
  mass: number;
  health: number;
  launchForce: number;
  radius: EntityRadiusConfig;
  explosion?: ShotExplosion;
  shotLocomotion: ShotLocomotion;
  mediumTrajectory: EmissionMediumTrajectoryMatrix;
  trailLength?: number;
  submunitions?: SubmunitionSpec;
  smokeTrail?: SmokeTrailSpec;
};

export type ActiveProjectileShot = ProjectileShot | BeamRay;

export type ShotConfig = ProjectileShot;

export type ProjectileType = 'projectile' | 'beam';

export type BeamReflectorKind = 'shield';

export type BeamPoint = {
  x: number;
  y: number;
  z: number;
  vx: number;
  vy: number;
  vz: number;
  reflectorEntityId: EntityId | null;
  reflectorKind: BeamReflectorKind | null;
  reflectorPlayerId: PlayerId | null;
  normalX: number | null;
  normalY: number | null;
  normalZ: number | null;
};

export type ShotRuntimeType = 'plasma' | 'rocket' | 'missile' | 'beam';

export type ShotRuntimeProfile = {
  shotBlueprintId: string;
  type: ShotRuntimeType;
  projectileType: ProjectileType;
  isProjectile: boolean;
  isLine: boolean;
  isRocketLike: boolean;
  radius: EntityRadiusConfig;
  deathExplosionRadius: number;
  maxLifespan: number;
  detonateOnExpiry: boolean;
  hasExplosion: boolean;
  hasSubmunitions: boolean;
};

export type ShotVisualProfile = {
  projectileTailShape: ProjectileTailShape;
  projectileTailLengthMult: number;
  projectileTailRadiusMult: number;
  projectileFinSizeMult: number;
  smokeTrail?: SmokeTrailSpec;
  burnMarkWidth: number;
  lineRadius: number;
  lineDamageSphereRadius: number;
};

export type ShotProfile = {
  runtime: ShotRuntimeProfile;
  visual: ShotVisualProfile;
};

export type ShieldPanel = {
  offsetX: number;
  offsetY: number;
  angle: number;
};

export type EntityRadiusConfig = {
  other: number;
  hitbox: number;
  collision: number;
};

export type EntityDeathExplosion = {
  radius: number;
  force: number;
  damage: number;
};

export type EntitySignature = {
  radarStealth: boolean;
  sonarStealth: boolean;
};

export type EntityBaseLedger = {
  cost: ResourceCost;
  mass: number;
  health: number;
  deathExplosion: EntityDeathExplosion;
  radius: EntityRadiusConfig;
  signature: EntitySignature;
};

export type TurretAimAngleType = 'rayDirect' | 'rayBisectTurretAndBody' | 'ballisticArcLow' | 'ballisticArcLowOnlyUnder' | 'ballisticArcHigh';

export type TurretAimStyle = {
  angleType: TurretAimAngleType;
};

export type TurretLockOnRelationshipInclusion = 'friendly_entities' | 'enemy_entities';

export type TurretLockOnEntityFamilyInclusion = 'buildings' | 'units' | 'turrets' | 'shots';

export type LockOnRequiresTargetLockedOntoSelf = 'ignore' | 'require' | 'preferReacquire' | 'preferHold';

export type LockOnInclusionObject = {
  includeLockOnLevel0FriendsAndEnemies: TurretLockOnRelationshipInclusion[];
  includeLockOnLevel0Entities: TurretLockOnEntityFamilyInclusion[];
  includeLockOnLevel1Buildings: string[];
  includeLockOnLevel1Units: string[];
  includeLockOnLevel1Turrets: string[];
  includeLockOnLevel1Shots: string[];
  lockOnRequiresTargetLockedOntoSelf: LockOnRequiresTargetLockedOntoSelf;
};

export type TurretEmitterKind = 'attack' | 'spawn' | 'resourcePylon' | 'sensor';

export type TurretMountControlMode = 'hostPreferred' | 'hostOnly' | 'autonomous' | 'manual' | 'slaved';

export type SpawnProducedKind = 'buildings' | 'units';

export type ResourcePylonResource = 'metal' | 'energy';

export type ResourcePylonRole = 'construction' | 'extraction';

export type SpawnTurretConfig = {
  producedKind: SpawnProducedKind;
  producedBlueprintId: string | null;
  producesNanoframe: boolean;
  cooldownMs: number;
  launchForce: number;
};

export type ResourcePylonConfig = {
  resource: ResourcePylonResource;
  role: ResourcePylonRole;
  radius: number;
};

export type TurretSpreadConfig = {
  angle: number;
  pelletCount: number;
};

export type TurretBurstConfig = {
  count: number;
  delay: number;
};

export type TurretCooldownConfig = {
  duration: number;
  durationRandomness: number;
};

export type TurretAudioConfig = {
  fireSound: SoundEntry;
};

export type TurretAngularActuatorAxis = {
  maxSpeed: number;
  maxAcceleration: number;
};

export type TurretAngularActuator = {
  yaw: TurretAngularActuatorAxis;
  pitch: TurretAngularActuatorAxis;
};

export type TurretBlueprint = {
  turretBlueprintId: TurretBlueprintId;
  name: string;
  kind: TurretEmitterKind;
  targeting: TurretTargetingConfig;
  cooldown: TurretCooldownConfig | null;
  color: number;
  angularActuator?: TurretAngularActuator;
  emissionLaneCount: number;
  eventsSmooth: boolean;
  launchForce: number;
  addTurretVelocityToEmissionLaunch: boolean;
  passive: boolean;
  requiresNonObstructedLineOfSight: boolean;
  spread: TurretSpreadConfig | null;
  submunitions?: TurretSubmunitionEmitterConfig | null;
  burst: TurretBurstConfig | null;
  audio: TurretAudioConfig | null;
  aimMotionSnapshotVisible: boolean;
  aimStyle: TurretAimStyle;
  verticalLauncher: boolean;
  idlePitch: number;
  groundAimFraction: number | null;
  spawn?: SpawnTurretConfig | null;
  resourcePylon?: ResourcePylonConfig | null;
  includeLockOnLevel0FriendsAndEnemies: TurretLockOnRelationshipInclusion[];
  includeLockOnLevel0Entities: TurretLockOnEntityFamilyInclusion[];
  includeLockOnLevel1Buildings: string[];
  includeLockOnLevel1Units: string[];
  includeLockOnLevel1Turrets: string[];
  includeLockOnLevel1Shots: string[];
  lockOnRequiresTargetLockedOntoSelf: LockOnRequiresTargetLockedOntoSelf;
  emissionKind: EmissionKind | null;
  emissionBlueprintId: string | null;
};

export type TurretPresentation = {
  headRadius: number | null;
  headOnly: boolean;
  barrel: BarrelShape | null;
};

export type MountOffset = {
  x: number;
  y: number;
  z: number;
};

export type UnitTurretMountZResolver = {
  kind: 'topMounted';
  bodyTopZFrac: number;
};

export type BotArmTurretHostAttachment = {
  kind: 'botArm';
  arm: 'leftArm' | 'rightArm' | 'leftUpperArm' | 'rightUpperArm';
  socketOffset: MountOffset;
};

export type BotPieceTurretHostAttachment = {
  kind: 'botPiece';
  piece: 'head' | 'leftShoulder' | 'rightShoulder' | 'backpackLeft' | 'backpackRight';
  socketOffset: MountOffset;
};

export type UnitTurretHostAttachment = BotArmTurretHostAttachment | BotPieceTurretHostAttachment;

export type BuildingYawPieceTurretHostAttachment = {
  kind: 'buildingYawPiece';
  piece: string;
  socketOffset: MountOffset;
};

export type BuildingAimPieceTurretHostAttachment = {
  kind: 'buildingAimPiece';
  piece: string;
  socketOffset: MountOffset;
};

export type BuildingTurretHostAttachment = BuildingYawPieceTurretHostAttachment | BuildingAimPieceTurretHostAttachment;

export type TurretHostAttachment = UnitTurretHostAttachment | BuildingTurretHostAttachment;

export type TurretEmissionSocket = {
  offset: MountOffset;
};

export type TurretYawTraverse = {
  continuous: boolean;
  minAngle: number;
  maxAngle: number;
};

export type TurretPitchTraverse = {
  minAngle: number;
  maxAngle: number;
};

export type TurretHostAssistPolicy = 'none' | 'requestYaw' | 'requestAim';

export type TurretStationArticulation = {
  yaw: TurretYawTraverse;
  pitch: TurretPitchTraverse;
  restYaw: number;
  restPitch: number;
  restoreDelayMs: number;
  hostAssist: TurretHostAssistPolicy;
  claimGroup: string | null;
  claimPriority: number;
};

export type TurretMount = {
  mountId: string;
  turretBlueprintId: TurretBlueprintId;
  sensorTurretBlueprintId?: TurretBlueprintId;
  mount: MountOffset;
  presentation: TurretPresentation | null;
  shieldPanels?: ShieldPanel[];
  controlMode: TurretMountControlMode;
  slavedToMountId?: string;
  requiredEngagedForFightStop: boolean;
  zResolver?: UnitTurretMountZResolver;
  hostAttachment?: UnitTurretHostAttachment;
  emissionSockets?: TurretEmissionSocket[];
  articulation?: TurretStationArticulation;
  producedBlueprintId?: UnitBlueprintId;
  allowedBuildBlueprintIds?: StructureBlueprintId[];
  productionHoldAnchor?: 'host';
  constructionRate?: number;
};

export type BuildingTurretMount = {
  mountId: string;
  turretBlueprintId: TurretBlueprintId;
  sensorTurretBlueprintId?: TurretBlueprintId;
  mount: MountOffset;
  presentation: TurretPresentation | null;
  shieldPanels?: ShieldPanel[];
  controlMode: TurretMountControlMode;
  slavedToMountId?: string;
  hostAttachment?: BuildingTurretHostAttachment;
  emissionSockets?: TurretEmissionSocket[];
  articulation?: TurretStationArticulation;
  angularActuator?: TurretAngularActuator;
};

export type RoverConfig = {
  mounts: LocomotionMount[];
  treadWidth: number;
  wheelRadius: number;
  rotationSpeed: number;
};

export type TankConfig = {
  mounts: LocomotionMount[];
  treadLength: number;
  treadWidth: number;
  wheelRadius: number;
  rotationSpeed: number;
};

export type LegSegment = {
  lengthUnitRadiusRatio: number;
};

export type LegSegments = {
  upper: LegSegment;
  lower: LegSegment;
};

export type LegFootSphere = {
  originExtensionRatio: number;
  radiusLegLengthRatio: number;
};

export type LegLayoutEntry = {
  attachmentPoint: LocomotionMount;
};

export type LegChoppingSphere = {
  radiusLegLengthRatio: number;
};

export type LegSnapRay = {
  originBoundarySpanRatio: number;
};

export type CrawlerConfig = {
  radius: number;
  kneeRadius: number;
  hasFeet: boolean;
  lerpDuration: number;
  segments: LegSegments;
  footSphere: LegFootSphere;
  choppingSphere: LegChoppingSphere;
  snapRay: LegSnapRay;
  leftSide: LegLayoutEntry[];
};

export type BotArmSegments = {
  upper: LegSegment;
  lower: LegSegment;
};

export type BotArms = {
  shoulder: LocomotionMount;
  radius: number;
  segments: BotArmSegments;
  handRadiusRatio: number;
  restSwingDeg: number;
  walkSwingDeg: number;
  outwardDeg: number;
  elbowBendDirection?: 'normal' | 'downward';
};

export type BotLegs = {
  hip: LocomotionMount;
  radius: number;
  segments: BotArmSegments;
  footLengthRatio: number;
  footWidthRatio: number;
  strideLengthRatio: number;
  strideLiftRatio: number;
  standHeightRatio: number;
  stanceForwardUnitRadiusRatio: number;
  stanceOutwardUnitRadiusRatio: number;
};

export type BotConfig = {
  legs: BotLegs;
  arms: BotArms;
  upperArms?: BotArms;
  upperBodyActuator: TurretAngularActuatorAxis;
  upperBodyRestoreDelayMs: number;
};

export type AmphibianConfig = {
  mounts: FlipperMount[];
  rootChordFrac: number;
  tipChordFrac: number;
  thicknessFrac: number;
  groundDownAngleDeg: number;
  groundSweepAngleDeg: number;
  waterStrokeAngleDeg: number;
  cycleDistanceFrac: number;
};

export type SubmarineConfig = {
  pectorals: SubmarinePectoralMount[];
  rearFan: SubmarineRearFan;
  pectoralSpanFrac: number;
  pectoralRootChordFrac: number;
  pectoralTipChordFrac: number;
  thicknessFrac: number;
  strokeAngleDeg: number;
  cycleDistanceFrac: number;
};

export type LocomotionAirLiftPhysics = {
  surfaceFollowingInverseForceFromGround: number;
  surfaceFollowingInverseForceFromWater: number;
};

export type LocomotionWaterLiftPhysics = {
  surfaceFollowingInverseForceFromGround: number;
  surfaceFollowingProportionalForceFromWater: number;
};

export type LocomotionAirFluidBodyPhysics = {
  maxPropulsiveForce: number;
  lift: LocomotionAirLiftPhysics;
};

export type LocomotionWaterFluidBodyPhysics = {
  maxPropulsiveForce: number;
  lift: LocomotionWaterLiftPhysics;
};

export type LocomotionGroundBodyPhysics = {
  maxPropulsiveForce: number;
};

export type UnitUnitLocomotionBlueprintPhysics = {
  ground: LocomotionGroundBodyPhysics;
  air: LocomotionAirFluidBodyPhysics;
  water: LocomotionWaterFluidBodyPhysics;
};

export type UnitLocomotionEnvironmentalHazardPolicy = {
  waterDamagePerSecond: number;
};

export type DroneConfig = {
  mounts: DroneFanMount[];
  fanSpinRadPerSec: number;
};

export type AirframeConfig = {
  wing: AirframeSurface | null;
  tailWing: AirframeSurface | null;
  jets: AirframeJetMount[];
  jetRadius: number;
  jetLength: number;
};

export type UnitLocomotionBlueprintRover = {
  type: 'rover';
  physicsPresetId: string;
  physics: UnitUnitLocomotionBlueprintPhysics;
  environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy;
  config: RoverConfig;
};

export type UnitLocomotionBlueprintTank = {
  type: 'tank';
  physicsPresetId: string;
  physics: UnitUnitLocomotionBlueprintPhysics;
  environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy;
  config: TankConfig;
};

export type UnitLocomotionBlueprintAmphibiousTank = {
  type: 'amphibious-tank';
  physicsPresetId: string;
  physics: UnitUnitLocomotionBlueprintPhysics;
  environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy;
  config: TankConfig;
};

export type UnitLocomotionBlueprintCrawler = {
  type: 'crawler';
  physicsPresetId: string;
  physics: UnitUnitLocomotionBlueprintPhysics;
  environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy;
  config: CrawlerConfig;
};

export type UnitLocomotionBlueprintBot = {
  type: 'bot';
  physicsPresetId: string;
  physics: UnitUnitLocomotionBlueprintPhysics;
  environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy;
  config: BotConfig;
};

export type UnitLocomotionBlueprintAmphibian = {
  type: 'amphibian';
  physicsPresetId: string;
  physics: UnitUnitLocomotionBlueprintPhysics;
  environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy;
  config: AmphibianConfig;
};

export type UnitLocomotionBlueprintDrone = {
  type: 'drone';
  physicsPresetId: string;
  physics: UnitUnitLocomotionBlueprintPhysics;
  environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy;
  config: DroneConfig;
};

export type UnitLocomotionBlueprintPlane = {
  type: 'plane';
  physicsPresetId: string;
  physics: UnitUnitLocomotionBlueprintPhysics;
  environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy;
  config: AirframeConfig;
  turnRateDegreesPerSecond?: number;
};

export type UnitLocomotionBlueprintSubmarine = {
  type: 'submarine';
  physicsPresetId: string;
  physics: UnitUnitLocomotionBlueprintPhysics;
  environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy;
  config: SubmarineConfig;
};

export type UnitLocomotionBlueprintAerosub = {
  type: 'aerosub';
  physicsPresetId: string;
  physics: UnitUnitLocomotionBlueprintPhysics;
  environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy;
  config: AirframeConfig;
  turnRateDegreesPerSecond?: number;
};

export type UnitLocomotionBlueprint = UnitLocomotionBlueprintRover | UnitLocomotionBlueprintTank | UnitLocomotionBlueprintAmphibiousTank | UnitLocomotionBlueprintCrawler | UnitLocomotionBlueprintBot | UnitLocomotionBlueprintAmphibian | UnitLocomotionBlueprintDrone | UnitLocomotionBlueprintPlane | UnitLocomotionBlueprintSubmarine | UnitLocomotionBlueprintAerosub;

export type UnitBodyShapePartCircle = {
  kind: 'circle';
  offsetForward: number;
  offsetLateral?: number;
  radiusFrac: number;
  yFrac?: number;
  centerYFrac?: number;
};

export type UnitBodyShapePartOval = {
  kind: 'oval';
  offsetForward: number;
  offsetLateral?: number;
  xFrac: number;
  yFrac: number;
  zFrac: number;
  centerYFrac?: number;
};

export type UnitBodyShapePartBox = {
  kind: 'box';
  offsetForward: number;
  offsetLateral?: number;
  lengthFrac: number;
  widthFrac: number;
  heightFrac: number;
  centerYFrac?: number;
  pitchRad?: number;
};

export type UnitBodyShapePartCylinder = {
  kind: 'cylinder';
  offsetForward: number;
  offsetLateral?: number;
  lengthFrac: number;
  radiusFrac: number;
  centerYFrac?: number;
  pitchRad?: number;
  startYFrac?: number;
  endYFrac?: number;
};

export type UnitBodyShapePartCone = {
  kind: 'cone';
  offsetForward: number;
  offsetLateral?: number;
  lengthFrac: number;
  radiusFrac: number;
  centerYFrac?: number;
};

export type UnitBodyShapePart = UnitBodyShapePartCircle | UnitBodyShapePartOval | UnitBodyShapePartCylinder | UnitBodyShapePartCone | UnitBodyShapePartBox;

export type UnitBodyShapePolygon = {
  kind: 'polygon';
  sides: number;
  radiusFrac: number;
  heightFrac: number;
  rotation: number;
};

export type UnitBodyShapeRect = {
  kind: 'rect';
  lengthFrac: number;
  widthFrac: number;
  heightFrac: number;
};

export type UnitBodyShapeRhombus = {
  kind: 'rhombus';
  lengthFrac: number;
  widthFrac: number;
  heightFrac: number;
};

export type UnitBodyShapeCircle = {
  kind: 'circle';
  radiusFrac: number;
  yFrac?: number;
};

export type UnitBodyShapeOval = {
  kind: 'oval';
  xFrac: number;
  yFrac: number;
  zFrac: number;
};

export type UnitBodyShapeComposite = {
  kind: 'composite';
  parts: UnitBodyShapePart[];
};

export type TeamOrnamentFit = {
  backX: number;
  frontX: number;
  backY: number;
  frontY: number;
};

export type UnitBodyShape = UnitBodyShapePolygon | UnitBodyShapeRect | UnitBodyShapeRhombus | UnitBodyShapeCircle | UnitBodyShapeOval | UnitBodyShapeComposite;

export type EntityHudBlueprint = {
  barsOffsetAboveTop: number;
};

export type UnitRadiusConfig = EntityRadiusConfig;

export type UnitBuilderConfig = {
  buildRange: number;
};

export type UnitDgunConfig = {
  turretBlueprintId: TurretBlueprintId;
  energyCost: number;
};

export type UnitSupportSurfaceNone = {
  kind: 'none';
};

export type UnitSupportSurfaceDiscTop = {
  kind: 'discTop';
  topZ: number;
  radius: number;
};

export type UnitSupportSurface = UnitSupportSurfaceNone | UnitSupportSurfaceDiscTop;

export type UnitProductionDomain = 'bot' | 'vehicle' | 'aircraft' | 'naval';

export type UnitProduction = {
  techLevel: 1 | 2;
  domains: UnitProductionDomain[];
};

export type UnitAnimalIdentity = {
  kind: 'animal';
  animalClass: 'mammal' | 'bird' | 'insect' | 'arachnid' | 'reptile' | 'amphibian' | 'fish' | 'mollusk' | 'dinosaur';
};

export type UnitConstructionCraftIdentity = {
  kind: 'constructionCraft';
};

export type UnitIdentity = UnitAnimalIdentity | UnitConstructionCraftIdentity;

export type UnitBlueprint = {
  unitBlueprintId: UnitBlueprintId;
  name: string;
  identity: UnitIdentity;
  shortName: string;
  tinyName: string;
  base: EntityBaseLedger;
  hp: number;
  radius: UnitRadiusConfig;
  supportSurface: UnitSupportSurface;
  mass: number;
  cost: ResourceCost;
  turrets: TurretMount[];
  bodyShape: UnitBodyShape | null;
  teamOrnament: TeamOrnamentFit;
  hud: EntityHudBlueprint;
  unitLocomotion: UnitLocomotionBlueprint;
  production: UnitProduction | null;
  suspension: UnitSuspensionConfig | null;
  builder: UnitBuilderConfig | null;
  constructionRate?: number | null;
  allowedBuildBlueprintIds?: StructureBlueprintId[] | null;
  factoryProducedUnitBlueprintId?: UnitBlueprintId | null;
  workEmitter?: WorkEmitterSpec | null;
  dgun: UnitDgunConfig | null;
  deathSound: SoundEntry | null;
  includeLockOnLevel0FriendsAndEnemies: TurretLockOnRelationshipInclusion[];
  includeLockOnLevel0Entities: TurretLockOnEntityFamilyInclusion[];
  includeLockOnLevel1Buildings: string[];
  includeLockOnLevel1Units: string[];
  includeLockOnLevel1Turrets: string[];
  includeLockOnLevel1Shots: string[];
  lockOnRequiresTargetLockedOntoSelf: LockOnRequiresTargetLockedOntoSelf;
  preventLockOnIfMyTeamIsAboveMe?: boolean;
  supportPointOffsetZ: number;
};

export type RayType = 'beam';

export type EmissionKind = 'shot' | 'ray' | 'shield';

export type BeamRayBlueprint = {
  type: 'beam';
  dps: number;
  force: number;
  recoil: number;
  radius: number;
  width: number;
  damageSphere: ShotCollision;
  gravityForceMultiplier: number;
  mediumTrajectory: EmissionMediumTrajectoryMatrix;
  continuousSound: BeamContinuousSoundConfig;
  hitSound: SoundEntry | null;
  rayBlueprintId: RayBlueprintId;
};

export type BeamContinuousSoundConfig = {
  harmonicSeriesIndex: number;
};

export type ShieldBlueprint = {
  type: 'shield';
  materialId: ShieldMaterialId;
  angle: number;
  transitionTime: number;
  reflection: ShieldReflectionPolicy;
  barrier: ShieldBarrierRatioConfig | null;
  mediumTrajectory: EmissionMediumTrajectoryMatrix;
  hitSound: SoundEntry | null;
  shieldBlueprintId: ShieldBlueprintId;
};

export type RayBlueprint = BeamRayBlueprint;

export type BeamRay = {
  type: 'beam';
  dps: number;
  force: number;
  recoil: number;
  radius: number;
  width: number;
  damageSphere: ShotCollision;
  gravityForceMultiplier: number;
  mediumTrajectory: EmissionMediumTrajectoryMatrix;
  rayBlueprintId: RayBlueprintId;
};

export type RayConfig = BeamRay;

export type ShieldConfig = {
  type: 'shield';
  material: ShieldMaterialBlueprint;
  angle: number;
  transitionTime: number;
  reflection: ShieldReflectionPolicy;
  mediumTrajectory: EmissionMediumTrajectoryMatrix;
  barrier?: ShieldBarrierConfig;
  shieldBlueprintId: ShieldBlueprintId;
};

export type EmissionConfig = ProjectileShot | BeamRay | ShieldConfig;

export type LocomotionMount = {
  xUnitRadiusRatio: number;
  yUnitRadiusRatio: number;
  zUnitRadiusRatio: number;
};

export type FlipperMount = {
  offset: LocomotionMount;
  lengthFrac: number;
};

export type DroneFanMount = {
  offset: LocomotionMount;
  radiusFrac: number;
  ringTubeRadiusFrac: number;
  outwardAngleDeg: number;
};

export type AirframeSurface = {
  offset: LocomotionMount;
  span: number;
  chord: number;
  thickness: number;
  dihedralDeg: number;
  sweepFrac: number;
  mirrorX: boolean;
};

export type AirframeJetMount = {
  offset: LocomotionMount;
};

export type SubmarinePectoralMount = {
  offset: LocomotionMount;
};

export type SubmarineRearFan = {
  offset: LocomotionMount;
  radius: number;
  ringTubeRadius: number;
  spinRadPerSec: number;
};
