// Generated by scripts/generateBlueprintSchemaTypes.mjs from src/game/sim/blueprints/blueprintSchema.json.
// Do not edit this file directly.
import type { SoundEntry } from './audio';
import type { RayBlueprintId, ShieldBlueprintId, ShieldMaterialId, ShotBlueprintId, StructureBlueprintId, TurretBlueprintId, UnitBlueprintId } from './blueprintIds';
import type { TurretRangeOverrides } from './combatTypes';
import type { BarrelShape } from './config';
import type { ConstructionEmitterSize, ConstructionEmitterVisualSpec } from './constructionTypes';
import type { ResourceCost } from './economyTypes';
import type { EntityId, PlayerId } from './entityTypes';
import type { UnitSuspensionConfig } from './unitLocomotionTypes';

export type TurretRangeVolume = 'turret-range-cylinder-normal' | 'turret-range-bottom-unbounded' | 'turret-range-top-water-and-bottom-unbounded' | 'turret-range-top-and-bottom-unbounded' | 'turret-range-sphere';

export type SensorCapabilityConfig = {
  fullSightRadius: number;
  radarRadius: number;
  detectorRadius: number;
  trackingRadius: number;
  scanRadius: number;
};

export type ProjectileShotKind = 'plasma' | 'rocket' | 'missile';

export type ShotLocomotionMotionModel = 'ballistic' | 'thrustGuided' | 'constantSpeedGuided' | 'terrainFollowing';

export type ShotLocomotionTerminalOutcome = 'detonate' | 'despawn';

export type ShotLocomotionTransitionOutcome = 'continue' | 'continueBallistic' | 'detonate' | 'despawn';

export type ShotLocomotionMediumPhysics = {
  operational: boolean;
  propulsionForce: number;
  guidanceThrust: number;
  turnRate: number;
  velocityFrictionPer60HzFrame: number;
};

export type ShotLocomotionGroundPhysics = {
  mode: 'impact' | 'terrainFollowing';
};

export type ShotLocomotionMedia = {
  air: ShotLocomotionMediumPhysics;
  water: ShotLocomotionMediumPhysics;
  ground: ShotLocomotionGroundPhysics;
};

export type ShotLocomotionTransitions = {
  enterWater: ShotLocomotionTransitionOutcome;
  exitWater: ShotLocomotionTransitionOutcome;
};

export type ShotLocomotionTerminalPolicy = {
  entityImpact: ShotLocomotionTerminalOutcome;
  groundContact: ShotLocomotionTerminalOutcome;
  expiry: ShotLocomotionTerminalOutcome;
  destroyed: ShotLocomotionTerminalOutcome;
  reflectorImpact: ShotLocomotionTerminalOutcome;
};

export type ShotLocomotion = {
  presetId: string;
  motionModel: ShotLocomotionMotionModel;
  maxLifespanMs: number | null;
  gravityForceMultiplier: number;
  guidanceDelayMs: number;
  media: ShotLocomotionMedia;
  transitions: ShotLocomotionTransitions;
  terminal: ShotLocomotionTerminalPolicy;
};

export type ShieldSurfaceResponse = 'reflect' | 'absorb' | 'passThrough';

export type ShieldReflectionMode = 'outside-in' | 'inside-out' | 'both';

export type ShieldReflectionDirection = 'reflect-none' | 'reflect-outside' | 'reflect-inside' | 'reflect-both';

export type ShieldReflectionEntity = 'plasma' | 'rocket' | 'missile' | 'beam' | 'laser';

export type ShieldReflectionEntityDirections = {
  plasma?: ShieldReflectionDirection;
  rocket?: ShieldReflectionDirection;
  missile?: ShieldReflectionDirection;
  beam?: ShieldReflectionDirection;
  laser?: ShieldReflectionDirection;
};

export type ShieldReflectionPolicy = {
  entities: ShieldReflectionEntityDirections;
};

export type ShieldBarrierShape = 'sphere' | 'infiniteVerticalCylinder' | 'aimedCylinder';

export type ShieldBarrierRatioConfig = {
  shape: ShieldBarrierShape;
  outerRatio?: number | null;
  rimWidth?: number | null;
  originOffsetRadiusRatio?: number | null;
};

export type TurretSubmunitionEmitterConfig = {
  shotBlueprintId: ShotBlueprintId;
  launchForce: number;
  cooldown: TurretCooldownConfig;
  spread: TurretSpreadConfig;
};

export type ShieldMaterialVisualConfig = {
  color: number;
  alpha: number;
  particleAlpha: number;
};

export type ShieldMaterialReflectionConfig = {
  mode: ShieldReflectionMode;
  reflectivity: number;
};

export type ShieldMaterialProjectileResponseConfig = {
  plasma: ShieldSurfaceResponse;
  rocket: ShieldSurfaceResponse;
  beam: ShieldSurfaceResponse;
  laser: ShieldSurfaceResponse;
};

export type ShieldMaterialHitReactionConfig = {
  impactEvent: 'shieldImpact';
  sound: SoundEntry | null;
};

export type ShieldMaterialBlueprint = {
  materialId: ShieldMaterialId;
  reflection: ShieldMaterialReflectionConfig;
  projectileResponse: ShieldMaterialProjectileResponseConfig;
  hitReaction: ShieldMaterialHitReactionConfig;
  visual: ShieldMaterialVisualConfig;
};

export type ShotCollision = {
  radius: number;
};

export type ShotExplosion = {
  radius: number;
  damage: number;
  force: number;
};

export type SubmunitionSpec = {
  shotBlueprintId: ShotBlueprintId;
  count: number;
  randomSpreadSpeedHorizontal: number;
  randomSpreadSpeedVertical: number;
  reflectedVelocityDamper?: number;
};

export type SmokeTrailSpec = {
  useId?: string;
  maxPoolSize?: number;
  capPolicy: 'evictOldest' | 'skipWhenFull';
  emitFramesSkip?: number;
  exhaustSpeed?: number;
  startRadius?: number;
  endRadiusMultiplier?: number;
  fadeInMs?: number;
  fadeOutMs?: number;
  maxAlpha?: number;
  color?: number;
};

export type ProjectileShotBlueprint = {
  type: ProjectileShotKind;
  shotBlueprintId: ShotBlueprintId;
  name: string;
  base: EntityBaseLedger;
  mass: number;
  health: number;
  radius: EntityRadiusConfig;
  shotLocomotionPresetId: string;
  hitSound: SoundEntry | null;
  submunitions: SubmunitionSpec | null;
  smokeTrail: SmokeTrailSpec | null;
};

export type ShotBlueprint = ProjectileShotBlueprint;

export type ProjectileTailShape = 'cone' | 'cylinder' | 'none';

export type ShieldBarrierConfig = {
  shape: ShieldBarrierShape;
  innerRange: number;
  outerRange: number;
  originOffsetZ: number;
  color: number;
  alpha: number;
  particleAlpha: number;
};

export type ProjectileShot = {
  type: ProjectileShotKind;
  shotBlueprintId: ShotBlueprintId;
  base: EntityBaseLedger;
  mass: number;
  health: number;
  launchForce: number;
  radius: EntityRadiusConfig;
  explosion?: ShotExplosion;
  shotLocomotion: ShotLocomotion;
  trailLength?: number;
  submunitions?: SubmunitionSpec;
  smokeTrail?: SmokeTrailSpec;
};

export type ActiveProjectileShot = ProjectileShot | BeamRay | LaserRay;

export type ShotConfig = ProjectileShot;

export type ProjectileType = 'projectile' | 'beam' | 'laser';

export type BeamReflectorKind = 'shield';

export type BeamPoint = {
  x: number;
  y: number;
  z: number;
  vx: number;
  vy: number;
  vz: number;
  reflectorEntityId: EntityId | null;
  reflectorKind: BeamReflectorKind | null;
  reflectorPlayerId: PlayerId | null;
  normalX: number | null;
  normalY: number | null;
  normalZ: number | null;
};

export type ShotRuntimeType = 'plasma' | 'rocket' | 'missile' | 'beam' | 'laser';

export type ShotRuntimeProfile = {
  shotBlueprintId: string;
  type: ShotRuntimeType;
  projectileType: ProjectileType;
  isProjectile: boolean;
  isLine: boolean;
  isRocketLike: boolean;
  radius: EntityRadiusConfig;
  deathExplosionRadius: number;
  maxLifespan: number;
  detonateOnExpiry: boolean;
  hasExplosion: boolean;
  hasSubmunitions: boolean;
};

export type ShotVisualProfile = {
  projectileTailShape: ProjectileTailShape;
  projectileTailLengthMult: number;
  projectileTailRadiusMult: number;
  projectileFinSizeMult: number;
  smokeTrail?: SmokeTrailSpec;
  burnMarkWidth: number;
  lineRadius: number;
  lineDamageSphereRadius: number;
};

export type ShotProfile = {
  runtime: ShotRuntimeProfile;
  visual: ShotVisualProfile;
};

export type ShieldPanel = {
  offsetX: number;
  offsetY: number;
  angle: number;
};

export type EntityRadiusConfig = {
  other: number;
  hitbox: number;
  collision: number;
  shotArmingRadius?: number;
};

export type EntityDeathExplosion = {
  radius: number;
  force: number;
  damage: number;
};

export type EntityBaseLedger = {
  cost: ResourceCost;
  mass: number;
  health: number;
  deathExplosion: EntityDeathExplosion;
  radius: EntityRadiusConfig;
};

export type TurretRadiusConfig = EntityRadiusConfig;

export type TurretAimAngleType = 'rayDirect' | 'rayBisectTurretAndBody' | 'ballisticArcLow' | 'ballisticArcLowOnlyUnder' | 'ballisticArcHigh';

export type TurretAimStyle = {
  angleType: TurretAimAngleType;
};

export type TurretLockOnRelationshipInclusion = 'friendly_entities' | 'enemy_entities';

export type TurretLockOnEntityFamilyInclusion = 'buildings' | 'towers' | 'units' | 'turrets' | 'shots';

export type LockOnRequiresTargetLockedOntoSelf = 'ignore' | 'require' | 'preferReacquire' | 'preferHold';

export type LockOnInclusionObject = {
  includeLockOnLevel0FriendsAndEnemies: TurretLockOnRelationshipInclusion[];
  includeLockOnLevel0Entities: TurretLockOnEntityFamilyInclusion[];
  includeLockOnLevel1Buildings: string[];
  includeLockOnLevel1Towers: string[];
  includeLockOnLevel1Units: string[];
  includeLockOnLevel1Turrets: string[];
  includeLockOnLevel1Shots: string[];
  lockOnRequiresTargetLockedOntoSelf: LockOnRequiresTargetLockedOntoSelf;
};

export type WeaponKind = 'attack' | 'construction' | 'repair' | 'spawn' | 'resourcePylon';

export type SpawnProducedKind = 'buildingsAndTowers' | 'units';

export type ResourcePylonResource = 'metal' | 'energy';

export type ResourcePylonRole = 'construction' | 'extraction';

export type SpawnTurretConfig = {
  producedKind: SpawnProducedKind;
  producedBlueprintId: string | null;
  producesNanoframe: boolean;
  cooldownMs: number;
  launchForce: number;
};

export type ResourcePylonConfig = {
  resource: ResourcePylonResource;
  role: ResourcePylonRole;
  radius: number;
};

export type TurretSpreadConfig = {
  angle: number;
  pelletCount: number;
};

export type TurretBurstConfig = {
  count: number;
  delay: number;
};

export type TurretCooldownConfig = {
  duration: number;
  durationRandomness: number;
};

export type TurretAudioConfig = {
  fireSound: SoundEntry;
};

export type TurretBlueprint = {
  turretBlueprintId: TurretBlueprintId;
  name: string;
  kind: WeaponKind;
  range: number;
  rangeVolume: TurretRangeVolume;
  cooldown: TurretCooldownConfig | null;
  color: number;
  turretTurnAccel: number;
  turretDrag: number;
  barrel: BarrelShape;
  rangeMultiplierOverrides: TurretRangeOverrides;
  eventsSmooth: boolean;
  launchForce: number;
  addTurretVelocityToEmissionLaunch: boolean;
  isManualFire: boolean;
  passive: boolean;
  requiresNonObstructedLineOfSight: boolean;
  spread: TurretSpreadConfig | null;
  submunitions?: TurretSubmunitionEmitterConfig | null;
  burst: TurretBurstConfig | null;
  shieldPanels: ShieldPanel[];
  audio: TurretAudioConfig | null;
  radius: TurretRadiusConfig;
  headOnly: boolean;
  aimStyle: TurretAimStyle;
  verticalLauncher: boolean;
  requiresFullSight?: boolean;
  idlePitch: number;
  groundAimFraction: number | null;
  constructionEmitter: ConstructionEmitterVisualSpec | null;
  spawn?: SpawnTurretConfig | null;
  resourcePylon?: ResourcePylonConfig | null;
  includeLockOnLevel0FriendsAndEnemies: TurretLockOnRelationshipInclusion[];
  includeLockOnLevel0Entities: TurretLockOnEntityFamilyInclusion[];
  includeLockOnLevel1Buildings: string[];
  includeLockOnLevel1Towers: string[];
  includeLockOnLevel1Units: string[];
  includeLockOnLevel1Turrets: string[];
  includeLockOnLevel1Shots: string[];
  lockOnRequiresTargetLockedOntoSelf: LockOnRequiresTargetLockedOntoSelf;
  emissionKind: EmissionKind | null;
  emissionBlueprintId: string | null;
};

export type MountOffset = {
  x: number;
  y: number;
  z: number;
};

export type UnitTurretMountZResolver = {
  kind: 'topMounted';
  bodyTopZFrac: number;
};

export type TurretMount = {
  turretBlueprintId: TurretBlueprintId;
  mount: MountOffset;
  shieldPanels?: ShieldPanel[];
  hostDirected: boolean;
  requiredEngagedForFightStop: boolean;
  zResolver?: UnitTurretMountZResolver;
  visualVariant?: ConstructionEmitterSize;
  producedBlueprintId?: UnitBlueprintId;
  allowedBuildBlueprintIds?: StructureBlueprintId[];
  productionHoldAnchor?: 'host';
  constructionRate?: number;
};

export type BuildingTurretMount = {
  turretBlueprintId: TurretBlueprintId;
  mount: MountOffset;
  shieldPanels?: ShieldPanel[];
  hostDirected: boolean;
  visualVariant?: ConstructionEmitterSize;
};

export type WheelConfig = {
  wheelDistX: number;
  wheelDistY: number;
  treadLength: number;
  treadWidth: number;
  wheelRadius: number;
  rotationSpeed: number;
};

export type TreadConfig = {
  treadOffset: number;
  treadLength: number;
  treadWidth: number;
  wheelRadius: number;
  rotationSpeed: number;
};

export type LegLayoutEntry = {
  attachOffsetXFrac: number;
  attachOffsetYFrac: number;
  upperLegLengthFrac: number;
  lowerLegLengthFrac: number;
  snapTriggerAngle: number;
  snapTargetAngle: number;
  snapDistanceMultiplier: number;
  extensionThreshold: number;
};

export type LegConfig = {
  upperThickness: number;
  lowerThickness: number;
  hipRadius: number;
  kneeRadius: number;
  lerpDuration: number;
  leftSide: LegLayoutEntry[];
};

export type FlipperConfig = {
  frontOffsetXFrac: number;
  rearOffsetXFrac: number;
  lateralOffsetFrac: number;
  rootHeightFrac: number;
  frontLengthFrac: number;
  rearLengthFrac: number;
  rootChordFrac: number;
  tipChordFrac: number;
  thicknessFrac: number;
  groundDownAngleDeg: number;
  groundSweepAngleDeg: number;
  waterStrokeAngleDeg: number;
  cycleDistanceFrac: number;
};

export type SwimConfig = {
  pectoralOffsetXFrac: number;
  pectoralLateralOffsetFrac: number;
  pectoralHeightFrac: number;
  pectoralSpanFrac: number;
  pectoralRootChordFrac: number;
  pectoralTipChordFrac: number;
  rearFanOffsetXFrac: number;
  rearFanHeightFrac: number;
  rearFanRadius: number;
  rearFanRingTubeRadius: number;
  rearFanSpinRadPerSec: number;
  thicknessFrac: number;
  strokeAngleDeg: number;
  cycleDistanceFrac: number;
};

export type LocomotionLiftPhysics = {
  surfaceFollowingForceFromGround: number;
  surfaceFollowingForceFromWater?: number;
  buoyancyRatio: number;
};

export type LocomotionFluidBodyPhysics = {
  lift: LocomotionLiftPhysics;
};

export type UnitUnitLocomotionBlueprintPhysics = {
  air: LocomotionFluidBodyPhysics;
  water: LocomotionFluidBodyPhysics;
};

export type UnitLocomotionEnvironmentalHazardPolicy = {
  waterFatal: boolean;
  fatalSubmergedFraction: number;
  fatalExposureSeconds: number;
};

export type HoverConfig = {
  fanDistX: number;
  fanDistY: number;
  fanPositionRadius?: number;
  fanLayout?: 'quad' | 'triFront' | 'twin';
  fanRadius: number;
  fanRingTubeRadius: number;
  fanOutwardAngleDeg?: number;
  fanSpinRadPerSec?: number;
  tailFanOffsetX?: number;
  tailFanRadius?: number;
  tailFanRingTubeRadius?: number;
  tailFanBackAngleDeg?: number;
};

export type FlyingConfig = {
  wingEnabled?: boolean;
  wingSpan?: number;
  wingChord?: number;
  wingOffsetX?: number;
  wingHeight?: number;
  wingThickness?: number;
  wingDihedralDeg?: number;
  wingSweepFrac?: number;
  tailWingSpan?: number;
  tailWingChord?: number;
  tailWingOffsetX?: number;
  tailWingHeight?: number;
  tailWingThickness?: number;
  tailWingDihedralDeg?: number;
  tailWingSweepFrac?: number;
  tailWingMirrorX?: boolean;
  jetOffsetX: number;
  jetOffsetY: number;
  jetOffsetZ: number;
  jetRadius: number;
  jetLength: number;
  jetCount?: 1 | 2;
};

export type UnitLocomotionBlueprintWheels = {
  type: 'wheels';
  physicsPresetId: string;
  physics: UnitUnitLocomotionBlueprintPhysics;
  environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy;
  config: WheelConfig;
};

export type UnitLocomotionBlueprintTreads = {
  type: 'treads';
  physicsPresetId: string;
  physics: UnitUnitLocomotionBlueprintPhysics;
  environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy;
  config: TreadConfig;
};

export type UnitLocomotionBlueprintAmphibiousTreads = {
  type: 'amphibious-treads';
  physicsPresetId: string;
  physics: UnitUnitLocomotionBlueprintPhysics;
  environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy;
  config: TreadConfig;
};

export type UnitLocomotionBlueprintLegs = {
  type: 'legs';
  physicsPresetId: string;
  physics: UnitUnitLocomotionBlueprintPhysics;
  environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy;
  config: LegConfig;
};

export type UnitLocomotionBlueprintFlippers = {
  type: 'flippers';
  physicsPresetId: string;
  physics: UnitUnitLocomotionBlueprintPhysics;
  environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy;
  config: FlipperConfig;
};

export type UnitLocomotionBlueprintHover = {
  type: 'hover';
  physicsPresetId: string;
  physics: UnitUnitLocomotionBlueprintPhysics;
  environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy;
  config: HoverConfig;
};

export type UnitLocomotionBlueprintFlying = {
  type: 'flying';
  physicsPresetId: string;
  physics: UnitUnitLocomotionBlueprintPhysics;
  environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy;
  config: FlyingConfig;
};

export type UnitLocomotionBlueprintSubmarine = {
  type: 'submarine';
  physicsPresetId: string;
  physics: UnitUnitLocomotionBlueprintPhysics;
  environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy;
  config: SwimConfig;
};

export type UnitLocomotionBlueprintDive = {
  type: 'dive';
  physicsPresetId: string;
  physics: UnitUnitLocomotionBlueprintPhysics;
  environmentalHazards: UnitLocomotionEnvironmentalHazardPolicy;
  config: FlyingConfig;
};

export type UnitLocomotionBlueprint = UnitLocomotionBlueprintWheels | UnitLocomotionBlueprintTreads | UnitLocomotionBlueprintAmphibiousTreads | UnitLocomotionBlueprintLegs | UnitLocomotionBlueprintFlippers | UnitLocomotionBlueprintHover | UnitLocomotionBlueprintFlying | UnitLocomotionBlueprintSubmarine | UnitLocomotionBlueprintDive;

export type UnitBodyShapePartCircle = {
  kind: 'circle';
  offsetForward: number;
  offsetLateral?: number;
  radiusFrac: number;
  yFrac?: number;
  centerYFrac?: number;
};

export type UnitBodyShapePartOval = {
  kind: 'oval';
  offsetForward: number;
  offsetLateral?: number;
  xFrac: number;
  yFrac: number;
  zFrac: number;
};

export type UnitBodyShapePartCylinder = {
  kind: 'cylinder';
  offsetForward: number;
  offsetLateral?: number;
  lengthFrac: number;
  radiusFrac: number;
  centerYFrac?: number;
  pitchRad?: number;
};

export type UnitBodyShapePartCone = {
  kind: 'cone';
  offsetForward: number;
  offsetLateral?: number;
  lengthFrac: number;
  radiusFrac: number;
  centerYFrac?: number;
};

export type UnitBodyShapePart = UnitBodyShapePartCircle | UnitBodyShapePartOval | UnitBodyShapePartCylinder | UnitBodyShapePartCone;

export type UnitBodyShapePolygon = {
  kind: 'polygon';
  sides: number;
  radiusFrac: number;
  heightFrac: number;
  rotation: number;
  bevelEnabled?: boolean;
};

export type UnitBodyShapeRect = {
  kind: 'rect';
  lengthFrac: number;
  widthFrac: number;
  heightFrac: number;
};

export type UnitBodyShapeRhombus = {
  kind: 'rhombus';
  lengthFrac: number;
  widthFrac: number;
  heightFrac: number;
};

export type UnitBodyShapeCircle = {
  kind: 'circle';
  radiusFrac: number;
  yFrac?: number;
};

export type UnitBodyShapeOval = {
  kind: 'oval';
  xFrac: number;
  yFrac: number;
  zFrac: number;
};

export type UnitBodyShapeComposite = {
  kind: 'composite';
  parts: UnitBodyShapePart[];
};

export type UnitBodyShape = UnitBodyShapePolygon | UnitBodyShapeRect | UnitBodyShapeRhombus | UnitBodyShapeCircle | UnitBodyShapeOval | UnitBodyShapeComposite;

export type EntityHudBlueprint = {
  barsOffsetAboveTop: number;
};

export type UnitRadiusConfig = EntityRadiusConfig;

export type UnitBuilderConfig = {
  buildRange: number;
};

export type UnitDgunConfig = {
  turretBlueprintId: TurretBlueprintId;
  energyCost: number;
};

export type UnitSupportSurfaceNone = {
  kind: 'none';
};

export type UnitSupportSurfaceDiscTop = {
  kind: 'discTop';
  topZ: number;
  radius: number;
};

export type UnitSupportSurface = UnitSupportSurfaceNone | UnitSupportSurfaceDiscTop;

export type UnitBlueprint = {
  unitBlueprintId: UnitBlueprintId;
  name: string;
  shortName: string;
  base: EntityBaseLedger;
  hp: number;
  radius: UnitRadiusConfig;
  supportSurface: UnitSupportSurface;
  fullVisionRadius: number;
  sensors: SensorCapabilityConfig;
  mass: number;
  cost: ResourceCost;
  turrets: TurretMount[];
  bodyShape: UnitBodyShape;
  hud: EntityHudBlueprint;
  legAttachHeightFrac: number | null;
  unitLocomotion: UnitLocomotionBlueprint;
  suspension: UnitSuspensionConfig | null;
  builder: UnitBuilderConfig | null;
  dgun: UnitDgunConfig | null;
  deathSound: SoundEntry | null;
  includeLockOnLevel0FriendsAndEnemies: TurretLockOnRelationshipInclusion[];
  includeLockOnLevel0Entities: TurretLockOnEntityFamilyInclusion[];
  includeLockOnLevel1Buildings: string[];
  includeLockOnLevel1Towers: string[];
  includeLockOnLevel1Units: string[];
  includeLockOnLevel1Turrets: string[];
  includeLockOnLevel1Shots: string[];
  lockOnRequiresTargetLockedOntoSelf: LockOnRequiresTargetLockedOntoSelf;
  preventLockOnIfMyTeamIsAboveMe?: boolean;
  supportPointOffsetZ: number;
};

export type RayType = 'beam' | 'laser';

export type EmissionKind = 'shot' | 'ray' | 'shield';

export type BeamRayBlueprint = {
  type: 'beam';
  dps: number;
  force: number;
  recoil: number;
  radius: number;
  width: number;
  damageSphere: ShotCollision;
  gravityForceMultiplier: number;
  continuousSound: BeamContinuousSoundConfig;
  hitSound: SoundEntry | null;
  rayBlueprintId: RayBlueprintId;
};

export type BeamContinuousSoundConfig = {
  harmonicSeriesIndex: number;
};

export type LaserRayBlueprint = {
  type: 'laser';
  dps: number;
  force: number;
  recoil: number;
  radius: number;
  width: number;
  damageSphere: ShotCollision;
  duration: number;
  gravityForceMultiplier: number;
  hitSound: SoundEntry | null;
  rayBlueprintId: RayBlueprintId;
};

export type ShieldBlueprint = {
  type: 'shield';
  materialId: ShieldMaterialId;
  angle: number;
  transitionTime: number;
  reflection: ShieldReflectionPolicy;
  barrier: ShieldBarrierRatioConfig | null;
  hitSound: SoundEntry | null;
  shieldBlueprintId: ShieldBlueprintId;
};

export type RayBlueprint = BeamRayBlueprint | LaserRayBlueprint;

export type BeamRay = {
  type: 'beam';
  dps: number;
  force: number;
  recoil: number;
  radius: number;
  width: number;
  damageSphere: ShotCollision;
  gravityForceMultiplier: number;
  rayBlueprintId: RayBlueprintId;
};

export type LaserRay = {
  type: 'laser';
  dps: number;
  force: number;
  recoil: number;
  radius: number;
  width: number;
  damageSphere: ShotCollision;
  duration: number;
  gravityForceMultiplier: number;
  rayBlueprintId: RayBlueprintId;
};

export type RayConfig = BeamRay | LaserRay;

export type ShieldConfig = {
  type: 'shield';
  material: ShieldMaterialBlueprint;
  angle: number;
  transitionTime: number;
  reflection: ShieldReflectionPolicy;
  barrier?: ShieldBarrierConfig;
  shieldBlueprintId: ShieldBlueprintId;
};

export type EmissionConfig = ProjectileShot | BeamRay | LaserRay | ShieldConfig;
