// Network type definitions — re-exported from canonical @/types/network

export type {
  NetworkMessage,
  NetworkLockstepMessage,
  LockstepProtocolVersion,
  LockstepProtocolBase,
  LockstepPeerSequenceAck,
  LockstepHelloMessage,
  LockstepReadyMessage,
  LockstepCommandMessage,
  LockstepCommandFrameMessage,
  LockstepAckMessage,
  LockstepChecksumMessage,
  LockstepPauseMessage,
  LockstepResumeMessage,
  LockstepDesyncMessage,
  LockstepResyncRequestMessage,
  NetworkCommunicationDraft,
  NetworkCommunicationEvent,
  NetworkCommunicationChatEvent,
  NetworkCommunicationMapDrawingEvent,
  NetworkCommunicationMapEraseEvent,
  NetworkCommunicationPoint,
  NetworkServerSnapshotSimEvent,
  NetworkServerSnapshotProjectileSpawn,
  NetworkServerSnapshotProjectileDespawn,
  NetworkServerSnapshotVelocityUpdate,
  NetworkServerSnapshotMinimapEntity,
  NetworkServerSnapshotScanPulse,
  NetworkServerSnapshotShroud,
  NetworkServerSnapshotBeamPoint,
  NetworkServerSnapshotBeamUpdate,
  NetworkServerSnapshotGridCell,
  NetworkServerSnapshotMeta,
  NetworkServerSnapshot,
  NetworkServerSnapshotSprayTarget,
  NetworkServerSnapshotAction,
  NetworkServerSnapshotTurret,
  NetworkServerSnapshotEntity,
  NetworkServerSnapshotEconomy,
  NetworkServerSnapshotResourceMovement,
  LobbyPlayerInfoPayload,
  LobbySettings,
  LobbyPlayer,
  NetworkRole,
  BattleHandoff,
  GamePhase,
} from '@/types/network';

export { BATTLE_HANDOFF_PROTOCOL, LOCKSTEP_PROTOCOL_VERSION } from '@/types/network';
