use serde_json::Value;
use std::{
    env, fs,
    path::{Path, PathBuf},
};

struct BlueprintObjectTable {
    relative_path: &'static str,
    json_const: &'static str,
    ids_const: &'static str,
    count_const: &'static str,
    validate_entry_id: bool,
}

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is required"));
    generate_shared_sim_constants(&manifest_dir);
    generate_blueprint_tables(&manifest_dir);
}

fn generate_shared_sim_constants(manifest_dir: &Path) {
    let constants_path = manifest_dir.join("../src/sharedSimConstants.json");
    rerun_if_changed(&constants_path);

    let raw = fs::read_to_string(&constants_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", constants_path.display()));
    let fields = [
        ("gravity", "GRAVITY"),
        ("unitGroundContactEpsilon", "UNIT_GROUND_CONTACT_EPSILON"),
        (
            "unitGroundSpringAccelPerWorldUnit",
            "UNIT_GROUND_SPRING_ACCEL_PER_WORLD_UNIT",
        ),
        (
            "unitGroundPassiveReboundMaxSpeed",
            "UNIT_GROUND_PASSIVE_REBOUND_MAX_SPEED",
        ),
        ("bodySleepSpeedSq", "SLEEP_SPEED_SQ"),
        ("bodySleepAccelSq", "SLEEP_ACCEL_SQ"),
        ("bodySleepTicks", "SLEEP_TICKS"),
        (
            "bodySleepGroundPenetrationEps",
            "SLEEP_GROUND_PENETRATION_EPS",
        ),
    ];

    let mut generated = String::from(
        "// Generated by rts-sim-wasm/build.rs from src/sharedSimConstants.json.\n\
         // Do not edit this file directly.\n",
    );
    for (json_field, rust_const) in fields {
        let value = read_number_field(&raw, json_field).unwrap_or_else(|| {
            panic!(
                "missing numeric {json_field} in {}",
                constants_path.display()
            )
        });
        generated.push_str(&format!("const {rust_const}: f64 = {value:?};\n"));
    }
    let spring_accel = read_number_field(&raw, "unitGroundSpringAccelPerWorldUnit")
        .expect("unitGroundSpringAccelPerWorldUnit was already validated");
    let spring_damping_ratio = read_number_field(&raw, "unitGroundSpringDampingRatio")
        .unwrap_or_else(|| {
            panic!(
                "missing numeric unitGroundSpringDampingRatio in {}",
                constants_path.display()
            )
        });
    let damping = spring_damping_ratio.max(0.0) * 2.0 * spring_accel.max(0.0).sqrt();
    generated.push_str(&format!(
        "const GROUND_SPRING_DAMPING_ACCEL_PER_SPEED: f64 = {damping:?};\n"
    ));
    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is required"))
        .join("shared_sim_constants.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
}

fn generate_blueprint_tables(manifest_dir: &Path) {
    let tables = [
        BlueprintObjectTable {
            relative_path: "../src/game/sim/blueprints/units.json",
            json_const: "BLUEPRINT_UNITS_JSON",
            ids_const: "BLUEPRINT_UNIT_IDS",
            count_const: "BLUEPRINT_UNITS_COUNT",
            validate_entry_id: true,
        },
        BlueprintObjectTable {
            relative_path: "../src/game/sim/blueprints/buildings.json",
            json_const: "BLUEPRINT_BUILDINGS_JSON",
            ids_const: "BLUEPRINT_BUILDING_IDS",
            count_const: "BLUEPRINT_BUILDINGS_COUNT",
            validate_entry_id: true,
        },
        BlueprintObjectTable {
            relative_path: "../src/game/sim/blueprints/turrets.json",
            json_const: "BLUEPRINT_TURRETS_JSON",
            ids_const: "BLUEPRINT_TURRET_IDS",
            count_const: "BLUEPRINT_TURRETS_COUNT",
            validate_entry_id: true,
        },
        BlueprintObjectTable {
            relative_path: "../src/game/sim/blueprints/shots.json",
            json_const: "BLUEPRINT_SHOTS_JSON",
            ids_const: "BLUEPRINT_SHOT_IDS",
            count_const: "BLUEPRINT_SHOTS_COUNT",
            validate_entry_id: true,
        },
        BlueprintObjectTable {
            relative_path: "../src/game/sim/blueprints/locomotion.json",
            json_const: "BLUEPRINT_LOCOMOTION_JSON",
            ids_const: "BLUEPRINT_LOCOMOTION_IDS",
            count_const: "BLUEPRINT_LOCOMOTION_COUNT",
            validate_entry_id: false,
        },
        BlueprintObjectTable {
            relative_path: "../src/game/sim/blueprints/pathfindingConfig.json",
            json_const: "BLUEPRINT_PATHFINDING_JSON",
            ids_const: "BLUEPRINT_PATHFINDING_IDS",
            count_const: "BLUEPRINT_PATHFINDING_COUNT",
            validate_entry_id: true,
        },
        BlueprintObjectTable {
            relative_path: "../src/game/sim/blueprints/fallbacks.json",
            json_const: "BLUEPRINT_FALLBACKS_JSON",
            ids_const: "BLUEPRINT_FALLBACK_KEYS",
            count_const: "BLUEPRINT_FALLBACKS_COUNT",
            validate_entry_id: false,
        },
    ];

    let mut generated = String::from(
        "// Generated by rts-sim-wasm/build.rs from src/game/sim/blueprints/*.json.\n\
         // Do not edit this file directly.\n",
    );

    for table in tables {
        emit_blueprint_object_table(&mut generated, manifest_dir, &table);
    }
    emit_unit_roster_table(&mut generated, manifest_dir);

    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is required"))
        .join("blueprint_tables.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
}

fn read_number_field(raw: &str, field: &str) -> Option<f64> {
    let key = format!("\"{field}\"");
    let key_start = raw.find(&key)?;
    let after_key = &raw[key_start + key.len()..];
    let colon = after_key.find(':')?;
    let after_colon = after_key[colon + 1..].trim_start();
    let end = after_colon
        .find(|ch: char| !matches!(ch, '-' | '+' | '.' | '0'..='9' | 'e' | 'E'))
        .unwrap_or(after_colon.len());
    after_colon[..end].parse::<f64>().ok()
}

fn emit_blueprint_object_table(
    generated: &mut String,
    manifest_dir: &Path,
    table: &BlueprintObjectTable,
) {
    let path = manifest_dir.join(table.relative_path);
    rerun_if_changed(&path);
    let raw = fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
    let json = parse_json(&raw, &path);
    let object = json
        .as_object()
        .unwrap_or_else(|| panic!("{} must contain a top-level JSON object", path.display()));

    let mut ids = object.keys().cloned().collect::<Vec<_>>();
    ids.sort();

    if table.validate_entry_id {
        for id in &ids {
            let entry = object
                .get(id)
                .and_then(Value::as_object)
                .unwrap_or_else(|| panic!("{} entry {id:?} must be an object", path.display()));
            let entry_id = entry.get("id").and_then(Value::as_str).unwrap_or_else(|| {
                panic!(
                    "{} entry {id:?} must have a string id field",
                    path.display()
                )
            });
            if entry_id != id {
                panic!(
                    "{} entry key {id:?} does not match id field {entry_id:?}",
                    path.display()
                );
            }
        }
    }

    generated.push_str(&format!(
        "pub const {}: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}\"));\n",
        table.json_const, table.relative_path
    ));
    generated.push_str(&format!(
        "pub const {}: usize = {};\n",
        table.count_const,
        ids.len()
    ));
    generated.push_str(&format!(
        "pub const {}: [&str; {}] = {};\n\n",
        table.ids_const,
        ids.len(),
        rust_str_array_literal(&ids)
    ));
}

fn emit_unit_roster_table(generated: &mut String, manifest_dir: &Path) {
    let relative_path = "../src/game/sim/blueprints/unitRoster.json";
    let path = manifest_dir.join(relative_path);
    rerun_if_changed(&path);
    let raw = fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
    let json = parse_json(&raw, &path);
    let buildable = read_string_array_field(&json, "buildableUnitIds", &path);
    let disabled = read_string_array_field(&json, "defaultDisabledDemoUnitIds", &path);

    generated.push_str(&format!(
        "pub const BLUEPRINT_UNIT_ROSTER_JSON: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}\"));\n",
        relative_path
    ));
    generated.push_str(&format!(
        "pub const BLUEPRINT_BUILDABLE_UNIT_COUNT: usize = {};\n",
        buildable.len()
    ));
    generated.push_str(&format!(
        "pub const BLUEPRINT_BUILDABLE_UNIT_IDS: [&str; {}] = {};\n",
        buildable.len(),
        rust_str_array_literal(&buildable)
    ));
    generated.push_str(&format!(
        "pub const BLUEPRINT_DEFAULT_DISABLED_DEMO_UNIT_COUNT: usize = {};\n",
        disabled.len()
    ));
    generated.push_str(&format!(
        "pub const BLUEPRINT_DEFAULT_DISABLED_DEMO_UNIT_IDS: [&str; {}] = {};\n",
        disabled.len(),
        rust_str_array_literal(&disabled)
    ));
}

fn read_string_array_field(json: &Value, field: &str, path: &Path) -> Vec<String> {
    json.get(field)
        .and_then(Value::as_array)
        .unwrap_or_else(|| panic!("{} missing array field {field:?}", path.display()))
        .iter()
        .enumerate()
        .map(|(index, value)| {
            value
                .as_str()
                .unwrap_or_else(|| {
                    panic!(
                        "{} field {field:?} entry {index} must be a string",
                        path.display()
                    )
                })
                .to_owned()
        })
        .collect()
}

fn parse_json(raw: &str, path: &Path) -> Value {
    serde_json::from_str(raw)
        .unwrap_or_else(|err| panic!("failed to parse {}: {err}", path.display()))
}

fn rerun_if_changed(path: &Path) {
    println!("cargo:rerun-if-changed={}", path.display());
}

fn rust_str_array_literal(values: &[String]) -> String {
    let mut out = String::from("[");
    for (index, value) in values.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("{value:?}"));
    }
    out.push(']');
    out
}
