use serde_json::Value;
use std::{
    env, fs,
    path::{Path, PathBuf},
};

struct BlueprintObjectTable {
    relative_path: &'static str,
    json_const: &'static str,
    ids_const: &'static str,
    count_const: &'static str,
    entry_id_field: Option<&'static str>,
}

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is required"));
    generate_shared_sim_constants(&manifest_dir);
    generate_pathfinding_tuning(&manifest_dir);
    generate_wind_config(&manifest_dir);
    generate_wire_enums(&manifest_dir);
    generate_blueprint_tables(&manifest_dir);
}

/// Generate the Rust side of the wire/state enum codes from
/// src/wireEnums.json. TypeScript imports the same JSON directly, so the
/// numeric codes that cross the JS/WASM boundary have one source of truth
/// and cannot drift between the two languages.
fn generate_wire_enums(manifest_dir: &Path) {
    let enums_path = manifest_dir.join("../src/wireEnums.json");
    rerun_if_changed(&enums_path);
    let raw = fs::read_to_string(&enums_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", enums_path.display()));
    let json = parse_json(&raw, &enums_path);

    // (json pointer, Rust const name, Rust type, visibility prefix). Only
    // the codes Rust actually consumes are emitted; `entityChanged.combatMode`
    // is TypeScript-only (no Rust changed-field handling), so it is left out
    // here while still living in the shared JSON.
    let consts: &[(&str, &str, &str, &str)] = &[
        ("/turretState/idle", "CT_TURRET_STATE_IDLE", "u8", "pub "),
        (
            "/turretState/tracking",
            "CT_TURRET_STATE_TRACKING",
            "u8",
            "pub ",
        ),
        (
            "/turretState/engaged",
            "CT_TURRET_STATE_ENGAGED",
            "u8",
            "pub ",
        ),
        (
            "/combatHaltMode/anyEngaged",
            "CT_COMBAT_HALT_MODE_ANY_ENGAGED",
            "u8",
            "pub ",
        ),
        (
            "/combatHaltMode/fightRequired",
            "CT_COMBAT_HALT_MODE_FIGHT_REQUIRED",
            "u8",
            "pub ",
        ),
        ("/entityChanged/pos", "ENTITY_CHANGED_POS", "u32", ""),
        ("/entityChanged/rot", "ENTITY_CHANGED_ROT", "u32", ""),
        ("/entityChanged/vel", "ENTITY_CHANGED_VEL", "u32", ""),
        ("/entityChanged/hp", "ENTITY_CHANGED_HP", "u32", ""),
        (
            "/entityChanged/actions",
            "ENTITY_CHANGED_ACTIONS",
            "u32",
            "",
        ),
        (
            "/entityChanged/turrets",
            "ENTITY_CHANGED_TURRETS",
            "u32",
            "",
        ),
        (
            "/entityChanged/building",
            "ENTITY_CHANGED_BUILDING",
            "u32",
            "",
        ),
        (
            "/entityChanged/factory",
            "ENTITY_CHANGED_FACTORY",
            "u32",
            "",
        ),
        ("/entityChanged/normal", "ENTITY_CHANGED_NORMAL", "u32", ""),
    ];

    let mut generated = String::from(
        "// Generated by rts-sim-wasm/build.rs from src/wireEnums.json.\n\
         // Do not edit this file directly.\n",
    );
    for (pointer, name, ty, vis) in consts {
        let value = json
            .pointer(pointer)
            .and_then(Value::as_i64)
            .unwrap_or_else(|| panic!("missing integer {pointer} in {}", enums_path.display()));
        generated.push_str(&format!("{vis}const {name}: {ty} = {value};\n"));
    }

    let out_path =
        PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is required")).join("wire_enums.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
}

fn generate_shared_sim_constants(manifest_dir: &Path) {
    let constants_path = manifest_dir.join("../src/sharedSimConstants.json");
    rerun_if_changed(&constants_path);

    let raw = fs::read_to_string(&constants_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", constants_path.display()));
    let fields = [
        ("gravity", "GRAVITY"),
        ("unitGroundContactEpsilon", "UNIT_GROUND_CONTACT_EPSILON"),
        (
            "unitGroundSpringAccelPerWorldUnit",
            "UNIT_GROUND_SPRING_ACCEL_PER_WORLD_UNIT",
        ),
        (
            "unitGroundPassiveReboundMaxSpeed",
            "UNIT_GROUND_PASSIVE_REBOUND_MAX_SPEED",
        ),
        ("bodySleepSpeedSq", "SLEEP_SPEED_SQ"),
        ("bodySleepAccelSq", "SLEEP_ACCEL_SQ"),
        ("bodySleepTicks", "SLEEP_TICKS"),
        (
            "bodySleepGroundPenetrationEps",
            "SLEEP_GROUND_PENETRATION_EPS",
        ),
    ];

    let mut generated = String::from(
        "// Generated by rts-sim-wasm/build.rs from src/sharedSimConstants.json.\n\
         // Do not edit this file directly.\n",
    );
    for (json_field, rust_const) in fields {
        let value = read_number_field(&raw, json_field).unwrap_or_else(|| {
            panic!(
                "missing numeric {json_field} in {}",
                constants_path.display()
            )
        });
        generated.push_str(&format!("const {rust_const}: f64 = {value:?};\n"));
    }
    let spring_accel = read_number_field(&raw, "unitGroundSpringAccelPerWorldUnit")
        .expect("unitGroundSpringAccelPerWorldUnit was already validated");
    let spring_damping_ratio = read_number_field(&raw, "unitGroundSpringDampingRatio")
        .unwrap_or_else(|| {
            panic!(
                "missing numeric unitGroundSpringDampingRatio in {}",
                constants_path.display()
            )
        });
    let damping = spring_damping_ratio.max(0.0) * 2.0 * spring_accel.max(0.0).sqrt();
    generated.push_str(&format!(
        "const GROUND_SPRING_DAMPING_ACCEL_PER_SPEED: f64 = {damping:?};\n"
    ));
    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is required"))
        .join("shared_sim_constants.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
}

fn generate_pathfinding_tuning(manifest_dir: &Path) {
    let config_path = manifest_dir.join("../src/game/sim/pathfindingTuningConfig.json");
    rerun_if_changed(&config_path);

    let raw = fs::read_to_string(&config_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", config_path.display()));
    let water_buffer_cells = read_number_field(&raw, "waterBufferCells").unwrap_or_else(|| {
        panic!(
            "missing numeric waterBufferCells in {}",
            config_path.display()
        )
    });
    if water_buffer_cells < 0.0 || water_buffer_cells.fract() != 0.0 {
        panic!(
            "invalid waterBufferCells in {}: expected non-negative integer, got {}",
            config_path.display(),
            water_buffer_cells
        );
    }
    let stability_max_slope_deg =
        read_number_field(&raw, "stabilityMaxSlopeDeg").unwrap_or_else(|| {
            panic!(
                "missing numeric stabilityMaxSlopeDeg in {}",
                config_path.display()
            )
        });
    if stability_max_slope_deg <= 0.0 || stability_max_slope_deg >= 90.0 {
        panic!(
            "invalid stabilityMaxSlopeDeg in {}: expected degrees in (0, 90), got {}",
            config_path.display(),
            stability_max_slope_deg
        );
    }
    let stability_min_normal_z = stability_max_slope_deg.to_radians().cos() as f32;

    let mut generated = String::from(
        "// Generated by rts-sim-wasm/build.rs from src/game/sim/pathfindingTuningConfig.json.\n\
         // Do not edit this file directly.\n",
    );
    generated.push_str(&format!(
        "const PATHFINDING_WATER_BUFFER_CELLS: i32 = {};\n",
        water_buffer_cells as i32
    ));
    generated.push_str(&format!(
        "const PATHFINDING_STABILITY_MIN_NORMAL_Z: f32 = {:?};\n",
        stability_min_normal_z
    ));

    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is required"))
        .join("pathfinding_tuning.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
}

fn generate_wind_config(manifest_dir: &Path) {
    let config_path = manifest_dir.join("../src/windConfig.json");
    rerun_if_changed(&config_path);
    let raw = fs::read_to_string(&config_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", config_path.display()));
    let json = parse_json(&raw, &config_path);

    let fields = [
        ("/speed/min", "WIND_SPEED_MIN"),
        ("/speed/max", "WIND_SPEED_MAX"),
        (
            "/directionOscillationPeriodsSeconds/primary",
            "WIND_DIRECTION_PERIOD_PRIMARY",
        ),
        (
            "/directionOscillationPeriodsSeconds/secondary",
            "WIND_DIRECTION_PERIOD_SECONDARY",
        ),
        (
            "/directionOscillationPeriodsSeconds/tertiary",
            "WIND_DIRECTION_PERIOD_TERTIARY",
        ),
        (
            "/speedOscillationPeriodsSeconds/primary",
            "WIND_SPEED_PERIOD_PRIMARY",
        ),
        (
            "/speedOscillationPeriodsSeconds/secondary",
            "WIND_SPEED_PERIOD_SECONDARY",
        ),
        (
            "/speedOscillationPeriodsSeconds/tertiary",
            "WIND_SPEED_PERIOD_TERTIARY",
        ),
        (
            "/vertical/maxFractionOfHorizontalSpeed",
            "WIND_VERTICAL_MAX_FRACTION_OF_HORIZONTAL_SPEED",
        ),
        (
            "/vertical/oscillationPeriodsSeconds/primary",
            "WIND_VERTICAL_PERIOD_PRIMARY",
        ),
        (
            "/vertical/oscillationPeriodsSeconds/secondary",
            "WIND_VERTICAL_PERIOD_SECONDARY",
        ),
    ];

    let mut generated = String::from(
        "// Generated by rts-sim-wasm/build.rs from src/windConfig.json.\n\
         // Do not edit this file directly.\n",
    );
    for (pointer, rust_const) in fields {
        let value = json
            .pointer(pointer)
            .and_then(Value::as_f64)
            .unwrap_or_else(|| panic!("missing numeric {pointer} in {}", config_path.display()));
        generated.push_str(&format!("const {rust_const}: f64 = {value:?};\n"));
    }

    let out_path =
        PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is required")).join("wind_config.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
}

fn generate_blueprint_tables(manifest_dir: &Path) {
    let tables = [
        BlueprintObjectTable {
            relative_path: "../src/game/sim/blueprints/units.json",
            json_const: "BLUEPRINT_UNITS_JSON",
            ids_const: "BLUEPRINT_UNIT_IDS",
            count_const: "BLUEPRINT_UNITS_COUNT",
            entry_id_field: Some("unitBlueprintId"),
        },
        BlueprintObjectTable {
            relative_path: "../src/game/sim/blueprints/buildings.json",
            json_const: "BLUEPRINT_BUILDINGS_JSON",
            ids_const: "BLUEPRINT_BUILDING_IDS",
            count_const: "BLUEPRINT_BUILDINGS_COUNT",
            entry_id_field: Some("buildingBlueprintId"),
        },
        BlueprintObjectTable {
            relative_path: "../src/game/sim/blueprints/towers.json",
            json_const: "BLUEPRINT_TOWERS_JSON",
            ids_const: "BLUEPRINT_TOWER_IDS",
            count_const: "BLUEPRINT_TOWERS_COUNT",
            entry_id_field: Some("buildingBlueprintId"),
        },
        BlueprintObjectTable {
            relative_path: "../src/game/sim/blueprints/turrets.json",
            json_const: "BLUEPRINT_TURRETS_JSON",
            ids_const: "BLUEPRINT_TURRET_BLUEPRINT_IDS",
            count_const: "BLUEPRINT_TURRETS_COUNT",
            entry_id_field: Some("turretBlueprintId"),
        },
        BlueprintObjectTable {
            relative_path: "../src/game/sim/blueprints/shots.json",
            json_const: "BLUEPRINT_SHOTS_JSON",
            ids_const: "BLUEPRINT_SHOT_BLUEPRINT_IDS",
            count_const: "BLUEPRINT_SHOTS_COUNT",
            entry_id_field: Some("shotBlueprintId"),
        },
        BlueprintObjectTable {
            relative_path: "../src/game/sim/blueprints/rays.json",
            json_const: "BLUEPRINT_RAYS_JSON",
            ids_const: "BLUEPRINT_RAY_BLUEPRINT_IDS",
            count_const: "BLUEPRINT_RAYS_COUNT",
            entry_id_field: Some("rayBlueprintId"),
        },
        BlueprintObjectTable {
            relative_path: "../src/game/sim/blueprints/shields.json",
            json_const: "BLUEPRINT_SHIELDS_JSON",
            ids_const: "BLUEPRINT_SHIELD_BLUEPRINT_IDS",
            count_const: "BLUEPRINT_SHIELDS_COUNT",
            entry_id_field: Some("shieldBlueprintId"),
        },
        BlueprintObjectTable {
            relative_path: "../src/game/sim/blueprints/shieldMaterials.json",
            json_const: "BLUEPRINT_SHIELD_MATERIALS_JSON",
            ids_const: "BLUEPRINT_SHIELD_MATERIAL_IDS",
            count_const: "BLUEPRINT_SHIELD_MATERIALS_COUNT",
            entry_id_field: Some("materialId"),
        },
        BlueprintObjectTable {
            relative_path: "../src/game/sim/blueprints/pathfindingConfig.json",
            json_const: "BLUEPRINT_PATHFINDING_JSON",
            ids_const: "BLUEPRINT_PATHFINDING_IDS",
            count_const: "BLUEPRINT_PATHFINDING_COUNT",
            entry_id_field: Some("pathfindingBlueprintId"),
        },
        BlueprintObjectTable {
            relative_path: "../src/game/sim/blueprints/fallbacks.json",
            json_const: "BLUEPRINT_FALLBACKS_JSON",
            ids_const: "BLUEPRINT_FALLBACK_KEYS",
            count_const: "BLUEPRINT_FALLBACKS_COUNT",
            entry_id_field: None,
        },
    ];

    let mut generated = String::from(
        "// Generated by rts-sim-wasm/build.rs from src/game/sim/blueprints/*.json.\n\
         // Do not edit this file directly.\n",
    );

    for table in tables {
        emit_blueprint_object_table(&mut generated, manifest_dir, &table);
    }
    emit_unit_roster_table(&mut generated, manifest_dir);

    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is required"))
        .join("blueprint_tables.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
}

fn read_number_field(raw: &str, field: &str) -> Option<f64> {
    let key = format!("\"{field}\"");
    let key_start = raw.find(&key)?;
    let after_key = &raw[key_start + key.len()..];
    let colon = after_key.find(':')?;
    let after_colon = after_key[colon + 1..].trim_start();
    let end = after_colon
        .find(|ch: char| !matches!(ch, '-' | '+' | '.' | '0'..='9' | 'e' | 'E'))
        .unwrap_or(after_colon.len());
    after_colon[..end].parse::<f64>().ok()
}

fn emit_blueprint_object_table(
    generated: &mut String,
    manifest_dir: &Path,
    table: &BlueprintObjectTable,
) {
    let path = manifest_dir.join(table.relative_path);
    rerun_if_changed(&path);
    let raw = fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
    let json = parse_json(&raw, &path);
    let object = json
        .as_object()
        .unwrap_or_else(|| panic!("{} must contain a top-level JSON object", path.display()));

    let mut ids = object
        .keys()
        .filter(|id| !id.starts_with('$'))
        .cloned()
        .collect::<Vec<_>>();
    ids.sort();

    if let Some(entry_id_field) = table.entry_id_field {
        for id in &ids {
            let entry = object
                .get(id)
                .and_then(Value::as_object)
                .unwrap_or_else(|| panic!("{} entry {id:?} must be an object", path.display()));
            let entry_id = entry
                .get(entry_id_field)
                .and_then(Value::as_str)
                .unwrap_or_else(|| {
                    panic!(
                        "{} entry {id:?} must have a string {entry_id_field} field",
                        path.display(),
                    )
                });
            if entry_id != id {
                panic!(
                    "{} entry key {id:?} does not match {entry_id_field} field {entry_id:?}",
                    path.display(),
                );
            }
        }
    }

    generated.push_str(&format!(
        "pub const {}: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}\"));\n",
        table.json_const, table.relative_path
    ));
    generated.push_str(&format!(
        "pub const {}: usize = {};\n",
        table.count_const,
        ids.len()
    ));
    generated.push_str(&format!(
        "pub const {}: [&str; {}] = {};\n\n",
        table.ids_const,
        ids.len(),
        rust_str_array_literal(&ids)
    ));
}

fn emit_unit_roster_table(generated: &mut String, manifest_dir: &Path) {
    let relative_path = "../src/game/sim/blueprints/unitRoster.json";
    let path = manifest_dir.join(relative_path);
    rerun_if_changed(&path);
    let raw = fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
    let json = parse_json(&raw, &path);
    let buildable = read_string_array_field(&json, "buildableUnitIds", &path);
    let disabled = read_string_array_field(&json, "defaultDisabledDemoUnitIds", &path);

    generated.push_str(&format!(
        "pub const BLUEPRINT_UNIT_ROSTER_JSON: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}\"));\n",
        relative_path
    ));
    generated.push_str(&format!(
        "pub const BLUEPRINT_BUILDABLE_UNIT_COUNT: usize = {};\n",
        buildable.len()
    ));
    generated.push_str(&format!(
        "pub const BLUEPRINT_BUILDABLE_UNIT_BLUEPRINT_IDS: [&str; {}] = {};\n",
        buildable.len(),
        rust_str_array_literal(&buildable)
    ));
    generated.push_str(&format!(
        "pub const BLUEPRINT_DEFAULT_DISABLED_DEMO_UNIT_COUNT: usize = {};\n",
        disabled.len()
    ));
    generated.push_str(&format!(
        "pub const BLUEPRINT_DEFAULT_DISABLED_DEMO_UNIT_BLUEPRINT_IDS: [&str; {}] = {};\n",
        disabled.len(),
        rust_str_array_literal(&disabled)
    ));
}

fn read_string_array_field(json: &Value, field: &str, path: &Path) -> Vec<String> {
    json.get(field)
        .and_then(Value::as_array)
        .unwrap_or_else(|| panic!("{} missing array field {field:?}", path.display()))
        .iter()
        .enumerate()
        .map(|(index, value)| {
            value
                .as_str()
                .unwrap_or_else(|| {
                    panic!(
                        "{} field {field:?} entry {index} must be a string",
                        path.display()
                    )
                })
                .to_owned()
        })
        .collect()
}

fn parse_json(raw: &str, path: &Path) -> Value {
    serde_json::from_str(raw)
        .unwrap_or_else(|err| panic!("failed to parse {}: {err}", path.display()))
}

fn rerun_if_changed(path: &Path) {
    println!("cargo:rerun-if-changed={}", path.display());
}

fn rust_str_array_literal(values: &[String]) -> String {
    let mut out = String::from("[");
    for (index, value) in values.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("{value:?}"));
    }
    out.push(']');
    out
}
