use std::{env, fs, path::PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(
        env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is required"),
    );
    let constants_path = manifest_dir.join("../src/sharedSimConstants.json");
    println!("cargo:rerun-if-changed={}", constants_path.display());

    let raw = fs::read_to_string(&constants_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", constants_path.display()));
    let fields = [
        ("gravity", "GRAVITY"),
        ("unitGroundContactEpsilon", "UNIT_GROUND_CONTACT_EPSILON"),
        (
            "unitGroundSpringAccelPerWorldUnit",
            "UNIT_GROUND_SPRING_ACCEL_PER_WORLD_UNIT",
        ),
        (
            "unitGroundPassiveReboundMaxSpeed",
            "UNIT_GROUND_PASSIVE_REBOUND_MAX_SPEED",
        ),
        ("bodySleepSpeedSq", "SLEEP_SPEED_SQ"),
        ("bodySleepAccelSq", "SLEEP_ACCEL_SQ"),
        ("bodySleepTicks", "SLEEP_TICKS"),
        (
            "bodySleepGroundPenetrationEps",
            "SLEEP_GROUND_PENETRATION_EPS",
        ),
    ];

    let mut generated = String::from(
        "// Generated by rts-sim-wasm/build.rs from src/sharedSimConstants.json.\n\
         // Do not edit this file directly.\n",
    );
    for (json_field, rust_const) in fields {
        let value = read_number_field(&raw, json_field).unwrap_or_else(|| {
            panic!(
                "missing numeric {json_field} in {}",
                constants_path.display()
            )
        });
        generated.push_str(&format!("const {rust_const}: f64 = {value:?};\n"));
    }
    let spring_accel = read_number_field(&raw, "unitGroundSpringAccelPerWorldUnit")
        .expect("unitGroundSpringAccelPerWorldUnit was already validated");
    let spring_damping_ratio = read_number_field(&raw, "unitGroundSpringDampingRatio")
        .unwrap_or_else(|| {
            panic!(
                "missing numeric unitGroundSpringDampingRatio in {}",
                constants_path.display()
            )
        });
    let damping = spring_damping_ratio.max(0.0) * 2.0 * spring_accel.max(0.0).sqrt();
    generated.push_str(&format!(
        "const GROUND_SPRING_DAMPING_ACCEL_PER_SPEED: f64 = {damping:?};\n"
    ));
    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is required"))
        .join("shared_sim_constants.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
}

fn read_number_field(raw: &str, field: &str) -> Option<f64> {
    let key = format!("\"{field}\"");
    let key_start = raw.find(&key)?;
    let after_key = &raw[key_start + key.len()..];
    let colon = after_key.find(':')?;
    let after_colon = after_key[colon + 1..].trim_start();
    let end = after_colon
        .find(|ch: char| !matches!(ch, '-' | '+' | '.' | '0'..='9' | 'e' | 'E'))
        .unwrap_or(after_colon.len());
    after_colon[..end].parse::<f64>().ok()
}
