import type { MapLandCellDimensions } from '../mapSizeConfig';
import type { BattlePreset } from './battlePresets';
import type {
  AudioScope,
  CameraFollowMode,
  CameraFovDegrees,
  CameraSmoothMode,
  CameraViewMode,
  DriftMode,
  EntityHudElement,
  EntityHudToggles,
  EntityHudType,
  LodMode,
  MasterVolumePercent,
  PathingDebugUnitId,
  ProjRangeType,
  RangeType,
  SelectionHudMode,
  SoundCategory,
  UnitRadiusType,
  WaypointDetail,
  WaterBoundaryMode,
} from '../types/client';
import type { SnapshotRate, TickRate } from '../types/server';
import type { UnitGroundNormalEmaMode } from '../shellConfig';
import type { SlopePathMode } from '../types/slopePathMode';
import type { RenderMode } from '../types/graphics';
import type { CommandHotkeyPresetId } from '../game/input/commandHotkeys';

export type ControlBarStyle = Record<string, string>;

export type GameCanvasBattleControlBarModel = {
  readonly isReadonly: boolean;
  readonly barStyle: ControlBarStyle;
  readonly battleLabel: string;
  readonly battleElapsed: string;
  readonly allDemoUnitsActive: boolean;
  readonly demoUnitBlueprintIds: readonly string[];
  readonly currentAllowedUnits: readonly string[];
  readonly currentAllowedUnitsSet: ReadonlySet<string>;
  readonly allDemoBuildingsActive: boolean;
  readonly demoBuildingBlueprintIds: readonly string[];
  readonly currentAllowedBuildingsSet: ReadonlySet<string>;
  readonly allDemoTowersActive: boolean;
  readonly demoTowerBlueprintIds: readonly string[];
  readonly currentAllowedTowersSet: ReadonlySet<string>;
  readonly displayUnitCap: number;
  readonly gameStarted: boolean;
  readonly mapWidthLandCells: number;
  readonly mapLengthLandCells: number;
  readonly centerMagnitude: number;
  readonly dividersMagnitude: number;
  readonly perimeterMagnitude: number;
  readonly terrainDTerrain: number;
  readonly plateauWallSlopeDegrees: number;
  readonly watersEdgeBeachSlopeDegrees: number;
  readonly watersEdgeCliffHeight: number;
  readonly metalDepositStep: number;
  readonly terrainDetail: number;
  readonly terrainTextureSmoothing: number;
  readonly terrainLightSmoothing: number;
  readonly terrainTextureSmoothAcrossWallBoundary: boolean;
  readonly terrainLightSmoothAcrossWallBoundary: boolean;
  readonly terrainSplitWallBoundaryVertices: boolean;
  readonly displayUnitCount: number;
  readonly currentForceFieldsVisible: boolean;
  readonly currentShieldsObstructSight: boolean;
  readonly currentFogOfWarEnabled: boolean;
  readonly currentSlopePathMode: SlopePathMode;
  readonly currentConverterTax: number;
  readonly serverUnitGroundNormalEmaMode: UnitGroundNormalEmaMode;
  readonly presets: readonly BattlePreset[];
  readonly activePresetName: string | null;
  applyPreset(preset: BattlePreset): void;
  resetDemoDefaults(): void;
  toggleAllDemoUnits(): void;
  toggleDemoUnitBlueprintId(unitBlueprintId: string): void;
  toggleAllDemoBuildings(): void;
  toggleDemoBuildingBlueprintId(buildingBlueprintId: string): void;
  toggleAllDemoTowers(): void;
  toggleDemoTowerBlueprintId(towerBlueprintId: string): void;
  changeMaxTotalUnits(cap: number): void;
  applyMapLandDimensions(dimensions: MapLandCellDimensions): void;
  applyCenterMagnitude(value: number): void;
  applyDividersMagnitude(value: number): void;
  applyPerimeterMagnitude(value: number): void;
  applyTerrainDTerrain(value: number): void;
  applyPlateauWallSlopeDegrees(value: number): void;
  applyWatersEdgeBeachSlopeDegrees(value: number): void;
  applyWatersEdgeCliffHeight(value: number): void;
  applyMetalDepositStep(value: number): void;
  applyTerrainDetail(value: number): void;
  applyTerrainTextureSmoothing(value: number): void;
  applyTerrainLightSmoothing(value: number): void;
  toggleTerrainTextureSmoothAcrossWallBoundary(): void;
  toggleTerrainLightSmoothAcrossWallBoundary(): void;
  toggleTerrainSplitWallBoundaryVertices(): void;
  setForceFieldsVisible(enabled: boolean): void;
  setShieldsObstructSight(enabled: boolean): void;
  setFogOfWarEnabled(enabled: boolean): void;
  setSlopePathMode(mode: SlopePathMode): void;
  setConverterTax(tax: number): void;
  setUnitGroundNormalEmaModeValue(mode: UnitGroundNormalEmaMode): void;
};

export type GameCanvasServerControlBarModel = {
  readonly isReadonly: boolean;
  readonly barStyle: ControlBarStyle;
  readonly serverLabel: string;
  readonly displayServerTime: string;
  readonly displayServerIp: string;
  readonly displayServerTpsAvg: number;
  readonly displayServerTpsWorst: number;
  readonly displayServerCpuAvg: number;
  readonly displayServerCpuHi: number;
};

export type GameCanvasClientControlBarModel = {
  readonly barStyle: ControlBarStyle;
  readonly clientLabel: string;
  readonly playerClientEnabled: boolean;
  readonly displayedClientTime: string;
  readonly displayedClientIp: string;
  readonly waypointDetail: WaypointDetail;
  readonly entityHud: Readonly<EntityHudToggles>;
  readonly selectionHudMode: SelectionHudMode;
  readonly commandHotkeyPreset: CommandHotkeyPresetId;
  readonly commandHotkeyRevision: number;
  readonly entityHudTypes: readonly EntityHudType[];
  readonly entityHudElements: readonly EntityHudElement[];
  readonly logicMsAvg: number;
  readonly logicMsHi: number;
  readonly renderMsAvg: number;
  readonly renderMsHi: number;
  readonly displayGpuMs: number;
  readonly gpuSourceLabel: string;
  readonly gpuTimerSupported: boolean;
  readonly runtimeProfile: string;
  readonly nativePixelRatio: number;
  readonly activePixelRatio: number;
  readonly dynamicPixelRatioEnabled: boolean;
  readonly webglBufferProfilerSupported: boolean;
  readonly webglRendererRenderMs: number;
  readonly webglDrawCalls: number;
  readonly webglTriangles: number;
  readonly webglPoints: number;
  readonly webglLines: number;
  readonly webglGeometries: number;
  readonly webglTextures: number;
  readonly webglBufferDataCalls: number;
  readonly webglBufferSubDataCalls: number;
  readonly webglBufferUploadBytes: number;
  readonly rendererContextMainCount: number;
  readonly rendererContextAuxiliaryCount: number;
  readonly rendererContextAuxiliaryBudget: number;
  readonly rendererContextDeniedAuxiliaryCount: number;
  readonly hudSpriteActiveCount: number;
  readonly hudSpriteRetainedCount: number;
  readonly hudSpritePeakCount: number;
  readonly hudSpriteDisposedCount: number;
  readonly hudSpriteBudgetCount: number;
  readonly scopedRetainedUnitMeshes: number;
  readonly scopedRetainedBuildingMeshes: number;
  readonly scopedMeshHiddenPerSec: number;
  readonly scopedMeshReactivatedPerSec: number;
  readonly scopedMeshDestroyPerSec: number;
  readonly scopedMeshRebuildPerSec: number;
  readonly frameMsAvg: number;
  readonly frameMsHi: number;
  readonly longtaskSupported: boolean;
  readonly longtaskMsPerSec: number;
  readonly renderTpsAvg: number;
  readonly renderTpsWorst: number;
  readonly currentZoom: number;
  readonly snapAvgRate: number;
  readonly snapWorstRate: number;
  readonly rawSnapshotReceivedRate: number;
  readonly rawSnapshotAppliedRate: number;
  readonly richSnapAvgRate: number;
  readonly richSnapWorstRate: number;
  readonly deltaSnapAvgRate: number;
  readonly deltaSnapWorstRate: number;
  readonly entityDeltaSnapAvgRate: number;
  readonly entityDeltaSnapWorstRate: number;
  readonly projectileDeltaSnapAvgRate: number;
  readonly projectileDeltaSnapWorstRate: number;
  readonly displayTickRate: TickRate;
  readonly displaySnapshotRate: SnapshotRate;
  readonly snapshotSizeAvgBytes: number;
  readonly snapshotSizeHiBytes: number;
  readonly richSnapshotSizeAvgBytes: number;
  readonly richSnapshotSizeHiBytes: number;
  readonly deltaSnapshotSizeAvgBytes: number;
  readonly deltaSnapshotSizeHiBytes: number;
  readonly entityDeltaSnapshotSizeAvgBytes: number;
  readonly entityDeltaSnapshotSizeHiBytes: number;
  readonly projectileDeltaSnapshotSizeAvgBytes: number;
  readonly projectileDeltaSnapshotSizeHiBytes: number;
  readonly snapshotApplyAvgMs: number;
  readonly snapshotApplyHiMs: number;
  readonly richSnapshotApplyAvgMs: number;
  readonly richSnapshotApplyHiMs: number;
  readonly deltaSnapshotApplyAvgMs: number;
  readonly deltaSnapshotApplyHiMs: number;
  readonly entityDeltaSnapshotApplyAvgMs: number;
  readonly entityDeltaSnapshotApplyHiMs: number;
  readonly projectileDeltaSnapshotApplyAvgMs: number;
  readonly projectileDeltaSnapshotApplyHiMs: number;
  readonly audioSmoothing: boolean;
  readonly burnMarks: boolean;
  readonly locomotionMarks: boolean;
  readonly smokeTrails: boolean;
  readonly smokeSoftEdges: boolean;
  readonly fogShade: boolean;
  readonly materialExplosions: boolean;
  readonly clientUnitGroundNormalEmaMode: DriftMode;
  readonly allPanActive: boolean;
  readonly dragPanEnabled: boolean;
  readonly showServerControls: boolean;
  readonly triangleDebug: boolean;
  readonly wallTriangleDebug: boolean;
  readonly buildGridDebug: boolean;
  readonly airLiftProbeDebug: boolean;
  readonly metalMap: boolean;
  readonly elevationMap: boolean;
  readonly pathingMap: boolean;
  readonly pathingDebugUnit: PathingDebugUnitId;
  readonly renderMode: RenderMode;
  readonly audioScope: AudioScope;
  readonly masterVolume: MasterVolumePercent;
  readonly allSoundsActive: boolean;
  readonly soundToggles: Readonly<Record<SoundCategory, boolean>>;
  readonly sfxCategories: readonly SoundCategory[];
  readonly soundLabels: Readonly<Record<SoundCategory, string>>;
  readonly soundTooltips: Readonly<Record<SoundCategory, string>>;
  readonly allRangesActive: boolean;
  readonly rangeToggles: Readonly<Record<RangeType, boolean>>;
  readonly allProjRangesActive: boolean;
  readonly projRangeToggles: Readonly<Record<ProjRangeType, boolean>>;
  readonly allUnitRadiiActive: boolean;
  readonly unitRadiusToggles: Readonly<Record<UnitRadiusType, boolean>>;
  readonly legsRadiusToggle: boolean;
  readonly lodMode: LodMode;
  readonly cameraFovDegrees: CameraFovDegrees;
  readonly cameraSmoothMode: CameraSmoothMode;
  readonly cameraFollowMode: CameraFollowMode;
  readonly waterBoundaryMode: WaterBoundaryMode;
  readonly fullscreenActive: boolean;
  readonly uiChromeVisible: boolean;
  readonly mapDetailsVisible: boolean;
  readonly optionsMenuOpen: boolean;
  resetClientDefaults(): void;
  togglePlayerClientEnabled(): void;
  changeWaypointDetail(mode: WaypointDetail): void;
  toggleEntityHud(type: EntityHudType, element: EntityHudElement): void;
  changeSelectionHudMode(mode: SelectionHudMode): void;
  changeCommandHotkeyPreset(presetId: CommandHotkeyPresetId): void;
  refreshCommandHotkeys(): void;
  toggleAudioSmoothing(): void;
  toggleBurnMarks(): void;
  toggleLocomotionMarks(): void;
  toggleSmokeTrails(): void;
  toggleSmokeSoftEdges(): void;
  toggleFogShade(): void;
  toggleMaterialExplosions(): void;
  changeClientUnitGroundNormalEmaMode(mode: DriftMode): void;
  toggleAllPan(): void;
  toggleDragPan(): void;
  toggleTriangleDebug(): void;
  toggleWallTriangleDebug(): void;
  toggleBuildGridDebug(): void;
  toggleAirLiftProbeDebug(): void;
  toggleMetalMap(): void;
  toggleElevationMap(): void;
  togglePathingMap(): void;
  changePathingDebugUnit(unitBlueprintId: PathingDebugUnitId): void;
  changeRenderMode(mode: RenderMode): void;
  changeAudioScope(scope: AudioScope): void;
  changeMasterVolume(volume: MasterVolumePercent): void;
  setGamePaused(paused: boolean): void;
  toggleAllSounds(): void;
  toggleSoundCategory(category: SoundCategory): void;
  toggleAllRanges(): void;
  toggleRange(type: RangeType): void;
  toggleAllProjRanges(): void;
  toggleProjRange(type: ProjRangeType): void;
  toggleAllUnitRadii(): void;
  toggleUnitRadius(type: UnitRadiusType): void;
  toggleLegsRadius(): void;
  changeLodMode(mode: LodMode): void;
  changeCameraFovDegrees(fov: CameraFovDegrees): void;
  changeWaterBoundaryMode(mode: WaterBoundaryMode): void;
  setCameraMode(mode: CameraSmoothMode): void;
  setCameraViewMode(mode: CameraViewMode): void;
  setCameraFollowMode(mode: CameraFollowMode): void;
  showMapOverview(): void;
  flipCameraYaw(): void;
  setCameraAnchor(index: number): void;
  focusCameraAnchor(index: number): void;
  toggleFullscreen(): void;
  captureScreenshot(): void;
  goToLastPing(): void;
  toggleUiChrome(): void;
  toggleMapDetails(): void;
  toggleOptionsMenu(): void;
};
