import {
  ENTITY_CHANGED_BUILDING,
  ENTITY_CHANGED_HP,
  ENTITY_CHANGED_NORMAL,
  ENTITY_CHANGED_POS,
  ENTITY_CHANGED_ROT,
  ENTITY_CHANGED_VEL,
} from '../../types/network';
const ENTITY_MOTION_DELTA_FIELDS =
  ENTITY_CHANGED_POS |
  ENTITY_CHANGED_ROT |
  ENTITY_CHANGED_VEL |
  ENTITY_CHANGED_NORMAL;

export const ENTITY_BASIC_TRANSFORM_DELTA_FIELDS =
  ENTITY_CHANGED_POS |
  ENTITY_CHANGED_ROT;

export const ENTITY_UNIT_SLAB_DELTA_FIELDS =
  ENTITY_MOTION_DELTA_FIELDS |
  ENTITY_CHANGED_HP |
  ENTITY_CHANGED_BUILDING;
