import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const schemaPath = path.join(root, 'src/game/sim/blueprints/blueprintSchema.json');
const tsOutPath = path.join(root, 'src/types/blueprintSchema.generated.ts');
const rustOutPath = path.join(root, 'rts-sim-wasm/src/generated_blueprint_schema.rs');

const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf8'));
const defs = schema.$defs ?? {};

function codegen(def) {
  return def['x-codegen'] ?? null;
}

function isExternal(def) {
  return Boolean(codegen(def)?.tsImport || codegen(def)?.rustType);
}

function refName(ref) {
  const prefix = '#/$defs/';
  if (!ref.startsWith(prefix)) {
    throw new Error(`Unsupported $ref ${ref}`);
  }
  return ref.slice(prefix.length);
}

function resolveRef(ref) {
  const name = refName(ref);
  const def = defs[name];
  if (!def) throw new Error(`Unknown $ref ${ref}`);
  return { name, def };
}

function isIdentifier(value) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value);
}

function tsPropName(value) {
  return isIdentifier(value) ? value : JSON.stringify(value);
}

function indent(level) {
  return '  '.repeat(level);
}

function tsLiteral(value) {
  return typeof value === 'string' ? JSON.stringify(value).replace(/"/g, "'") : JSON.stringify(value);
}

function tsType(node, level = 0) {
  if (node.$ref) return refName(node.$ref);
  if (Object.prototype.hasOwnProperty.call(node, 'const')) return tsLiteral(node.const);
  if (Array.isArray(node.enum)) return node.enum.map(tsLiteral).join(' | ');
  if (node.oneOf) {
    return flattenUnion(node.oneOf).map((entry) => tsType(entry, level)).join(' | ');
  }
  if (Array.isArray(node.type)) {
    return node.type.map((entry) => tsType({ ...node, type: entry }, level)).join(' | ');
  }
  switch (node.type) {
    case 'null':
      return 'null';
    case 'boolean':
      return 'boolean';
    case 'integer':
    case 'number':
      return 'number';
    case 'string':
      return 'string';
    case 'array':
      return `${wrapTsArrayType(tsType(node.items ?? {}, level))}[]`;
    case 'object':
      return tsObjectType(node, level);
    default:
      return 'unknown';
  }
}

function flattenUnion(entries) {
  const flattened = [];
  for (const entry of entries) {
    if (entry.oneOf) {
      flattened.push(...flattenUnion(entry.oneOf));
    } else {
      flattened.push(entry);
    }
  }
  return flattened;
}

function wrapTsArrayType(type) {
  return type.includes(' | ') || type.startsWith('{') ? `(${type})` : type;
}

function tsObjectType(node, level) {
  const props = node.properties ?? {};
  const propNames = Object.keys(props);
  if (propNames.length === 0) {
    if (node.additionalProperties && typeof node.additionalProperties === 'object') {
      return `Record<string, ${tsType(node.additionalProperties, level)}>`;
    }
    return 'Record<string, unknown>';
  }
  const required = new Set(node.required ?? []);
  const lines = ['{'];
  for (const name of propNames) {
    const optional = required.has(name) ? '' : '?';
    lines.push(`${indent(level + 1)}${tsPropName(name)}${optional}: ${tsType(props[name], level + 1)};`);
  }
  lines.push(`${indent(level)}}`);
  return lines.join('\n');
}

function collectTsImports() {
  const importsByModule = new Map();
  for (const def of Object.values(defs)) {
    const tsImport = codegen(def)?.tsImport;
    if (!tsImport) continue;
    const names = importsByModule.get(tsImport.module) ?? new Set();
    names.add(tsImport.name);
    importsByModule.set(tsImport.module, names);
  }
  return [...importsByModule.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([module, names]) => `import type { ${[...names].sort().join(', ')} } from '${module}';`);
}

function generateTs() {
  const lines = [
    '// Generated by scripts/generateBlueprintSchemaTypes.mjs from src/game/sim/blueprints/blueprintSchema.json.',
    '// Do not edit this file directly.',
    ...collectTsImports(),
    '',
  ];

  for (const [name, def] of Object.entries(defs)) {
    if (isExternal(def)) continue;
    lines.push(`export type ${name} = ${tsType(def, 0)};`);
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function rustType(node) {
  if (node.$ref) {
    const { name, def } = resolveRef(node.$ref);
    return codegen(def)?.rustType ?? name;
  }
  if (Object.prototype.hasOwnProperty.call(node, 'const')) return rustConstType(node.const);
  if (Array.isArray(node.enum)) return rustInlineEnumType(node.enum);
  if (node.oneOf) {
    const entries = flattenUnion(node.oneOf);
    const nonNull = entries.filter((entry) => entry.type !== 'null');
    if (nonNull.length === 1 && nonNull.length !== entries.length) {
      return `Option<${rustType(nonNull[0])}>`;
    }
    return 'BlueprintJsonValue';
  }
  if (Array.isArray(node.type)) {
    const nonNull = node.type.filter((entry) => entry !== 'null');
    if (nonNull.length === 1 && nonNull.length !== node.type.length) {
      return `Option<${rustType({ ...node, type: nonNull[0] })}>`;
    }
    return 'BlueprintJsonValue';
  }
  switch (node.type) {
    case 'null':
      return '()';
    case 'boolean':
      return 'bool';
    case 'integer':
      return 'i32';
    case 'number':
      return 'f64';
    case 'string':
      return 'String';
    case 'array':
      return `Vec<${rustType(node.items ?? {})}>`;
    case 'object':
      if (node.properties && Object.keys(node.properties).length > 0) return 'BlueprintJsonValue';
      if (node.additionalProperties && typeof node.additionalProperties === 'object') {
        return `BTreeMap<String, ${rustType(node.additionalProperties)}>`;
      }
      return 'BlueprintJsonValue';
    default:
      return 'BlueprintJsonValue';
  }
}

function rustConstType(value) {
  switch (typeof value) {
    case 'boolean':
      return 'bool';
    case 'number':
      return Number.isInteger(value) ? 'i32' : 'f64';
    case 'string':
      return 'String';
    default:
      return 'BlueprintJsonValue';
  }
}

function rustInlineEnumType(values) {
  const scalarType = typeof values[0];
  if (values.every((value) => typeof value === scalarType)) {
    if (scalarType === 'number') return values.every(Number.isInteger) ? 'i32' : 'f64';
    if (scalarType === 'boolean') return 'bool';
    if (scalarType === 'string') return 'String';
  }
  return 'BlueprintJsonValue';
}

function rustFieldName(name) {
  if (name === 'type') return 'r#type';
  return name.replace(/[^A-Za-z0-9_]/g, '_');
}

function rustVariantName(value) {
  const source = String(value)
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .trim();
  const out = source
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => `${part[0].toUpperCase()}${part.slice(1)}`)
    .join('');
  return /^[0-9]/.test(out) ? `Value${out}` : out;
}

function generateRustDef(name, def) {
  const cg = codegen(def);
  if (cg?.rustType) {
    return `pub type ${name} = ${cg.rustType};`;
  }
  if (Array.isArray(def.enum)) {
    if (!def.enum.every((value) => typeof value === 'string')) {
      return `pub type ${name} = ${rustInlineEnumType(def.enum)};`;
    }
    const variants = def.enum.map((value) => `    ${rustVariantName(value)},`).join('\n');
    return `#[derive(Clone, Debug, PartialEq)]\npub enum ${name} {\n${variants}\n}`;
  }
  if (def.oneOf) {
    const entries = flattenUnion(def.oneOf);
    const nonNull = entries.filter((entry) => entry.type !== 'null');
    if (nonNull.length === 1 && nonNull.length !== entries.length) {
      return `pub type ${name} = Option<${rustType(nonNull[0])}>;`;
    }
    const variants = entries.map((entry) => {
      if (!entry.$ref) return `    Value(${rustType(entry)}),`;
      const variantName = refName(entry.$ref);
      return `    ${variantName}(${variantName}),`;
    }).join('\n');
    return `#[derive(Clone, Debug, PartialEq)]\npub enum ${name} {\n${variants}\n}`;
  }
  if (def.type === 'object' && def.properties && Object.keys(def.properties).length > 0) {
    const required = new Set(def.required ?? []);
    const fields = Object.entries(def.properties).map(([field, fieldDef]) => {
      const base = rustType(fieldDef);
      const fieldType = required.has(field) || base.startsWith('Option<') ? base : `Option<${base}>`;
      return `    pub ${rustFieldName(field)}: ${fieldType},`;
    }).join('\n');
    return `#[derive(Clone, Debug, PartialEq)]\npub struct ${name} {\n${fields}\n}`;
  }
  return `pub type ${name} = ${rustType(def)};`;
}

function generateRust() {
  const lines = [
    '// Generated by scripts/generateBlueprintSchemaTypes.mjs from src/game/sim/blueprints/blueprintSchema.json.',
    '// Do not edit this file directly.',
    '#![allow(dead_code)]',
    '#![allow(non_camel_case_types)]',
    '#![allow(non_snake_case)]',
    '',
    'use std::collections::BTreeMap;',
    '',
    '#[derive(Clone, Debug, PartialEq)]',
    'pub enum BlueprintJsonValue {',
    '    Null,',
    '    Bool(bool),',
    '    Number(f64),',
    '    String(String),',
    '    Array(Vec<BlueprintJsonValue>),',
    '    Object(BTreeMap<String, BlueprintJsonValue>),',
    '}',
    '',
  ];

  for (const [name, def] of Object.entries(defs)) {
    lines.push(generateRustDef(name, def));
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

fs.writeFileSync(tsOutPath, generateTs());
fs.writeFileSync(rustOutPath, generateRust());
