import { WATER_RENDER_CONFIG } from './config';
import type { GraphicsConfig } from './types/graphics';

export const PLAYER_CLIENT_MAX_GRAPHICS_CONFIG: GraphicsConfig = {
  tier: 'max',
  unitRenderMode: 'rich',
  hudFrameStride: 1,
  effectFrameStride: 1,
  terrainTileFrameStride: 1,
  terrainTileSideWalls: true,
  waterSubdivisions: 96,
  waterFrameStride: 1,
  waterWaveAmplitude: 6,
  waterOpacity: WATER_RENDER_CONFIG.opacity,
  unitShape: 'full',
  legs: 'full',
  treadsAnimated: true,
  chassisDetail: true,
  paletteShading: true,
  turretStyle: 'full',
  forceTurretStyle: 'full',
  barrelSpin: true,
  beamStyle: 'detailed',
  beamGlow: true,
  antialias: false,
  burnMarkDensity: 1,
  groundPrintDensity: 1,
  smokeTrailFramesSkip: 0,
  projectileStyle: 'trail',
  fireExplosionStyle: 'inferno',
  materialExplosionStyle: 'obliterate',
  materialExplosionPieceBudget: 40,
  materialExplosionPhysicsFramesSkip: 0,
  deathExplosionStyle: 'obliterate',
};
